### PR TITLE
Added link to get started with Camel in general.

### PR DESCRIPTION
**Pull request by spatnity**

### CODE REVIEW

**Comment by spatnity** [comment]
This is for #3580

**Review by oscerd — APPROVED** [review]

**Review by zhfeng — APPROVED** [review]

**Review by aldettinger — APPROVED** [review]
There seems to be a single version of the camel getting started link. Looks good.

**Comment by ppalaga** [comment]
Thanks @spatnity!

**Comment by davsclaus** [comment]
I had to revert this commit as it breaks the website build
11650d6739097c3e0e80345add0b7ef250b0acd2

[check:html     ] public/camel-quarkus/next/user-guide/index.html
[check:html     ]   1:50606  error  For links within camel.apache.org use relative links, found: https://camel.apache.org/manual/getting-started.html  camel/relative-links

I dont know the top of my head how to do relative links between the projects (try to find in some other docs how that is done) and send another PR, thanks

**Comment by jamesnetherton** [comment]
I think the correct link should be like:

```
 xref:manual::getting-started.adoc[Getting started with Camel]
```

**Comment by davsclaus** [comment]
Thanks we can try this after this job is done
https://github.com/apache/camel-website/actions/runs/5129187679/jobs/9228170859?pr=1006

**Comment by davsclaus** [comment]
Okay lets try with
https://github.com/apache/camel-quarkus/commit/8f72af5e8a10ba53aaee1f23fbf0587bfcd0690c

**Pull request merged**
