### PR TITLE
1672 as2 too much time second attempt

### LINKED ISSUE #1672: Check whether it is possible to reduce the amount of RAM spent by the AS2 itest
As seen in this job, https://github.com/apache/camel-quarkus/pull/1670/checks?check_run_id=1061031500#step:9:1345
the native compilation of the AS2 itest takes too much RAM and too much time. I wonder whether there is any potential to strip down the amount of compiled code somehow so that less RAM and less time is needed. @JiriOndrusek  would you mind having a look?

### PR DESCRIPTION
**Pull request by JiriOndrusek**
Fixes #1672

Adds configuration for bouncycastle extension. It now requires user to define all ciphers and digest at build time, which has impact on memory requirements.

This change can be merged. It is an isolated fix.

Replaces https://github.com/apache/camel-quarkus/pull/1686

[ ] An issue should be filed for the change unless this is a trivial change (fixing a typo or similar). One issue should ideally be fixed by not more than one commit and the other way round, each commit should fix just one issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful and properly spelled subject line and body. Copying the title of the associated issue is typically enough. Please include the issue number in the commit message prefixed by #.
[ ] The pull request description should explain what the pull request does, how, and why. If the info is available in the associated issue or some other external document, a link is enough.
[ ] Phrases like Fix #<issueNumber> or Fixes #<issueNumber> will auto-close the named issue upon merging the pull request. Using them is typically a good idea.
[ ] Please run mvn process-resources -Pformat (and amend the changes if necessary) before sending the pull request.
[ ] Contributor guide is your good friend: https://camel.apache.org/camel-quarkus/latest/contributor-guide.html

### CODE REVIEW

**Comment by JiriOndrusek** [comment]
@ppalaga Here is fixed and rebased attempt for optimization (from PR https://github.com/apache/camel-quarkus/pull/1686)

In my POV it could be merged even if this is not the best optimization as possible (probably) - but still it is an optimization. I'll try to find better ones.

**Comment by ppalaga** [comment]
As I said on the chat, although we should try to improve the 25mins AS2 native build, there is no urgent need to do so quickly, because the total CI times are in quite a good shape ATM. 

New config options are a kind of user facing contract that we should avoid breaking as far as possible. So I'd prefer that we continue our investigation and gather enough evidence that the new config options are useful in the long term.

**Comment by JiriOndrusek** [comment]
@ppalaga  ok, I'll try to gather more optimizations into one  PR.

Did something happen? I'm looking into log form misc run, which contains as2 and see 5 mins (https://github.com/apache/camel-quarkus/pull/1723/checks?check_run_id=1081972054#step:9:1499)
> NFO] Camel Quarkus :: Integration Tests :: AS2 .......... SUCCESS [05:31 min]

Memory values are also smaller:
> [camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]    classlist:   9,334.93 ms,  1.18 GB
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]        (cap):     743.82 ms,  1.18 GB
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]        setup:   3,019.14 ms,  1.18 GB
14:31:44,532 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]     (clinit):   1,032.06 ms,  2.91 GB
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]   (typeflow):  38,405.29 ms,  2.91 GB
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]    (objects):  64,402.55 ms,  2.91 GB
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]   (features):   2,541.14 ms,  2.91 GB
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]     analysis: 109,059.42 ms,  2.91 GB
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]     universe:   3,247.39 ms,  2.88 GB
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]      (parse):  19,484.60 ms,  3.34 GB
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]     (inline):  27,183.85 ms,  4.33 GB
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]    (compile):  72,688.11 ms,  4.55 GB
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]      compile: 124,011.35 ms,  4.62 GB
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]        image:  10,471.53 ms,  4.36 GB
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]        write:   8,725.64 ms,  4.36 GB
[camel-quarkus-integration-test-as2-1.1.0-SNAPSHOT-runner:25]      [total]: 268,668.58 ms,  4.36 GB

If this is caused by newer quarkus version, then there is no need for another optimization... (<quarkus.version>1.8.0.CR1</quarkus.version>)

WDYT?

**Comment by ppalaga** [comment]
We should always compare against a build that is close enough. This one from yesterday took 6:29: https://github.com/apache/camel-quarkus/runs/1081877206?check_suite_focus=true#step:9:1500
Yes, the general improvement may well be caused by the upgrade to GraalVM 20.2.0 via Quarkus 1.8.0.CR1. 
I think that reducing the build time by a minute and image disk size by 10MB is worth the effort. Esp. if we learn tricks that we can re-use elsewhere.

**Comment by JiriOndrusek** [comment]
Because of the fact that currently native build takes slightly over 6 mins (`Finished generating 'camel-quarkus-integration-test-as2-2.16.0-SNAPSHOT-runner' in 6m 16s.`) and because the optimization proposed by this PR can not be used -> limiting algorithms reduces the testing coverage, Im closing theis PR. Issue is still opened, therefore if needed, new optimization attempt may be done. 
The current better results are probably achieved by the newer quarkus bits `2.16.0.Final`. (in the time of creating this PR the version was `1.x`.

**Pull request closed without merging**
