### PR TITLE
Upgrade to Quarkus 3.3.0

### LINKED ISSUE #4467: [Mandrel 22.3.1] CXF SOAP native image compilation failure
```
2023-02-01T04:15:36.7285943Z Error: Class initialization of org.apache.neethi.builders.converters.OMToDOMConverter failed. This error is reported at image build time because class org.apache.neethi.builders.converters.OMToDOMConverter is registered for linking at image build time by command line Use the option --initialize-at-run-time=org.apache.neethi.builders.converters.OMToDOMConverter to explicitly request delayed initialization of this class.
2023-02-01T04:15:36.7286881Z Detailed message:
2023-02-01T04:15:36.7287018Z 
2023-02-01T04:15:36.7288222Z com.oracle.svm.core.util.UserError$UserException: Class initialization of org.apache.neethi.builders.converters.OMToDOMConverter failed. This error is reported at image build time because class org.apache.neethi.builders.converters.OMToDOMConverter is registered for linking at image build time by command line Use the option --initialize-at-run-time=org.apache.neethi.builders.converters.OMToDOMConverter to explicitly request delayed initialization of this class.
2023-02-01T04:15:36.7289111Z Detailed message:
2023-02-01T04:15:36.7289222Z 
2023-02-01T04:15:36.7289466Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
2023-02-01T04:15:36.7290021Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
2023-02-01T04:15:36.7290656Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:776)
2023-02-01T04:15:36.7291277Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
2023-02-01T04:15:36.7291838Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
2023-02-01T04:15:36.7292449Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
2023-02-01T04:15:36.7293097Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
2023-02-01T04:15:36.7293727Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
2023-02-01T04:15:36.7295243Z Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Class initialization of org.apache.neethi.builders.converters.OMToDOMConverter failed. This error is reported at image build time because class org.apache.neethi.builders.converters.OMToDOMConverter is registered for linking at image build time by command line Use the option --initialize-at-run-time=org.apache.neethi.builders.converters.OMToDOMConverter to explicitly request delayed initialization of this class.
2023-02-01T04:15:36.7296217Z Detailed message:
2023-02-01T04:15:36.7296331Z 
2023-02-01T04:15:36.7296666Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
2023-02-01T04:15:36.7299669Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:771)
2023-02-01T04:15:36.7300087Z 	... 5 more
2023-02-01T04:15:36.7300544Z Caused by: java.lang.NoClassDefFoundError: org/apache/axiom/om/OMException
2023-02-01T04:15:36.7300970Z 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
2023-02-01T04:15:36.7301420Z 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
```

### PR DESCRIPTION
**Pull request by ppalaga**
Fix #4467

### CODE REVIEW

**Comment by zhfeng** [comment]
Hi @ppalaga,

Before merging this PR, can you create a `3.2.x` branch becasue we are looking for a new camel-quarkus release based the Quarkus 3.2 LTS ?

**Comment by ppalaga** [comment]
This was not meant to be merged immediately. But OTOH it is true that we should also release for Quarkus Platform 3.3, which should be due next week. Anyway, I am not sure this PR is complete. E.g. https://github.com/apache/camel-quarkus/issues/5110 might need to get adressed before we merge and release for 3.3. WDYT, @jamesnetherton?

**Comment by zbendhiba** [comment]
FYI, I'm about to rebase quarkus-main

**Comment by zbendhiba** [comment]
Opened another PR https://github.com/apache/camel-quarkus/pull/5236 to get rid of the 999-SNAPSHOT in the CI errors

**Pull request closed without merging**
