### PR TITLE
Mail test fails in native mode #4519

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/apache/camel-quarkus/issues/4519

replaces https://github.com/apache/camel-quarkus/pull/4529

### CODE REVIEW

**Comment by JiriOndrusek** [comment]
@jamesnetherton thanks for the comment for previous PR, I felt that something is not correct, but didn't know wat

**Review by oscerd — APPROVED** [review]

**Review by ppalaga — APPROVED** [review]
Thanks @JiriOndrusek !

It looks like the CI is not triggered for PRs against camel-4 branch. I'll either cherry-pick this fix to camel-4 if I have to do a new iteration in https://github.com/apache/camel-quarkus/pull/4504 or we first merge https://github.com/apache/camel-quarkus/pull/4504 to main and then we'll re-target this PR for main.

**Comment by ppalaga** [comment]
https://github.com/apache/camel-quarkus/pull/4504 is merged to main. I have changed the target of this PR to main, but there is a conflict. Could you please rebase @JiriOndrusek ?

**Comment by JiriOndrusek** [comment]
yes, I'll do that, thanks

**Comment by ppalaga** [comment]
Thanks, @JiriOndrusek !

**Pull request merged**
