### PR TITLE
Fix #599 Document the need to set quarkus.native.add-all-charsets = true in HTTP extensions

### LINKED ISSUE #599: Document the need to set quarkus.native.add-all-charsets = true in HTTP extensions
AHC and HTTP components are the prominent candidates. 

Why: They offer the option to decode the response body using the encoding sent by the server which can be any encoding.

https://github.com/apache/camel-quarkus/pull/597#discussion_r363188082

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
ok to test

**Comment by ppalaga** [comment]
The port conflict failures apparently have nothing to do with the current change. Do we need to re-test?

**Comment by lburgazzoli** [comment]
HystrixTest.testHystrixFallback is also failing but not because of port conflict

**Comment by ppalaga** [comment]
retest this please

**Comment by ppalaga** [comment]
rebased 83de21f

**Pull request merged**
