### PR TITLE
Ban javax.el:el-api in favor of  jakarta.el:jakarta.el-api

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by zhfeng — APPROVED** [review]

**Comment by ppalaga** [comment]
Let's try the new GH actions functionality to re-run only the fallen jobs

**Review by aldettinger — APPROVED** [review]

**Comment by ppalaga** [comment]
@aldettinger isn't the file test failure on Java 17 something that we were addressing recently?

**Comment by aldettinger** [comment]
Indeed, but it was re-opened. I think we have just narrowed down the frequency. We follow that in https://github.com/apache/camel-quarkus/issues/3584.

**Comment by ppalaga** [comment]
Thanks @aldettinger merging this one then.

**Pull request merged**
