### PR TITLE
Upgrade to Quarkus 3.3.1

### PR DESCRIPTION
**Pull request by zbendhiba**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by zbendhiba** [comment]
I'm going to look at those failing tests to fix them

**Comment by zbendhiba** [comment]
I'm going to rebase and push again

**Review by aldettinger — APPROVED** [review]
As far as I get LGTM.

Not sure why #4894 is needed for Quarkus upgrade. There might be good reason.

**Comment by jamesnetherton** [comment]
> There might be good reason.

It was added to `quarkus-main` some time ago. There are Quarkus changes that it depends on that were only added in 3.3.x.

**Pull request merged**
