### PR TITLE
[3.8.x] Fix #6301 to resort the beans if priority is same the default one win…

### LINKED ISSUE #6301: Bean autowiring is non-deterministic when multiple beans exist with no @Priority
### Bug description

Relates to #5464. The code changes for that feature assume that if there are multiple beans for a given type, that they will have an `@Priority` assigned, so that the desired bean is returned from registry lookups.

IMO this is only reliable for beans declared from user code. The majority of beans created by Quarkus extensions do not have any `@Priority` (AFAIK). E.g like `DataSource` beans.

Thus, when Camel attempts to do autowiring, it will potentially inject a 'random' bean into components, since there is no `@Priority` enforced.

### PR DESCRIPTION
**Pull request by zhfeng**
…s (#6304)

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by jamesnetherton — APPROVED** [review]

**Comment by zhfeng** [comment]
@jamesnetherton The `hazelcast` native failure is a known issue?

**Comment by jamesnetherton** [comment]
> @jamesnetherton The `hazelcast` native failure is a known issue?

I guess the native builder has been updated since the last CI run on `3.8.x`.

Here's the workaround:

https://github.com/apache/camel-quarkus/blob/main/extensions/hazelcast/deployment/src/main/java/org/apache/camel/quarkus/component/hazelcast/deployment/HazelcastProcessor.java#L108

**Comment by zhfeng** [comment]
Is it good to merge this PR and backport the above workaround in a seperated one?

**Comment by jamesnetherton** [comment]
> Is it good to merge this PR and backport the above workaround in a seperated one?

Yes, no problem 👍

**Pull request merged**
