### PR TITLE
Add Camel-AWS-ECS extension

### LINKED ISSUE #17: Add Camel-AWS-ECS extension

### PR DESCRIPTION
**Pull request by oscerd**
Fixes #17

### CODE REVIEW

**Comment by oscerd** [comment]
ok to test

**Comment by oscerd** [comment]
The error seems to be related to Fhir

**Comment by oscerd** [comment]
@johnpoth can you have a look, following the last two steps of the contributors guide the FHIR extension fails.

**Comment by oscerd** [comment]
ok to test

**Comment by oscerd** [comment]
There are no AWS credentials on CI, I use my personal one and I tested the extension by myself.

**Comment by oscerd** [comment]
We never had shared credentials, even on Apache Camel.

**Comment by ppalaga** [comment]
> I use my personal one

Yes, thanks, that's the last state I remember. I just wondered if anything changed in between. It would be nice if we could test on the CI.

**Pull request merged**
