### PR TITLE
Fix commons-logging setup

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
> +1 for the cleanup.
> 
> So the rule you are hereby coining is that we should exclude in the BOM rather than in the runtime modules, right?
> 

I would say yes but no strong opinion on it, what's your ?

> We could actually ban commons-logging via an enforcer rule, WDYT?

Yes we should

**Comment by lburgazzoli** [comment]
ok to test

**Comment by ppalaga** [comment]
> > So the rule you are hereby coining is that we should exclude in the BOM rather than in the runtime modules, right?
> 
> I would say yes but no strong opinion on it, what's your ?

I do not mind such a rule, neither I have a strong opinion about where it should be done.

**Comment by lburgazzoli** [comment]
> 
> I do not mind such a rule, neither I have a strong opinion about where it should be done.

So let's see how it goes

**Pull request merged**
