### PR TITLE
Fixed reference to Kamelets catalog

### PR DESCRIPTION
**Pull request by oscerd**
Other part of #3069

### CODE REVIEW

**Comment by zbendhiba** [comment]
It seems to me same as https://github.com/apache/camel-quarkus/pull/3069 ?

**Comment by oscerd** [comment]
One it's in the adoc from the main tree, the other one is the doc generation. I was from browser

**Review by zbendhiba — APPROVED** [review]

**Review by aldettinger — APPROVED** [review]
I agree the doc reference needs to be corrected. However, it looks to me that #3069 and #3070 really points to the same change. Hence, it may be that there is no PR fixing the generated doc `docs/modules/ROOT/pages/reference/extensions/kamelet.adoc` at all.

**Comment by oscerd** [comment]
Sorry, I'll close the other one.

**Pull request merged**
