### PR TITLE
Camel DataSonnet Extension  - resolves Issue #2078 (needs Scala >= 2.13)

### PR DESCRIPTION
**Pull request by javaduke**

### CODE REVIEW

**Comment by javaduke** [comment]
@aldettinger I created this PR and I'm going to close the old one.

**Comment by javaduke** [comment]
Hmm, not sure what this error means:
```
Caused by: java.lang.RuntimeException: Too little or too much org.apache.camel:* entries in camel-quarkus-bom:
[2920](https://github.com/apache/camel-quarkus/runs/6214331067?check_suite_focus=true#step:8:2920)

[2921](https://github.com/apache/camel-quarkus/runs/6214331067?check_suite_focus=true#step:8:2921)
    Extra content at line 89:
[2922](https://github.com/apache/camel-quarkus/runs/6214331067?check_suite_focus=true#step:8:2922)
  ["org.apache.camel:camel-datasonnet"]
[2923](https://github.com/apache/camel-quarkus/runs/6214331067?check_suite_focus=true#step:8:2923)

[2924](https://github.com/apache/camel-quarkus/runs/6214331067?check_suite_focus=true#step:8:2924)

[2925](https://github.com/apache/camel-quarkus/runs/6214331067?check_suite_focus=true#step:8:2925)
Consider adding, removing or excluding them in the BOM
```
Are there any dependencies I need to exclude?

**Comment by ppalaga** [comment]
> Hmm, not sure what this error means:
> 
> ```
> Caused by: java.lang.RuntimeException: Too little or too much org.apache.camel:* entries in camel-quarkus-bom:
> [2920](https://github.com/apache/camel-quarkus/runs/6214331067?check_suite_focus=true#step:8:2920)
> 
> [2921](https://github.com/apache/camel-quarkus/runs/6214331067?check_suite_focus=true#step:8:2921)
>     Extra content at line 89:
> [2922](https://github.com/apache/camel-quarkus/runs/6214331067?check_suite_focus=true#step:8:2922)
>   ["org.apache.camel:camel-datasonnet"]
> [2923](https://github.com/apache/camel-quarkus/runs/6214331067?check_suite_focus=true#step:8:2923)
> 
> [2924](https://github.com/apache/camel-quarkus/runs/6214331067?check_suite_focus=true#step:8:2924)
> 
> [2925](https://github.com/apache/camel-quarkus/runs/6214331067?check_suite_focus=true#step:8:2925)
> Consider adding, removing or excluding them in the BOM
> ```
> 
> Are there any dependencies I need to exclude?

Looks like you figured out in between?

Once again please, if you could rebase on top of target branch rather than merging it. The resulting history is much easier to read like that. Also, if you could please squash your commits for the same reason.

**Comment by javaduke** [comment]
Really sorry about it, I tried to squash and rebase, but ran into al kinds of conflicts and errors and ended up making a mess again. Would it be possible to squash and merge the PR instead?

**Comment by ppalaga** [comment]
> Really sorry about it, I tried to squash and rebase, but ran into al kinds of conflicts and errors and ended up making a mess again. 
> Would it be possible to squash and merge the PR instead?

I doubt it is even possible as long as there are conflicts. Basically it is you who should know best how to solve them. BTW, having less commits in the topic branch may make rebasing a bit easier. 
I guess after #3767 is merged, this PR can again target the main branch.

**Pull request closed without merging**
