### PR TITLE
[minor] Typo/Grammatical Corrections

### PR DESCRIPTION
**Pull request by PoojaChandak**
[ ] An issue should be filed for the change unless this is a trivial change (fixing a typo or similar). One issue should ideally be fixed by not more than one commit and the other way round, each commit should fix just one issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful and properly spelled subject line and body. Copying the title of the associated issue is typically enough. Please include the issue number in the commit message prefixed by #.
[ ] The pull request description should explain what the pull request does, how, and why. If the info is available in the associated issue or some other external document, a link is enough.
[ ] Phrases like Fix #<issueNumber> or Fixes #<issueNumber> will auto-close the named issue upon merging the pull request. Using them is typically a good idea.
[ ] Please run mvn process-resources -Pformat (and amend the changes if necessary) before sending the pull request.
[ ] Contributor guide is your good friend: https://camel.apache.org/camel-quarkus/latest/contributor-guide.html

### CODE REVIEW

**Review by jamesnetherton — COMMENTED** [review]
The extension doc pages are auto generated based on the information from the camel catalog, so shouldn't really be edited manually.

It'd be better to fix the atmos typo here first:

https://github.com/apache/camel/blob/992a6b9685f4db49236e540af2546548cf99a7d3/components/camel-atmos/src/main/java/org/apache/camel/component/atmos/AtmosEndpoint.java#L38

I already fixed the `retrie` typo in Camel. When the project upgrades to Camel 3.5.0 it'll pick up that change:

https://github.com/apache/camel/commit/4d94139f9567f257f8035056bc410f580286f672#diff-eb49992bc3a18fb954e8613c460fcb79

I'd drop the changes to `atmos.adoc` and `index.adoc` from this PR. The other improvements to `first-steps.adoc `& `native-mode.adoc` look ok to me.

**Review by oscerd — CHANGES_REQUESTED** [review]
I'll update the atmos typo for 3.6.0

**Comment by PoojaChandak** [comment]
Let me know if any changes are expected on my end

**Comment by jamesnetherton** [comment]
> Let me know if any changes are expected on my end

Please drop commits a52f441 & 607dfda from this PR.

**Comment by PoojaChandak** [comment]
Review comments added

**Comment by ppalaga** [comment]
let me cherry-pick 95180f6 and 954a1f4 manually to avoid four unnecessary commits

**Comment by ppalaga** [comment]
Cherry-picked as 8554bd6777d1b3b6c4555347359dbd6cf9f2e7d5 and a5ee3fa131ce84813c443cf9ada376c53c4fb196 in the master. Thanks @PoojaChandak !

**Pull request closed without merging**
