### PR TITLE
Migrate Camel extensions from Quarkus

### PR DESCRIPTION
**Pull request by ppalaga**
@lburgazzoli @davsclaus this is currently just the raw filtered commits from Quarkus for an early review. The wiring into the parent pom is yet to be done. So please, do not merge yet, just comment if you see something suspicious.

### CODE REVIEW

**Comment by davsclaus** [comment]
Okay thanks, yeah its a bunch of code. After the initial commit, we should then migrate this code as-is to ASF standard (license headers, package name rename, artifact id name rename etc)

**Comment by ppalaga** [comment]
About the new iteration ending with 8ecbd58 :

* Still WiP
* Refined the import of commits from Quarkus:
  * Merge commits kept because some of them contain code changes that I was not able to keep in any other way
  * Directory structure simplified, `camel-` removed from some directory names
* POM wiring done, the whole thing is passing `mvn clean install` - i.e. with tests in JVM mode.
* Next step: Native mode

**Comment by ppalaga** [comment]
I can confim that 8ecbd58 is passing in the native mode too.

Let me do the final cleanup

**Comment by lburgazzoli** [comment]
> About the new iteration ending with [8ecbd58](https://github.com/apache/camel-quarkus/commit/8ecbd58cc71ddec5928dbd119d1c1f320be127ec) :
> 
>     * Still WiP
> 
>     * Refined the import of commits from Quarkus:
>       
>       * Merge commits kept because some of them contain code changes that I was not able to keep in any other way
>       * Directory structure simplified, `camel-` removed from some directory names

Not having a strong opinion here but since the other camel projects have the `camel-`  prefix I'd go for keep it.

> 
>     * POM wiring done, the whole thing is passing `mvn clean install` - i.e. with tests in JVM mode.
> 
>     * Next step: Native mode

**Comment by ppalaga** [comment]
I added 415d15d just to see if TravisCI was really activated for this repo - and it seems to work well.

**Comment by lburgazzoli** [comment]
@ppalaga can we do 1 thing at time ? i.e. the travis thing can be a seprate PR that can be merged independently from the migration one

**Comment by ppalaga** [comment]
> @ppalaga can we do 1 thing at time ? i.e. the travis thing can be a seprate PR that can be merged independently from the migration one

Of course. I added it just to trigger the CI, because it is super important to see the CI pass for the current PR. Let me remove it again.

**Comment by ppalaga** [comment]
> > ```
> > `camel-` removed from some directory names
> > ```
> 
> 
> Not having a strong opinion here but since the other camel projects have the `camel-`  prefix I'd go for keep it.

I just checked how is the Camel main repo using `camel-` in directory names and I cannot confirm that `camel-` would be used in all places. 

I slightly prefer the shorter variant because:

* It is faster to type on the console - this matters a lot for at least:
  * `cd`
  * `git add`
* Path listings are easier to read. Often excluding `camel-` will eliminate the need for wrapping the paths. This is important for at least:
  * Maven error messages and warnings
  * `git status`

Is this worth discussing on camel-dev ML?

**Comment by lburgazzoli** [comment]
camel- is used for all the component, starter and so on, that's what I meant

**Comment by ppalaga** [comment]
4e0ac7b is based on Quarkus tag 0.18.0

**Pull request merged**
