### PR TITLE
Upgrade to Camel 3.0.0-M4

### PR DESCRIPTION
**Pull request by ppalaga**
Partly an adaptation of @gnodet 's https://github.com/gnodet/quarkus/tree/camel-m3

### CODE REVIEW

**Comment by ppalaga** [comment]
Not a draft anymore. Please review. Cc @gnodet

**Comment by ppalaga** [comment]
The failures popping up on Jenkins with 407d22c were caused by #80. eec554d workarounds them all except in infinispan where the native image build is simply disabled.

**Comment by oscerd** [comment]
Why is it disabled?

**Comment by ppalaga** [comment]
I was neither able to fix it or find a workaround on our side. The core of the problem is well described in https://github.com/quarkusio/quarkus/issues/3300 I'd need to consult with @lburgazzoli what strategy we should take. I think we can merge like this and figure out when @lburgazzoli is back.

**Comment by ppalaga** [comment]
Is this good to merge, @oscerd ?

**Comment by ppalaga** [comment]
070205b is the result of rebasing on top of the current master.

**Pull request merged**
