### PR TITLE
[update] Upgrade testcontainers version

### PR DESCRIPTION
**Pull request by llowinge**
We finally have https://github.com/testcontainers/testcontainers-java/releases/tag/1.15.2 :)

### CODE REVIEW

**Comment by llowinge** [comment]
@jamesnetherton FYI

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
Is it actually in Maven central yet? Last time I checked it was not.

**Comment by llowinge** [comment]
@jamesnetherton You are right, it is not there :-O

**Review by jamesnetherton — APPROVED** [review]

**Comment by jamesnetherton** [comment]
I'll merge this. Test failure seems to be flaky test in spring-rabbitmq which I'll look into further tomorrow.

**Pull request merged**
