### PR TITLE
Re-enable google-pubsub and google-storage and add a workaround

### PR DESCRIPTION
**Pull request by zhfeng**
It should fix 
- #5007 
- #5010

### CODE REVIEW

**Comment by jamesnetherton** [comment]
Looks fine.

But, I think we should drop a note into the extension docs about this so folks are aware that the workaround is required. I don't think there's any way for us to apply it for them automatically.

**Comment by zhfeng** [comment]
Oh, yeah, so put it in e.g. `./extensions/google-pubsub/runtime/src/main/doc/limitations.adoc`?

**Comment by jamesnetherton** [comment]
> put it in e.g. `./extensions/google-pubsub/runtime/src/main/doc/limitations.adoc`?

Yeah, that's fine to add for the `pubsub` & `storage` extensions :+1:

**Comment by zhfeng** [comment]
OK, I add them all. `google-bigquery` has another issue with `apache-arrow` due to the netty upgrading. I hope it can be fixed with some new releases in the future.

**Review by jamesnetherton — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by ppalaga** [comment]
Would please somebody explain, why the `RunReachabilityHandlersConcurrently` option cannot be passed via `quarkus.native.additional-build-args`?

**Pull request merged**
