### PR TITLE
Build with JDK 16 as 15 is EOL

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
Looks like some more work is needed for this. I'll investigate & revisit soon.

**Comment by jamesnetherton** [comment]
@ppalaga (or anyone who's interested). We have a working build on JDK 16. Had to do some workarounds for Spark, Kudu,  LevelDB & Kotlin but everything else seems to work ok.

**Review by ppalaga — APPROVED** [review]
Great job, @jamesnetherton! Thanks a lot!

**Comment by zbendhiba** [comment]
thanks @jamesnetherton

**Pull request merged**
