### PR TITLE
Added Redis Aggregation Repository support in JVM mode only #2085

### PR DESCRIPTION
**Pull request by aldettinger**
[ ] An issue should be filed for the change unless this is a trivial change (fixing a typo or similar). One issue should ideally be fixed by not more than one commit and the other way round, each commit should fix just one issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful and properly spelled subject line and body. Copying the title of the associated issue is typically enough. Please include the issue number in the commit message prefixed by #.
[ ] The pull request description should explain what the pull request does, how, and why. If the info is available in the associated issue or some other external document, a link is enough.
[ ] Phrases like Fix #<issueNumber> or Fixes #<issueNumber> will auto-close the named issue upon merging the pull request. Using them is typically a good idea.
[ ] Please run mvn process-resources -Pformat (and amend the changes if necessary) before sending the pull request.
[ ] Contributor guide is your good friend: https://camel.apache.org/camel-quarkus/latest/contributor-guide.html

JVM only as Redisson seems not quarkus native friendly, I'm opening a follow up.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by aldettinger** [comment]
I'm not able to workaround the build issue. But it seems unrelated.

**Comment by ppalaga** [comment]
> I'm not able to workaround the build issue. But it seems unrelated.

See https://github.com/apache/camel-quarkus/pull/2110

**Comment by jamesnetherton** [comment]
Wondering for native support whether we should think about having Camel support for `vertx-redis-client`? Then we could leverage Quarkus Redis and get the native bits for free, rather than spend time on Redisson.

**Comment by aldettinger** [comment]
Yeah, the quarkus community has taken this [path](https://github.com/quarkusio/quarkus/issues/4453#issuecomment-542042896). The potential benefits make it worth taking a look.

As far as I see, changing the underlying client shouldn't break any contract, so I think it is safe to start with redisson JVM only and then upgrade to vertx-redis-client for native.

**Review by ppalaga — APPROVED** [review]

**Pull request merged**
