### PR TITLE
Update qute.json to 3.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by zhfeng**
I think this file is generated but our CI building has not complain about these uncommitted changes. I'm not sure if there is anything need to check.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
> I'm not sure if there is anything need to check.

Move the `camel-package-maven-plugin` execution to phase `process-classes`. Otherwise the Jandex index that it queries to do the component generation will be empty.

**Comment by zhfeng** [comment]
@jamesnetherton Hmm, but there is no `jandex-maven-plugin` in `extensions/qute/component/pom.xml`.

**Comment by jamesnetherton** [comment]
> @jamesnetherton Hmm, but there is no `jandex-maven-plugin` in `extensions/qute/component/pom.xml`.

IIRC it's not needed. The `camel-package-maven-plugin` generates the index itself.

**Comment by aldettinger** [comment]
The release process mention to [regen Qute Camel component metadata](https://camel.apache.org/camel-quarkus/2.16.x/contributor-guide/release-guide.html#_next_version_in_camel_quarkus_main_branch). Is there any link with this ?

**Pull request merged**
