### PR TITLE
[WIP] Upgrade to Quarkus 1.1.0.CR1 and fix various upgrade issues

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
ok to test

**Comment by lburgazzoli** [comment]
Jenkins node is shutting down, gogin to test it locally in native mode

**Comment by gsmet** [comment]
I tested JDK but not native. Note that you need GraalVM 19.3.0 Java 8 for native testing.

**Comment by lburgazzoli** [comment]
```
mvn clean install -Dnative -rf :camel-quarkus-integration-test-bean
```

Fails with:

```
Fatal error: java.lang.RuntimeException: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /project/camel-quarkus-integration-test-bean-1.0.0-SNAPSHOT-runner -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-7870806881164755349/exported_symbols.list -Wl,-x -L/tmp/SVM-7870806881164755349 -L/opt/graalvm/jre/lib -L/opt/graalvm/jre/lib/svm/clibraries/linux-amd64 /tmp/SVM-7870806881164755349/camel-quarkus-integration-test-bean-1.0.0-SNAPSHOT-runner.o /opt/graalvm/jre/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm/jre/lib/svm/clibraries/linux-amd64/libjvm.a /opt/graalvm/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/graalvm/jre/lib/libzip.a /opt/graalvm/jre/lib/libnet.a /opt/graalvm/jre/lib/libjava.a /opt/graalvm/jre/lib/libnio.a /opt/graalvm/jre/lib/libsunec.a /opt/graalvm/jre/lib/libsunec.a -lm -lpthread -ldl -lpthread -lz -lrt -lstdc++

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.3.1 20190507 (Red Hat 8.3.1-4) (GCC) 
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/8/:/usr/libexec/gcc/x86_64-redhat-linux/8/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/8/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/8/:/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/8/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/project/camel-quarkus-integration-test-bean-1.0.0-SNAPSHOT-runner' '-z' 'noexecstack' '-L/tmp/SVM-7870806881164755349' '-L/opt/graalvm/jre/lib' '-L/opt/graalvm/jre/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/8/collect2 -plugin /usr/libexec/gcc/x86_64-redhat-linux/8/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper -plugin-opt=-fresolution=/tmp/ccJfrNDn.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /project/camel-quarkus-integration-test-bean-1.0.0-SNAPSHOT-runner -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/8/crtbegin.o -L/tmp/SVM-7870806881164755349 -L/opt/graalvm/jre/lib -L/opt/graalvm/jre/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/8 -L/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/8/../../.. --gc-sections --dynamic-list /tmp/SVM-7870806881164755349/exported_symbols.list -x /tmp/SVM-7870806881164755349/camel-quarkus-integration-test-bean-1.0.0-SNAPSHOT-runner.o /opt/graalvm/jre/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm/jre/lib/svm/clibraries/linux-amd64/libjvm.a /opt/graalvm/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/graalvm/jre/lib/libzip.a /opt/graalvm/jre/lib/libnet.a /opt/graalvm/jre/lib/libjava.a /opt/graalvm/jre/lib/libnio.a /opt/graalvm/jre/lib/libsunec.a /opt/graalvm/jre/lib/libsunec.a -lm -lpthread -ldl -lpthread -lz -lrt -lstdc++ -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-redhat-linux/8/crtend.o /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crtn.o
/opt/graalvm/jre/lib/libjava.a(Proxy.o): In function `Java_java_lang_reflect_Proxy_defineClass0':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/java/lang/reflect/Proxy.c:97: undefined reference to `VerifyFixClassname'
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/java/lang/reflect/Proxy.c:97: undefined reference to `VerifyFixClassname'
collect2: error: ld returned 1 exit status

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:315)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:454)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
Caused by: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1
```

**Comment by gsmet** [comment]
FWIW, I reproduce it on my Fedora 30.

**Comment by lburgazzoli** [comment]
Same issue even by using GraalVM 19.3.0 as JDK:

```
$ java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07)
OpenJDK 64-Bit GraalVM CE 19.3.0 (build 25.232-b07-jvmci-19.3-b05, mixed mode)

$ rpm -qa | grep libstdc++
libstdc++-9.2.1-1.fc31.x86_64
libstdc++-static-9.2.1-1.fc31.x86_64
libstdc++-devel-9.2.1-1.fc31.x86_64
```

Error:

```
atal error: java.lang.RuntimeException: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /home/lburgazz/work/apache/dev/camel-quarkus/integration-tests/bean/target/camel-quarkus-integration-test-bean-1.0.0-SNAPSHOT-native-image-source-jar/camel-quarkus-integration-test-bean-1.0.0-SNAPSHOT-runner -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-2495369923502253727/exported_symbols.list -Wl,-x -L/tmp/SVM-2495369923502253727 -L/opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib -L/opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64 /tmp/SVM-2495369923502253727/camel-quarkus-integration-test-bean-1.0.0-SNAPSHOT-runner.o /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libffi.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/libnet.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/libzip.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/libjava.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/libnio.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/libsunec.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/libsunec.a -lm -lpthread -ldl -lpthread -lz -lrt -lstdc++ -no-pie

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC) 
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/9/:/usr/libexec/gcc/x86_64-redhat-linux/9/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/9/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/9/:/usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/9/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/home/lburgazz/work/apache/dev/camel-quarkus/integration-tests/bean/target/camel-quarkus-integration-test-bean-1.0.0-SNAPSHOT-native-image-source-jar/camel-quarkus-integration-test-bean-1.0.0-SNAPSHOT-runner' '-z' 'noexecstack' '-L/tmp/SVM-2495369923502253727' '-L/opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib' '-L/opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64' '-no-pie' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/9/collect2 -plugin /usr/libexec/gcc/x86_64-redhat-linux/9/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-redhat-linux/9/lto-wrapper -plugin-opt=-fresolution=/tmp/ccZBj0cQ.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /home/lburgazz/work/apache/dev/camel-quarkus/integration-tests/bean/target/camel-quarkus-integration-test-bean-1.0.0-SNAPSHOT-native-image-source-jar/camel-quarkus-integration-test-bean-1.0.0-SNAPSHOT-runner -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/9/crtbegin.o -L/tmp/SVM-2495369923502253727 -L/opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib -L/opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/9 -L/usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/9/../../.. --gc-sections --dynamic-list /tmp/SVM-2495369923502253727/exported_symbols.list -x /tmp/SVM-2495369923502253727/camel-quarkus-integration-test-bean-1.0.0-SNAPSHOT-runner.o /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libffi.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/libnet.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/libzip.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/libjava.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/libnio.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/libsunec.a /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/libsunec.a -lm -lpthread -ldl -lpthread -lz -lrt -lstdc++ -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-redhat-linux/9/crtend.o /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/crtn.o
/usr/bin/ld: /opt/data/sfw/lang/java/graalvm-ce-java8-19.3.0/jre/lib/libjava.a(Proxy.o): in function `Java_java_lang_reflect_Proxy_defineClass0':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/java/lang/reflect/Proxy.c:97: undefined reference to `VerifyFixClassname'
/usr/bin/ld: /opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/java/lang/reflect/Proxy.c:97: undefined reference to `VerifyFixClassname'
collect2: error: ld returned 1 exit status
```

**Comment by lburgazzoli** [comment]
ok to test

**Comment by lburgazzoli** [comment]
@gsmet the pr is now building also in native mode with the exclusion of:

- bean (https://github.com/oracle/graal/issues/1971)
- salesforce (https://github.com/oracle/graal/issues/1975 which seems to be fixed on graalvm master)

Will merge tomorrow if ok to go ahead with two extension not supporting native compilation.

**Comment by lburgazzoli** [comment]
please do not merge

**Comment by gsmet** [comment]
Closing this one.

**Pull request closed without merging**
