### PR TITLE
Remove redundant Spring dependencies from JDBC extension

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Review by zhfeng — APPROVED** [review]

**Comment by aldettinger** [comment]
Is it "redundant Spring dependencies" ? so, redundant with what ?

Or maybe those dependencies have become useless ?

**Comment by jamesnetherton** [comment]
> Is it "redundant Spring dependencies" ? so, redundant with what ?
> 
> Or maybe those dependencies have become useless ?

Redundant `==` useless :slightly_smiling_face: 

https://issues.apache.org/jira/browse/CAMEL-16572

**Comment by zhfeng** [comment]
IIRC, I think we have splitted it to `camel-spring-jdbc` which supports the spring transaction.

**Review by aldettinger — APPROVED** [review]
== Yes true :)

Thanks for the context, it's clearer now.
This spring-less improvement is really good from camel-quarkus side :+1:

**Pull request merged**
