### PR TITLE
Debezium MongoDB Connector native support #1190

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/apache/camel-quarkus/issues/1190

[ ] An issue should be filed for the change unless this is a trivial change (fixing a typo or similar). One issue should ideally be fixed by not more than one commit and the other way round, each commit should fix just one issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful and properly spelled subject line and body. Copying the title of the associated issue is typically enough. Please include the issue number in the commit message prefixed by #.
[ ] The pull request description should explain what the pull request does, how, and why. If the info is available in the associated issue or some other external document, a link is enough.
[ ] Phrases like Fix #<issueNumber> or Fixes #<issueNumber> will auto-close the named issue upon merging the pull request. Using them is typically a good idea.
[ ] Please run mvn process-resources -Pformat (and amend the changes if necessary) before sending the pull request.
[ ] Contributor guide is your good friend: https://camel.apache.org/camel-quarkus/latest/contributor-guide.html

### CODE REVIEW

**Comment by JiriOndrusek** [comment]
Do not merge!
(Debezium connector version is 1.4.0.Beta1. In quarkus platform 1.11, there should be dbz connector 1.4.0.Final, which should be used in this PR)

**Comment by JiriOndrusek** [comment]
@ppalaga It seems that connector version 1.4.0-final was releases at the end of the last week - https://mvnrepository.com/artifact/io.debezium/debezium-connector-mongodb/1.4.0.Final

Do you think it is possible that it will make it into quarkus 1.11? (https://github.com/quarkusio/quarkus-platform/blob/master/pom.xml#L64-L65) - which will allow this extension to be merged?

**Comment by ppalaga** [comment]
> Do you think it is possible that it will make it into quarkus 1.11? (https://github.com/quarkusio/quarkus-platform/blob/master/pom.xml#L64-L65) - which will allow this extension to be merged?

IIRC, @gunnarmorling suggested that we take care for the platform which sounded a bit like doing their job, but we should definitely try because it is in our interest :) So could you please prepare a PR upgrading Debezium in the platform?

**Comment by JiriOndrusek** [comment]
I'll prepare it.

**Comment by gunnarmorling** [comment]
Funny timing, was just asking @gsmet about this earlier today. He wants to have Debezium 1.4.0.Final in any case, due to some ORM-related issue. I believe he wanted to take care of the update, but he surely won't mind you doing it :) Thanks!

**Comment by JiriOndrusek** [comment]
@ppalaga , @gunnarmorling , @gsmet PR is created https://github.com/quarkusio/quarkus-platform/pull/171

**Comment by ppalaga** [comment]
I rebased this PR and added a few minor fixes in https://github.com/apache/camel-quarkus/pull/2123

**Pull request closed without merging**
