### PR TITLE
Upgrade camel to 4.5.0

### PR DESCRIPTION
**Pull request by JiriOndrusek**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by JiriOndrusek** [comment]
There are 2 failures in examples:

- **observability** - will be fixed after merging this PR https://github.com/apache/camel-quarkus/issues/5851
- **kamelet-chucknorris** - the error is caused  by not resolving `camel-yaml-dsl`. , which is present in staging [repository](https://repository.apache.org/content/repositories/orgapachecamel-1689/org/apache/camel/camel-yaml-dsl/4.5.0/). (Locally the example works), therefore I would say, that it is not a real issue. WDYT? @jamesnetherton  
```
ArtifactResolutionException: The following artifacts could not be resolved: org.apache.camel:camel-yaml-dsl:jar:4.5.0 (present, but unavailable): org.apache.camel:camel-yaml-dsl:jar:4.5.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
```

**Comment by jamesnetherton** [comment]
> it is not a real issue

Yeah. I was thinking that it's probably just luck that most of the example projects compile anyway. Since they don't have the staging repo configured in their project pom.xml.

**Comment by jamesnetherton** [comment]
I regenerated the qdrant commit as it contained some unwanted stuff.

**Comment by aldettinger** [comment]
4.5.0 artifacts seems to be public accessible, let's try anoher ci run.

**Comment by jamesnetherton** [comment]
> 4.5.0 artifacts seems to be public accessible, let's try anoher ci run.

I think there's an issue with the Splunk container image. Something has changed to make the splunk-hec test start failing. It's also observed on the `main` branch.

**Comment by aldettinger** [comment]
> > 4.5.0 artifacts seems to be public accessible, let's try anoher ci run.
> 
> I think there's an issue with the Splunk container image. Something has changed to make the splunk-hec test start failing. It's also observed on the `main` branch.

And it's also observed on the 3.8.x, at least in pr #5933

**Comment by ppalaga** [comment]
Rebased and added the upgrade to cq-maven-plugin

**Pull request merged**
