### PR TITLE
Add GitHub Action to report test failures in the workflow summary

### PR DESCRIPTION
**Pull request by jamesnetherton**
Adds a custom action to report test failures into the workflow summary page.

I added a commit that will cause some failures so it can be tested. I'll drop it before merging.

### CODE REVIEW

**Comment by jamesnetherton** [comment]
Test failures are listed here:

https://github.com/apache/camel-quarkus/actions/runs/8997456627.

**Comment by jamesnetherton** [comment]
> Just wonder if it is possible to add such a comment in PR automatically?

Yeah, I did think about that. Not sure if we'd maybe run into permissions issues (needs checking)?

I also didn't want to force the PR comment requirement, since on the nightly workflows, there is no PR.

I can try to investigate it.

**Comment by zhfeng** [comment]
Yeah, I understand. What I need currently is just a comment with a link to the summary when there is a test failure. This could be much easier?

**Comment by jamesnetherton** [comment]
> This could be much easier?

Yes & no 🙂 

I could try to add something. I have a feeling that it wont work with PRs from forked repositories though. It'd need a bot user token.

**Comment by zhfeng** [comment]
Hmm, no, that's definely a problem. :(

**Comment by jamesnetherton** [comment]
How should I proceed?

Merge as-is and try to follow up later with improvements? Or rethink things entirely?

Even something as simple as a comment with a link is non-trivial to manage. They get stale, so need updating on future workflow runs. Or the tests pass and they become irrelevant so need minimising or deleting.

I deliberately kept the initial scope of this to be as simple as possible. It's two clicks from the PR to get to the summary. So not a massive overhead (IMO).

**Review by zhfeng — APPROVED** [review]

**Comment by zhfeng** [comment]
I'd say let's merge and keep to improve it. Thanks @jamesnetherton !

**Pull request merged**
