### PR TITLE
Find a proper place for registering SAXMessages native resource bundle

### PR DESCRIPTION
**Pull request by JiriOndrusek**
Issue: https://github.com/apache/camel-quarkus/issues/1796

[ ] An issue should be filed for the change unless this is a trivial change (fixing a typo or similar). One issue should ideally be fixed by not more than one commit and the other way round, each commit should fix just one issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful and properly spelled subject line and body. Copying the title of the associated issue is typically enough. Please include the issue number in the commit message prefixed by #.
[ ] The pull request description should explain what the pull request does, how, and why. If the info is available in the associated issue or some other external document, a link is enough.
[ ] Phrases like Fix #<issueNumber> or Fixes #<issueNumber> will auto-close the named issue upon merging the pull request. Using them is typically a good idea.
[ ] Please run mvn process-resources -Pformat (and amend the changes if necessary) before sending the pull request.
[ ] Contributor guide is your good friend: https://camel.apache.org/camel-quarkus/latest/contributor-guide.html

### CODE REVIEW

**Review by jamesnetherton — APPROVED** [review]

**Comment by ppalaga** [comment]
I think we should first discuss whether Quarkus JAXP extension would not be a better place for this. Apparently, Quarkus JAXP extension does not exist yet. It looks like they put the JAXP stuff into their JAXB extension. I think we should propose splitting their JAXB into JAXB and JAXP and then put the `SAXMessages` registration in the new Quarkus JAXP extension. WDYT, @jamesnetherton ?

**Comment by ppalaga** [comment]
> It looks like they put the JAXP stuff into their JAXB extension

Here: 

* https://github.com/quarkusio/quarkus/blob/master/extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java#L196-L199
* https://github.com/quarkusio/quarkus/blob/master/extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java#L205-L206
* https://github.com/quarkusio/quarkus/blob/master/extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java#L210-L214

**Comment by jamesnetherton** [comment]
> I think we should first discuss whether Quarkus JAXP extension would not be a better place for this. Apparently, Quarkus JAXP extension does not exist yet. It looks like they put the JAXP stuff into their JAXB extension. I think we should propose splitting their JAXB into JAXB and JAXP and then put the `SAXMessages` registration in the new Quarkus JAXP extension. WDYT, @jamesnetherton ?

Yes, that sounds like a better way. It'll be less stuff that we have to maintain on our side.

**Comment by ppalaga** [comment]
OK, let me file a Quarkus issue

**Comment by ppalaga** [comment]
Filed https://github.com/quarkusio/quarkus/issues/12129

**Comment by ppalaga** [comment]
Solved via quarkusio/quarkus#12144 , esp. https://github.com/quarkusio/quarkus/pull/12144/files#diff-d7d3c24be2a44a5a8077b76e7b3290c6R36

**Pull request closed without merging**
