### PR TITLE
⬆️ Upgrade Quarkus 2.6.0.Final

### PR DESCRIPTION
**Pull request by zbendhiba**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by zbendhiba** [comment]
I didn't check if versions were updated in the quarkus-bom. I'm upgrading the kotlin version and double-check all the versions we usually sync from the quarkus bom

**Review by aldettinger — APPROVED** [review]
Great. It should also open the path for #3366.

**Review by ppalaga — APPROVED** [review]
`mvn cq:sync-versions -N -e` does not show any upgrades anymore, so we are good

**Comment by zbendhiba** [comment]
> `mvn cq:sync-versions -N -e` does not show any upgrades anymore, so we are good

yes I need to use this !! thanks

**Pull request merged**
