### PR TITLE
CAMEL-18341 - Upgrade from Codehaus Groovy 3.0.12 to Apache Groovy 4.0.4

### PR DESCRIPTION
**Pull request by apupier**
might worth merging at same time than https://github.com/apache/camel/pull/8102

### CODE REVIEW

**Comment by apupier** [comment]
I do not understand why it complains about uncommited files.
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   poms/bom/src/main/generated/flattened-full-pom.xml
	modified:   poms/bom/src/main/generated/flattened-reduced-pom.xml
	modified:   poms/bom/src/main/generated/flattened-reduced-verbose-pom.xml
```

the mentioned files have a lot of modifications. i tried to run the build locally again and I do not have other changes

**Comment by jamesnetherton** [comment]
Attached a diff of the changes that I see when running the build.

Not sure what Maven version you are running, but try to run the build with the `mvnw` script if you have not already done so. That may help.

[diff.txt](https://github.com/apache/camel-quarkus/files/9257486/diff.txt)

**Comment by apupier** [comment]
ah when i see the diff, i think it is because we need to merge first https://github.com/apache/camel/pull/8102

**Comment by apupier** [comment]
outdated.
Note that Camel Core has migrated to Apache groovy 4 https://github.com/apache/camel/pull/9487

**Pull request closed without merging**
