### PR TITLE
Temporary workaround for #2109 antora/xref-validator after a componen…

### PR DESCRIPTION
**Pull request by ppalaga**
…t was removed from Camel

Let's unblock our CI

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by jamesnetherton — APPROVED** [review]
You got stung by the old no '-' characters allowed within XML comments issue.

**Comment by ppalaga** [comment]
> You got stung by the old no '-' characters allowed withing XML comments issue.

Yep, I just noticed and fixed that.

**Review by aldettinger — APPROVED** [review]
Indeed, disabling it will unblock CI. For the record, I've seen the antora xref working locally but failing on CI.

**Comment by jamesnetherton** [comment]
> I've seen the antora xref working locally but failing on CI.

Clear out `~/.cache/antora` and it'll probably fail.

**Comment by ppalaga** [comment]
initial-mvn-install passed, which is enough for this change so let's merge

**Pull request merged**
