### PR TITLE
langchain4j: fix link to camel core parameter binding usage

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Comment by orpiske** [comment]
To fix the website build -> https://ci-builds.apache.org/job/Camel/job/Camel.website/job/main/1738/console

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
Please can you update this also:

https://github.com/apache/camel-quarkus/blob/main/docs/modules/ROOT/pages/reference/extensions/langchain4j.adoc

Usually it'd be done automatically by rebuilding the extension module. But the plugin that does it is currently disabled.

**Comment by orpiske** [comment]
> Please can you update this also:
> 
> https://github.com/apache/camel-quarkus/blob/main/docs/modules/ROOT/pages/reference/extensions/langchain4j.adoc
> 
> Usually it'd be done automatically by rebuilding the extension module. But the plugin that does it is currently disabled.

Sure thing. Just did that.

**Review by jamesnetherton — APPROVED** [review]

**Comment by aldettinger** [comment]
Many thanks for finding this @orpiske :clap:

**Pull request merged**
