### PR TITLE
[WIP - Draft]✨ Promote Couchbase to native mode

### LINKED ISSUE #1188: Couchbase native support
Related: 

* https://github.com/quarkusio/quarkus/issues/6228 
* https://github.com/quarkusio/quarkus/issues/6199

### PR DESCRIPTION
**Pull request by zbendhiba**
Fixes #1188

Testing with CI -- Do not merge please

### CODE REVIEW

**Comment by jamesnetherton** [comment]
Are those couchbase config properties mandatory? If so, it'd be a blocker to using the extension in CQ IMO.

**Comment by zbendhiba** [comment]
> Are those couchbase config properties mandatory? If so, it'd be a blocker to using the extension in CQ IMO.

yes they are. I'd open an issue then

**Comment by zbendhiba** [comment]
> > Are those couchbase config properties mandatory? If so, it'd be a blocker to using the extension in CQ IMO.
> 
> yes they are. I'd open an issue then

@jamesnetherton it's a more general issue, I guess. It's mandatory just for the fact that the extension is present in the pom.xml. https://github.com/couchbaselabs/quarkus-couchbase/issues/5
It's in alpha stage, so hopefully this would be fixed. The idea of my work is to give it a try and give feedback

**Comment by zbendhiba** [comment]
There is a failure somewhere, but the Couchbase tests are fine. First time, we do have some tests working on JVM mode. And they work also on native mode. 
We just need to look for bug fixes and improvements, to be able to use it in the future.
I can close the Draft PR

**Pull request closed without merging**
