### PR TITLE
Upgrade Quarkus to 2.2.0.CR1

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
Not sure why the `xchange` test is failing. It's the same failure I noticed on the nightly `camel-main` build. I cannot replicate it locally.

**Review by aldettinger — APPROVED** [review]
Can't replicate it too on main before this PR. Maybe it's just transient.
I've noticed [the fix for xchange](https://github.com/apache/camel-quarkus/commit/e7b01ea7e1a2c54caed52eb0499fc0ddde10ad08) was pushed to main only, but it doesn't seem to explain the situation here.

**Comment by jamesnetherton** [comment]
> I've noticed [the fix for xchange](https://github.com/apache/camel-quarkus/commit/e7b01ea7e1a2c54caed52eb0499fc0ddde10ad08) was pushed to main only, but it doesn't seem to explain the situation here.

I did replicate it locally for a brief moment https://github.com/apache/camel-quarkus/issues/3016.

The resource bundle fix was rebased automatically onto `camel-main` (where this PR originates from), so that shouldn't be a problem.

**Comment by jamesnetherton** [comment]
Disabled the `xchange` tests for now so that we can move this PR forward.

**Pull request merged**
