### PR TITLE
CoreTest.testCamelContextAwareRegistryBeansInitialized failing after …

### LINKED ISSUE #3002: `CoreTest.testCamelContextAwareRegistryBeansInitialized` failing after RouteBuilder started implementing CamelContextAware
Not sure what's going on with this. In the failure case, a bunch of `RouteBuilder` impls have been found via `registry.findByType(CamelContextAware.class)` and they all have a null `CamelContext`. On success they never show up in the registry lookup at all.

I can't replicate this locally. Maybe its related to the order of test execution.

```
2021-08-10T01:10:42.5347701Z 2021-08-10 01:10:42,525 WARN  [org.apa.cam.qua.cor.CoreResource] (executor-thread-1) Found a CamelContextAware bean of type org.apache.camel.quarkus.core.languages.it.CustomDataFormatRoutes with null CamelContext
2021-08-10T01:10:42.5352909Z 2021-08-10 01:10:42,525 WARN  [org.apa.cam.qua.cor.CoreResource] (executor-thread-1) Found a CamelContextAware bean of type org.apache.camel.quarkus.component.bean.RouteBuilderWithProducer with null CamelContext
2021-08-10T01:10:42.5357507Z 2021-08-10 01:10:42,525 WARN  [org.apa.cam.qua.cor.CoreResource] (executor-thread-1) Found a CamelContextAware bean of type org.apache.camel.quarkus.core.languages.it.RefLanguageRoutes with null CamelContext
2021-08-10T01:10:42.5361434Z 2021-08-10 01:10:42,525 WARN  [org.apa.cam.qua.cor.CoreResource] (executor-thread-1) Found a CamelContextAware bean of type org.apache.camel.quarkus.eip.it.EipRoutes with null CamelContext
2021-08-10T01:10:42.5365142Z 2021-08-10 01:10:42,525 WARN  [org.apa.cam.qua.cor.CoreResource] (executor-thread-1) Found a CamelContextAware bean of type org.apache.camel.quarkus.component.bean.eip.EipRoutes with null CamelContext
```

### PR DESCRIPTION
**Pull request by ppalaga**
…RouteBuilder started implementing CamelContextAware 

Fix #3002

@jamesnetherton Sending this against main

### CODE REVIEW

**Review by jamesnetherton — COMMENTED** [review]
I guess this is probably ok.

It's not clear to me whether we're just masking an actual issue here. If I search for `CamelContextAware` beans, then I'd expect the `CamelContext` to not be `null`.

**Comment by ppalaga** [comment]
> It's not clear to me whether we're just masking an actual issue here. If I search for CamelContextAware beans, then I'd expect the CamelContext to not be null.

Yeah, when thinking of it again, I am getting the same impression. On one hand user beans are their responsibility but OTOH the same holds for our RouteBuilders. We should better set `@ApplicationScoped` on them so that ppl. do not copy it from us. And once we do it, we can actually get back to querying the whole registry. Let me do it like that.

**Comment by ppalaga** [comment]
620f4ad: 
* set `@ApplicationScoped` on our RouteBuilders that have bean producer method
* get back to querying the whole registry.

**Review by jamesnetherton — APPROVED** [review]

**Comment by ppalaga** [comment]
The CI failure seems to be unrelated. Let's merge

**Pull request merged**
