### PR TITLE
fixes #6608 - deprecated groovy-dsl as is deprecated in Camel

### LINKED ISSUE #6608: Groovy-dsl extension should be deprecated
### Describe the feature here

Groovy-dsl component is being removed from Camel 4.9.0 (see [CAMEL-21205](https://issues.apache.org/jira/browse/CAMEL-21205)

The groovy-dsl extension should be marked as deprecated.

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/apache/camel-quarkus/issues/6608

Deprecated `groovy-dsl`

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
The extension metadata is generated. You'll need to add this to the `runtime/pom.xml` properties.

```xml
<quarkus.metadata.status>deprecated</quarkus.metadata.status>
```

**Comment by JiriOndrusek** [comment]
> The extension metadata is generated. You'll need to add this to the `runtime/pom.xml` properties.
> 
> ```
> <quarkus.metadata.status>deprecated</quarkus.metadata.status>
> ```
> 
> Then run `mvn -N cq:update-quarkus-metadata` from the project root.

I added deprecated status into maven toling, but obviosly I have to add it also to `org.l2x6.cq.common.ExtensionStatus`

**Comment by JiriOndrusek** [comment]
I had to add a deprecated status here as well https://github.com/l2x6/cq-maven-plugin/pull/524
@jamesnetherton WDYT?

**Comment by JiriOndrusek** [comment]
New fix uses `<quarkus.metadata.deprecated>true</quarkus.metadata.deprecated>` I think it can be merged now

**Pull request merged**
