### PR TITLE
CamelQuarkusTestSupport: Alow to use AdiceWith with another route #4104

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/apache/camel-quarkus/issues/4104

New helper method `startRouteDefinitions` was added into `CamelQuarkusTestSupport` to enable this usecase. Use of the method is described in the javadoc.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by llowinge** [comment]
@JiriOndrusek I would ideally copy-paste whole javadoc comment from the `CamelTestSupport` with only needed changes for CQ.

**Comment by llowinge** [comment]
Great, thanks @JiriOndrusek !

**Review by ppalaga — APPROVED** [review]

**Comment by ppalaga** [comment]
Isn't there anything we need to add to [CamelQuarkusTestSupport documentation page](https://camel.apache.org/camel-quarkus/2.12.x/user-guide/testing.html#_cameltestsupport_style_of_testing)?

**Comment by JiriOndrusek** [comment]
It would make sense to add something like `     * If there are some unchanged routes, when using advice with, it's important to execute method CamelQuarkusTestSupport#startRouteDefinitions manually from the unit test after you are done doing all the advice with.`

(into the list of limitations). It could help users,

**Comment by JiriOndrusek** [comment]
Doc page is modified,

**Review by zbendhiba — APPROVED** [review]

**Comment by JiriOndrusek** [comment]
The build failure is caused by this change. I'm investigating it.

**Comment by JiriOndrusek** [comment]
fixed

**Review by jamesnetherton — APPROVED** [review]

**Pull request merged**
