### PR TITLE
Fix #635 Dependency parity check

### LINKED ISSUE #635: Dependency parity check
Not having 1:1 match between -deployment deps in the deployment module and runtime deps in the runtime module usually leads to subtle issues, so we should consider enforcing the parity somehow.

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
looks like there is a dependency issue

**Comment by ppalaga** [comment]
9ba95df rebased to trigger a new build to see whether that's just a transfer problem

**Comment by lburgazzoli** [comment]
ok to test

**Comment by lburgazzoli** [comment]
@ppalaga yet another conflict

**Comment by ppalaga** [comment]
f25de47 rebased

**Comment by lburgazzoli** [comment]
@ppalaga still failing

**Comment by ppalaga** [comment]
@gsmet isn't this `java.util.NoSuchElementException: Property user.country not found` https://github.com/apache/camel-quarkus/pull/638/checks?check_run_id=401147339#step:4:2706 caused by or related to the mysterious Quarkus issue you refer to in https://github.com/apache/camel-quarkus/commit/de4fffced064c9d9fd08379f7bae95403d707fbc ?

It is passing for me locally.

**Comment by ppalaga** [comment]
227e642 rebased in hope for the strange locale error to disappear

**Comment by gsmet** [comment]
@ppalaga it has been fixed here: https://github.com/quarkusio/quarkus/pull/6681 .

**Comment by gsmet** [comment]
So it should be fixed if you use `1.2.0.Final`.

**Pull request merged**
