### PR TITLE
Added an AWS Kinesis extension

### LINKED ISSUE #624: Add Camel-AWS-Kinesis extension

### PR DESCRIPTION
**Pull request by oscerd**
Fixes #624

### CODE REVIEW

**Comment by oscerd** [comment]
ok to test

**Comment by gsmet** [comment]
Could you please hold on on adding more extensions until the next release (that should start at the end of next week)?

We struggle to get the current extensions working with GraalVM 19.3.1 so adding more won't help.

Thanks!

/cc @lburgazzoli

**Comment by lburgazzoli** [comment]
@oscerd do you mind rebase so we can test against quarkus 1.2.0 RC ?

**Comment by oscerd** [comment]
Rebased.

**Comment by oscerd** [comment]
ok to test

**Comment by oscerd** [comment]
Looks good.

**Pull request merged**
