### PR TITLE
Fix #483 Flatten the integration-tests hierarchy and remove camel-qua…

### LINKED ISSUE #483: Flatten the integration-tests hierarchy and remove camel-quarkus-test-list.xml from git
Proposed by @lburgazzoli in https://github.com/apache/camel-quarkus/pull/482

> We may think to move support test extension in a dedicated support folder so main and core and future it tests are just like other tests and we only need to skip indexing the support folder

### PR DESCRIPTION
**Pull request by ppalaga**
…rkus-test-list.xml from git

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@ppalaga needs rebase

**Comment by ppalaga** [comment]
a7f573c rebased

**Comment by lburgazzoli** [comment]
ok to test

**Comment by ppalaga** [comment]
@lburgazzoli any theory why the CamelKafkaTest failed?

**Comment by lburgazzoli** [comment]
maybe a timing issue, like if the get exceed the duration, then iterating the response fails

**Comment by ppalaga** [comment]
Would that require a re-running the job?

**Comment by lburgazzoli** [comment]
ok to test

**Pull request merged**
