### PR TITLE
Add missing security configuration to azure test #1269

### PR DESCRIPTION
**Pull request by galderz**
Fix for https://github.com/apache/camel-quarkus/issues/1269.

* Security provider needs to enabled and security extension needs adding.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@jamesnetherton do we need to add those bits to the ms extensions themselves ?

**Comment by jamesnetherton** [comment]
@lburgazzoli Yeah I was just about to suggest that. It's probably better to do something like this in `AzureProcessor`:

```
    @BuildStep
    ExtensionSslNativeSupportBuildItem activateSslNativeSupport() {
        return new ExtensionSslNativeSupportBuildItem(FEATURE);
    }
```

Rather than adding the properties file and the additional dependency to the tests.

**Comment by galderz** [comment]
@lburgazzoli @jamesnetherton Sounds good. I'll rework the PR.

**Comment by galderz** [comment]
Tried it and it works. Created a new PR for the new fix https://github.com/apache/camel-quarkus/pull/1294.

**Pull request closed without merging**
