### PR TITLE
Do not merge ! Disabling tests except aws-ddb

### PR DESCRIPTION
**Pull request by JiriOndrusek**
do not merge, this is for testing purposes only. (to see result of build for aws-ddb)

Investigation of https://github.com/apache/camel-quarkus/issues/2860

### CODE REVIEW

**Comment by lburgazzoli** [comment]
wonder if when a pr should not be merged, best would be to open a draft pr (afaik co triggers as well)

**Comment by JiriOndrusek** [comment]
@lburgazzoli  I noticed, that with draft PRs, the build is not run completely (or I could be wrong about it)

**Comment by lburgazzoli** [comment]
> @lburgazzoli I noticed, that with draft PRs, the build is not run completely (or I could be wrong about it)
> 

Oh, didn't know, I guess we should investigate if there are any difference between the type of PRs.
Btw, I don't have any objection on warning people with the PR description :) but a draft pr would be much more robust

**Comment by JiriOndrusek** [comment]
My bad, it seems that CI starts with draft PRs, I'm keeping this PR as draft, because it is aligned with its purpose.

**Comment by JiriOndrusek** [comment]
I saw the test results, closing PR.

**Pull request closed without merging**
