### PR TITLE
fix  [JDK17]kudu:integration test failed in native mode #3340

### PR DESCRIPTION
**Pull request by ffang**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by aldettinger — APPROVED** [review]

**Review by zbendhiba — APPROVED** [review]

**Comment by zbendhiba** [comment]
@ffang can this be added in the same profile as jdk16-workarounds ?
there is a similar line here : https://github.com/apache/camel-quarkus/blob/cb9c92008820642be374fa136f9b53a4677777d6/integration-tests/kudu/pom.xml#L113
Maybe it will be good to refactor the config. WDYT ?

**Review by ppalaga — CHANGES_REQUESTED** [review]
A custom argline is not an end user-friendly solution. Is there no Quarkus BuildItem for this?
If we keep relying on argline, then we need to document this on the given extension page,

**Comment by jamesnetherton** [comment]
> A custom argline is not an end user-friendly solution.

I think in this case, it's acceptable because we unfortunately need this hack in the itests:

https://github.com/apache/camel-quarkus/blob/main/integration-tests/kudu/src/main/java/org/apache/camel/quarkus/component/kudu/it/KuduInfrastructureTestHelper.java#L64

It's not required for users to do this in their apps AFAIK.

**Comment by ffang** [comment]
> @ffang can this be added in the same profile as jdk16-workarounds ? there is a similar line here :
> 
> https://github.com/apache/camel-quarkus/blob/cb9c92008820642be374fa136f9b53a4677777d6/integration-tests/kudu/pom.xml#L113
> 
> Maybe it will be good to refactor the config. WDYT ?

**Comment by ffang** [comment]
> > A custom argline is not an end user-friendly solution.
> 
> I think in this case, it's acceptable because we unfortunately need this hack in the itests:
> 
> https://github.com/apache/camel-quarkus/blob/main/integration-tests/kudu/src/main/java/org/apache/camel/quarkus/component/kudu/it/KuduInfrastructureTestHelper.java#L64
> 
> It's not required for users to do this in their apps AFAIK.

Yes, this issue indeed from KuduInfrastructureTestHelper itself, which tries to access no-public field from java.net.InetAddress with reflection. This won't happen in users apps.

**Comment by ppalaga** [comment]
Thanks for the explanation @jamesnetherton and @ffang . Could we please have a big fat command near the `argLine` saying that this is due to the nasty things we do in `KuduInfrastructureTestHelper`?

**Comment by ppalaga** [comment]
About where to put `<argLine>--add-opens java.base/java.net=ALL-UNNAMED</argLine>` given that java 11 is our baseline, where this should work and given that we need it for both plugins in all profiles, can't we just add 

```
<properties>
  <argLine>--add-opens java.base/java.net=ALL-UNNAMED</argLine>
</properties>
```

in the top profile-less context (and remove the old `jdk16-workarounds` profile altogether)?

**Comment by ffang** [comment]
> About where to put `<argLine>--add-opens java.base/java.net=ALL-UNNAMED</argLine>` given that java 11 is our baseline, where this should work and given that we need it for both plugins in all profiles, can't we just add
> 
> ```
> <properties>
>   
>   <argLine>--add-opens java.base/java.net=ALL-UNNAMED</argLine>
> </properties>
> ```
> 
> in the top profile-less context (and remove the old `jdk16-workarounds` profile altogether)?

Hi @ppalaga ,

I may miss your point, but if we add
```
</dependencies>
+    <build>
+        <plugins>
+            <plugin>
+                <groupId>org.apache.maven.plugins</groupId>
+                <artifactId>maven-surefire-plugin</artifactId>
+                <configuration>
+                    <!-- This is to allow the "deep reflection" we do in KuduInfrastructureTestHelper -->
+                    <argLine>--add-opens java.base/java.net=ALL-UNNAMED</argLine>
+                </configuration>
+            </plugin>
+        </plugins>
+    </build>

```
in the pom.xml out of profiles, this can't affect the maven-failsafe-plugin configuration in native profile. The maven-failsafe-plugin configuration in native profile can't pick up this argLine and will fail with JDK17 in native mode. We need to add this argLine in native profile anyway. 

Freeman

**Comment by ppalaga** [comment]
I spoke about `<argLine>` in `<properties>`, not plugin config.  We should be able to hit both plugins that way.

**Comment by ffang** [comment]
> I spoke about `<argLine>` in `<properties>`, not plugin config. We should be able to hit both plugins that way.

That's right, I will revise the PR soon.

Thanks!
Freeman

**Comment by ffang** [comment]
revised and squashed commits here
https://github.com/apache/camel-quarkus/pull/3341/commits/43d45606d89f07f6f44e5d998903cb8145e75263

**Review by ppalaga — APPROVED** [review]
Thanks @ffang!

**Pull request merged**
