### PR TITLE
Added description about uber-jar creation

### PR DESCRIPTION
**Pull request by geertschuring**

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
I guess there are some troubles with the commits

**Comment by geertschuring** [comment]
> I guess there are some troubles with the commits

Yeah that's weird. I only changed 1 file: first-steps.adoc

**Comment by aldettinger** [comment]
Maybe it need to be rebased on the main branch.

Also, I wonder whether it would be interesting to precise in the doc that uber-jar may start a [bit slower](https://developers.redhat.com/blog/2021/04/08/build-even-faster-quarkus-applications-with-fast-jar#step_3__compare_the_application_startup_times) than the default fast-jar ?

**Comment by aldettinger** [comment]
@geertschuring PRs are more than welcome :) Do you still have time to work on this ?

**Comment by aldettinger** [comment]
@geertschuring Let's close this PR for now. Feel free and very much welcome to re-open if needed/time. Many thanks for taking interest in Camel Quarkus by the way. Feedbacks and contributions are much much welcome :)

**Pull request closed without merging**
