### PR TITLE
Aws SQS: Remove unnecessary headers from the test because of CAMEL-18…

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/apache/camel-quarkus/issues/3803

(requires https://github.com/apache/camel/pull/7633, therefore against camel-main)

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by aldettinger** [comment]
I experimented locally to understand the build issue. And it looks, running `mvn cq:sync-versions -N` is updating the pom file:
```
-        <msal4j.version>1.11.3</msal4j.version><!-- @sync com.azure:azure-identity:${azure-identity-vers
+        <msal4j.version>1.12.0</msal4j.version><!-- @sync com.azure:azure-identity:${azure-identity-vers
```

Probably, the version has been updated and pom file need to be committed.

**Comment by aldettinger** [comment]
I experimented locally to understand the build issue. And it looks, running `mvn cq:sync-versions -N` is updating the pom file:
```
-        <msal4j.version>1.11.3</msal4j.version><!-- @sync com.azure:azure-identity:${azure-identity-vers
+        <msal4j.version>1.12.0</msal4j.version><!-- @sync com.azure:azure-identity:${azure-identity-vers
```

Probably, the version has been updated and pom file need to be committed.

**Comment by JiriOndrusek** [comment]
@aldettinger thanks for the solution. I updated the PR.

**Review by aldettinger — APPROVED** [review]

**Comment by aldettinger** [comment]
The build failed, there is indeed other files to committed:
```
	modified:   poms/bom/src/main/generated/flattened-full-pom.xml
	modified:   poms/bom/src/main/generated/flattened-reduced-pom.xml
	modified:   poms/bom/src/main/generated/flattened-reduced-verbose-pom.xml
```

**Comment by jamesnetherton** [comment]
Merged manually here https://github.com/apache/camel-quarkus/commit/7e4f5b12586db9e67e3e7aeb9dd7c26f787d0899.

**Pull request closed without merging**
