### PR TITLE
Fix maven connection time out

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Review by zbendhiba — APPROVED** [review]

**Review by jamesnetherton — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Review by aldettinger — APPROVED** [review]

**Comment by zhfeng** [comment]
@ppalaga so it needs to change these configurations in `maven.config`, or it will be override?

**Comment by jamesnetherton** [comment]
> @ppalaga so it needs to change these configurations in `maven.config`, or it will be override?

I think Peter was hinting at removing `maven.config` (or just removing the file contents). I don't think we want to rely on it for the CI build because we sometimes build other projects like Quarkus & Camel.

**Comment by zhfeng** [comment]
OK, I see and +1 to remove it.

**Comment by zhfeng** [comment]
The CI looks good and I will merge it.

**Pull request merged**
