### PR TITLE
Fix #4279 to import PlatformTransactionManager completely in camel-qu…

### LINKED ISSUE #4279: JMS consumer in a XA router can not work with JPA
I'm trying to incorporate JMS consumer in a XA router such lik:
```
from("xajms:outbound")
                .transacted()
                .log("Message out: ${body}")
                .to("bean:auditLog?method=createAuditLog(${body}-ok)")
                .to("jpa:org.acme.AuditLog");
``` 

And a XA JMS Component could be 

```
 @Produces
    @Named("xajms")
    public JmsComponent xaJms() {
        JmsComponent component = new JmsComponent();
        component.setConnectionFactory(connectionFactory);
        component.setTransacted(false);

        JtaTransactionManager jtaTransactionManager = new JtaTransactionManager(userTransaction, transactionManager);
        jtaTransactionManager.setTransactionSynchronizationRegistry(transactionSynchronizationRegistry);
        component.setTransactionManager(jtaTransactionManager);
        return component;
    }
```
But it can not receive any message from the queue and the warn messaging is
```
2022-11-17 10:21:31,014 WARN  [org.apa.cam.com.jms.DefaultJmsMessageListenerContainer] (Camel (camel-1) thread #1 - JmsConsumer[outbound]) Setup of JMS message listener invoker failed for destination 'outbound' - trying to recover. Cause: 'org.springframework.transaction.TransactionStatus org.springframework.transaction.PlatformTransactionManager.getTransaction(org.springframework.transaction.TransactionDefinition)': java.lang.NoSuchMethodError: 'org.springframework.transaction.TransactionStatus org.springframework.transaction.PlatformTransactionManager.getTransaction(org.springframework.transaction.TransactionDefinition)'
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:243)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

I think the root cause is that we introduced [PlatformTransactionManager](https://github.com/apache/camel-quarkus/blob/main/extensions/jpa/runtime/src/main/java/org/springframework/transaction/PlatformTransactionManager.java) in `camel-quarkus-jpa` which is just to make the graal native building happy to do the static analyst.  So it needs to import `PlatformTransactionManager` interface completely since the `camel-jms` has to depend on `spring-tx`.

It might be an other better way to do such things with native building. @jamesnetherton @ppalaga WDYT?

### PR DESCRIPTION
**Pull request by zhfeng**
…arkus-jpa

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
We should probably open an issue to rethink how we're handling the removal of Spring from the JPA extension.

With the current way, I wonder if we're creating a potential maintenance headache? E.g if the Spring APIs change in the future, do we need to update these placeholder classes and interfaces?

**Comment by zhfeng** [comment]
Yeah, it is exactly what I'm worrying about. In case of APIs changes, I think we need to update these classes and interfaces otherwise `camel-jms` or othere components which depend on `spring-tx` will be failing when combining with `camel-jpa`.

**Comment by jamesnetherton** [comment]
Wondering whether an alternative 'fix' might be to revert the Spring removal from the JPA extension? That would give us some more time to think through a better solution for the future. WDYT?

**Comment by zhfeng** [comment]
It suppressed by https://github.com/apache/camel-quarkus/pull/4286

**Comment by zhfeng** [comment]
@jamesnetherton I've reopened https://github.com/apache/camel-quarkus/issues/4084 to think about removing spring from JPA.

**Pull request closed without merging**
