### PR TITLE
Use banned dependency rules published by Quarkus (after filtering the…

### LINKED ISSUE #4193: Ban `com.github.stephenc.jcip:jcip-annotations`
Follow up on https://github.com/apache/camel-quarkus/pull/4183#issuecomment-1282400106.

### PR DESCRIPTION
**Pull request by ppalaga**
…m), move ours to a separate XML file to be able to use them by both enforcer and flattener plugins

Fix #4193

### CODE REVIEW

**Comment by ppalaga** [comment]
Ups, the Sonatype OSS repo seems to be slow today. cq-plugin 3.3.0 is not in the Central yet. Let's wait.

**Review by zbendhiba — APPROVED** [review]

**Review by zhfeng — APPROVED** [review]

**Review by zhfeng — CHANGES_REQUESTED** [review]
Hi @ppalaga , `maven-enforcer-plugin` [3.2.1](https://github.com/apache/maven-enforcer/releases/tag/enforcer-3.2.1) is just released. Then it should be good to try it out.

**Comment by ppalaga** [comment]
> Hi @ppalaga , maven-enforcer-plugin [3.2.1](https://github.com/apache/maven-enforcer/releases/tag/enforcer-3.2.1) is just released. Then it should be good to try it out.

I tried it and it fails :D I did not have any time to look closer why.

**Comment by ppalaga** [comment]
This was done as fe585f2255d1a354a4c2568c17aba1293ccc130a via another PR

**Pull request closed without merging**
