### PR TITLE
Fix #217 Support rest dsl in platform-http component

### LINKED ISSUE #217: [platform http] support for rest dsl

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
d2ef7abd750e25d499a3cf4923a70c221899da0a rebased to restart the stuck CI.

**Comment by davsclaus** [comment]
Okay camel-paho on master branch has changed so update the test

**Comment by davsclaus** [comment]
However its weird as retained is the same option as before.

**Comment by davsclaus** [comment]
Okay it must have used a dodgy SNAPSHOT - the CI test works fine now

**Pull request merged**
