### PR TITLE
Update to Apache Camel 3.0.1

### LINKED ISSUE #628: Upgrade to Apache Camel 3.0.1

### LINKED ISSUE #631: camel-pdf: build failure in jvm mode with Apache Camel 3.0.1
From https://github.com/apache/camel-quarkus/pull/630#issuecomment-575749725

```
Caused by: java.io.IOException: COSStream has been closed and cannot be read. Perhaps its enclosing PDDocument has been closed?
	at org.apache.pdfbox.cos.COSStream.checkClosed(COSStream.java:83)
	at org.apache.pdfbox.cos.COSStream.createInputStream(COSStream.java:168)
	at org.apache.pdfbox.cos.COSStream.createInputStream(COSStream.java:163)
	at org.apache.pdfbox.pdmodel.PDPage.getContents(PDPage.java:157)
	at org.apache.pdfbox.pdfparser.PDFStreamParser.<init>(PDFStreamParser.java:92)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:496)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:480)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:153)
	at org.apache.pdfbox.text.LegacyPDFStreamEngine.processPage(LegacyPDFStreamEngine.java:139)
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:391)
	at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:319)
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:266)
	at org.apache.pdfbox.text.PDFTextStripper.getText(PDFTextStripper.java:227)
	at org.apache.camel.component.pdf.PdfProducer.doExtractText(PdfProducer.java:104)
	at org.apache.camel.component.pdf.PdfProducer.process(PdfProducer.java:66)
```

### PR DESCRIPTION
**Pull request by lburgazzoli**
Fixes #628
Fixes #631

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@aldettinger looks like camel-pdf fails in JVM with Apache Camel 3.0.1 with the following error:

```
Caused by: java.io.IOException: COSStream has been closed and cannot be read. Perhaps its enclosing PDDocument has been closed?
	at org.apache.pdfbox.cos.COSStream.checkClosed(COSStream.java:83)
	at org.apache.pdfbox.cos.COSStream.createInputStream(COSStream.java:168)
	at org.apache.pdfbox.cos.COSStream.createInputStream(COSStream.java:163)
	at org.apache.pdfbox.pdmodel.PDPage.getContents(PDPage.java:157)
	at org.apache.pdfbox.pdfparser.PDFStreamParser.<init>(PDFStreamParser.java:92)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:496)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:480)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:153)
	at org.apache.pdfbox.text.LegacyPDFStreamEngine.processPage(LegacyPDFStreamEngine.java:139)
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:391)
	at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:319)
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:266)
	at org.apache.pdfbox.text.PDFTextStripper.getText(PDFTextStripper.java:227)
	at org.apache.camel.component.pdf.PdfProducer.doExtractText(PdfProducer.java:104)
	at org.apache.camel.component.pdf.PdfProducer.process(PdfProducer.java:66)
```

See CI's for full logs

**Comment by lburgazzoli** [comment]
ok to test

**Comment by davsclaus** [comment]
It was reported to Camel that the the pdf should be closed after creating it, there is some CAMEL ticket about it

**Comment by lburgazzoli** [comment]
ok so the test has to be reworked

**Comment by lburgazzoli** [comment]
ok to test

**Comment by lburgazzoli** [comment]
ok to test

**Comment by oscerd** [comment]
The Sonatype CDN problem should be resolved now, so we can remove the apache repository. Maybe in a subsequent PR

**Comment by lburgazzoli** [comment]
> The Sonatype CDN problem should be resolved now, so we can remove the apache repository. Maybe in a subsequent PR

Still having the same issue:

```
$ wget https://repo.maven.apache.org/maven2/org/apache/camel/camel-util-json/3.0.1/camel-util-json-3.0.1.pom
--2020-01-18 13:19:04--  https://repo.maven.apache.org/maven2/org/apache/camel/camel-util-json/3.0.1/camel-util-json-3.0.1.pom
Resolving repo.maven.apache.org (repo.maven.apache.org)... 151.101.240.215
Connecting to repo.maven.apache.org (repo.maven.apache.org)|151.101.240.215|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-01-18 13:19:04 ERROR 404: Not Found.
```

**Pull request merged**
