### PR TITLE
docs: Fix some quarkus.camel property names

### PR DESCRIPTION
**Pull request by christophd**

### CODE REVIEW

**Comment by jamesnetherton** [comment]
Does `quarkus.camel.service.discovery.exclude-patterns` not work?

The config property doc sections are auto generated by some Quarkus tooling. So I think this change would get overwritten when the build runs.

**Comment by ppalaga** [comment]
I think the proposal of @christophd is indeed correct. There is a separate `.service.` node in the config: https://github.com/apache/camel-quarkus/blob/main/extensions-core/core/runtime/src/main/java/org/apache/camel/quarkus/core/CamelConfig.java#L128-L140

... and @jamesnetherton is also right that the docs is generated. So we need to fix the generator code.

**Comment by ppalaga** [comment]
I am looking into it.

The first step is done by annotation processor `io.quarkus:quarkus-extension-processor` plugged to the compiler plugin. 
The result is stored in `target/asciidoc/generated/config/all-configuration-roots-generated-doc/org.apache.camel.quarkus.core.CamelConfig` of the source tree root dir. The prop names seem to be correct there: 

```
...
 {
      "configDocKey":{
         "type":"string",
         "key":"quarkus.camel.service.discovery.exclude-patterns",
...
```

Those files are then picked by `update-extension-doc-page` of `camel-quarkus-maven-plugin`. Let my try to debug it.

**Comment by christophd** [comment]
sorry for the confusion. I was getting confused by `quarkus.camel.routes-discovery` and another property that was provided to me with another `-`. Reviewing the config structure I think `quarkus.camel.service.discovery.*` is correct as you guys have suggested.

I think we can safely close this one then

**Pull request closed without merging**
