### PR TITLE
Fix #838 TimeZone-less DTSTART and DTEND not changed to GMT

### LINKED ISSUE #838: [Quarkus 1.6][iCal] TimeZone-less DTSTART and DTEND changed to GMT in native mode
Probably caused by https://github.com/quarkusio/quarkus/issues/5016 

As a result, only zoned DTSTART and DTEND work properly.

### PR DESCRIPTION
**Pull request by ppalaga**
in native mode with GraalVM 20.1.0+

Waiting for Quarkus 1.6 whose docker image brings GraalVM 20.1.0

### CODE REVIEW

**Comment by ppalaga** [comment]
1ffce1c rebased. Should be good to merge now that we are on Quarkus 1.6.0.CR1

**Comment by davsclaus** [comment]
Should we get this merged before we do a new release?

**Comment by ppalaga** [comment]
I need to figure out why is it failing.

**Comment by ppalaga** [comment]
OK, I can reproduce the failure locally by setting the system TZ to Etc/UTC via `sudo timedatectl set-timezone Etc/UTC` or any other TZ with an offset different from Europe/Paris used in the test. Let me figure out how to solve it.

**Comment by ppalaga** [comment]
Java 8 failure is unrelated.

**Pull request merged**
