### PR TITLE
Remove not needed anymore BeansWeakCache substitution. Closes #3226

### LINKED ISSUE #3226: GraalVM 21.2.0 + Java 16 - Native build fails
I can see following error (running eg. any integration test in Native mode) using GraalVM 21.2.0 + JDK 16 (with JDK 11 it works great).

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM 21.2.0 Java 16 CE (Java Version 16.0.2+7-jvmci-21.2-b08)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /Users/llowinge/.sdkman/candidates/java/21.2.0.r16-grl/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=CZ -J-Dfile.encoding=UTF-8 -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https -H:-UseServiceLoaderFeature -H:+StackTrace -H:-ParseOnce camel-quarkus-examples-file-bindy-ftp-2.2.0-SNAPSHOT-runner -jar camel-quarkus-examples-file-bindy-ftp-2.2.0-SNAPSHOT-runner.jar
[camel-quarkus-examples-file-bindy-ftp-2.2.0-SNAPSHOT-runner:16830]    classlist:   2,415.44 ms,  1.19 GB
[camel-quarkus-examples-file-bindy-ftp-2.2.0-SNAPSHOT-runner:16830]        setup:   1,025.59 ms,  1.19 GB
Error: could not find target field: private static org.apache.camel.quarkus.support.common.runtime.graal.SubstituteBeansWeakCache org.apache.camel.quarkus.support.common.runtime.graal.SubstituteBeansIntrospector.declaredMethodCache
com.oracle.svm.core.util.UserError$UserException: could not find target field: private static org.apache.camel.quarkus.support.common.runtime.graal.SubstituteBeansWeakCache org.apache.camel.quarkus.support.common.runtime.graal.SubstituteBeansIntrospector.declaredMethodCache
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.core.util.UserError.guarantee(UserError.java:96)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalField(AnnotationSubstitutionProcessor.java:780)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleFieldInAliasClass(AnnotationSubstitutionProcessor.java:440)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:344)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:310)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:266)
        at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:936)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:868)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)

```

### PR DESCRIPTION
**Pull request by vladimirfx**
Fix for #3226
Tested locally on a couple of Camel Quarkus projects:

Quarkus 2.4.1.Final

ubi-quarkus-native-image:21.2-java11
ubi-quarkus-native-image:21.3-java17
ubi-quarkus-native-image:21.3-java11

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by vladimirfx** [comment]
There is some special build step that I forget to do?

**Comment by zhfeng** [comment]
It's werid that ```qute.json```  got some changes. I'll take a look.

**Comment by zhfeng** [comment]
@vladimirfx what are the steps you used to verify locally ? I think it should run all intgration tests in native mode.

**Comment by zhfeng** [comment]
@vladimirfx I think you need to raise a PR agaist to ```main``` branch but not ```2.4.x``` branch.

**Comment by vladimirfx** [comment]
> @vladimirfx what are the steps you used to verify locally ? I think it should run all intgration tests in native mode.

I run full non native build locally and test resulting artifacts on own projects.

**Comment by oscerd** [comment]
Yeah, it should be against main

**Comment by vladimirfx** [comment]
Rebased on main.

**Comment by aldettinger** [comment]
I've checked locally that native tests succeed against few select project. But better wait for a full CI build to approve.

**Review by aldettinger — APPROVED** [review]

**Review by zhfeng — APPROVED** [review]

**Pull request merged**
