### PR TITLE
chore: Add git diff when there are uncommitted changes

### PR DESCRIPTION
**Pull request by essobedo**
## Motivation

There are builds failing due to uncommitted changes for which providing only the list of uncommitted files is not enough to understand the problem especially when we cannot reproduce.

## Modifications

* Add `git diff` to each command to have more info

### CODE REVIEW

**Comment by essobedo** [comment]
I can see that in the generated bom, we are supposed to have:
```
--- a/poms/bom/src/main/generated/flattened-full-pom.xml
+++ b/poms/bom/src/main/generated/flattened-full-pom.xml
@@ -21279,176 +21279,64 @@
         <version>4.0.0</version><!-- com.hazelcast:quarkus-hazelcast-client-bom:4.0.0 -->
       </dependency>
       <dependency>
-        <groupId>io.quarkus</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <artifactId>quarkus-bom-quarkus-platform-descriptor</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <version>3.0.0.Final</version><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <type>json</type><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <classifier>3.0.0.Final</classifier><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
+        <groupId>io.quarkus</groupId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <artifactId>quarkus-bom-quarkus-platform-descriptor</artifactId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <version>999-SNAPSHOT</version><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <type>json</type><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <classifier>999-SNAPSHOT</classifier><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
       </dependency>
       <dependency>
-        <groupId>com.oracle.database.jdbc.debug</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <artifactId>ojdbc11-debug</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <version>21.5.0.0</version><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <type>pom</type><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
+        <groupId>io.quarkus</groupId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <artifactId>quarkus-smallrye-reactive-messaging-pulsar-deployment</artifactId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <version>999-SNAPSHOT</version><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
       </dependency>
       <dependency>
-        <groupId>com.oracle.database.jdbc.debug</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <artifactId>ojdbc11-observability-debug</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <version>21.5.0.0</version><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <type>pom</type><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
+        <groupId>io.quarkus</groupId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <artifactId>quarkus-smallrye-reactive-messaging-pulsar</artifactId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <version>999-SNAPSHOT</version><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
       </dependency>
       <dependency>
-        <groupId>com.oracle.database.jdbc.debug</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <artifactId>ojdbc11_g</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <version>21.5.0.0</version><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
+        <groupId>io.quarkus</groupId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <artifactId>quarkus-test-hibernate-reactive-panache</artifactId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <version>999-SNAPSHOT</version><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
       </dependency>
       <dependency>
-        <groupId>com.oracle.database.jdbc.debug</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <artifactId>ojdbc11dms_g</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <version>21.5.0.0</version><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
+        <groupId>io.smallrye.reactive</groupId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <artifactId>smallrye-reactive-messaging-pulsar</artifactId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <version>4.7.0</version><!-- io.quarkus:quarkus-bom:[99](https://github.com/apache/camel-quarkus/actions/runs/5483792206/jobs/9990529159?pr=5072#step:10:100)9-SNAPSHOT -->
+        <groupId>org.apache.pulsar</groupId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <artifactId>pulsar-client-original</artifactId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <version>3.0.0</version><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
         <exclusions>
           <exclusion>
-            <groupId>io.opentelemetry</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-            <artifactId>opentelemetry-sdk</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-          </exclusion>
-          <exclusion>
-            <groupId>io.opentelemetry</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-            <artifactId>opentelemetry-sdk-trace</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-          </exclusion>
-          <exclusion>
-            <groupId>io.opentelemetry</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-            <artifactId>opentelemetry-semconv</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
+            <groupId>org.checkerframework</groupId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+            <artifactId>checker-qual</artifactId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
           </exclusion>
           <exclusion>
-            <groupId>com.fasterxml.jackson.core</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-            <artifactId>jackson-core</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
+            <groupId>commons-logging</groupId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+            <artifactId>commons-logging</artifactId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
           </exclusion>
           <exclusion>
-            <groupId>com.fasterxml.jackson.core</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-            <artifactId>jackson-databind</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
+            <groupId>javax.validation</groupId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+            <artifactId>validation-api</artifactId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
           </exclusion>
           <exclusion>
-            <groupId>com.squareup.okhttp3</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-            <artifactId>okhttp</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
+            <groupId>javax.ws.rs</groupId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+            <artifactId>javax.ws.rs-api</artifactId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
           </exclusion>
         </exclusions>
       </dependency>
       <dependency>
-        <groupId>io.opentelemetry.instrumentation</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <artifactId>opentelemetry-spring-webflux-5.0</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <version>1.23.0-alpha</version><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-      </dependency>
-      <dependency>
-        <groupId>io.smallrye.reactive</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <artifactId>smallrye-mutiny-vertx-health-checks</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <version>3.2.0</version><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-      </dependency>
-      <dependency>
-        <groupId>org.jboss.resteasy</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <artifactId>resteasy-context-propagation</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <version>6.2.1.Final</version><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-      </dependency>
-      <dependency>
-        <groupId>org.mockito</groupId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <artifactId>mockito-inline</artifactId><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
-        <version>5.2.0</version><!-- io.quarkus:quarkus-bom:3.0.0.Final -->
+        <groupId>org.flywaydb</groupId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <artifactId>flyway-database-oracle</artifactId><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
+        <version>9.20.0</version><!-- io.quarkus:quarkus-bom:999-SNAPSHOT -->
       </dependency>
     </dependencies>
   </dependencyManagement>
```

But when I build locally, it doesn't generate it, what did I do wrong?

**Comment by jamesnetherton** [comment]
I would restart `quarkus-main` branch from scratch like `git reset --hard main`.

Then adjust the Quarkus version to `999-SNAPSHOT`, sync the properties, regenerate the BOMs and run the build.

That should give you a baseline with the all of the re-generated files. Then commit as `Upgrade to Quarkus 3.3.0.CR1`. Afterwards, you can apply your work on top.

**Comment by essobedo** [comment]
@jamesnetherton ok let me do that, I don't really like to hard push in a shared branch but ok

**Comment by essobedo** [comment]
How do you regenerate the boms? I personally launch `mvn clean install` from the `poms` but the Quarkus version is not set in the generated boms, I don't know what I miss

**Comment by jamesnetherton** [comment]
Ah, I think the wierdness is happening because the build explicitly runs with `-Dquarkus.version=999-SNAPSHOT`:

https://github.com/apache/camel-quarkus/blob/main/.github/workflows/ci-build.yaml#L136

I wonder if that is a relic of the past. If the version is already set correctly on `quarkus-main` then it's not necessary to do that.

**Comment by essobedo** [comment]
Good catch, I confirm that it is why that also means that I don't need to reset the branch, that's a good news too

**Pull request closed without merging**
