### PR TITLE
Upgrade to quarkus 0.28.0

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
ok to test

**Comment by gastaldi** [comment]
I can confirm that the integration tests in quarkus-platform pass with this PR

**Comment by gastaldi** [comment]
Better update to 0.28.1 (it should be available soon)

**Comment by lburgazzoli** [comment]
@gastaldi I suspect it may be a problem of bom imported in various location

**Pull request merged**
