### PR TITLE
add file cluster service automatic configuration itest #4262

### PR DESCRIPTION
**Pull request by aldettinger**

### CODE REVIEW

**Review by jamesnetherton — COMMENTED** [review]
Not sure if this can work on quarkus-platform. So maybe we need to add it to the exclusion list here:

https://github.com/apache/camel-quarkus/blob/874a2cb209e48d8b5655eb873ca86cef896d2911/tooling/test-list/pom.xml#L57

**Review by oscerd — APPROVED** [review]

**Comment by aldettinger** [comment]
> Not sure if this can work on quarkus-platform. So maybe we need to add it to the exclusion list here:
> 
> https://github.com/apache/camel-quarkus/blob/874a2cb209e48d8b5655eb873ca86cef896d2911/tooling/test-list/pom.xml#L57

Well spotted, I've forced push with this correction.

**Review by jamesnetherton — APPROVED** [review]
Project version got bumped to `2.15.0-SNAPSHOT`. So you'll need to rebase and update `master-file/pom.xml`.

**Comment by aldettinger** [comment]
Ok, I pushed the update accordingly.

**Pull request merged**
