### PR TITLE
Fix Netty integration tests on FIPS system

### PR DESCRIPTION
**Pull request by osmman**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by grgrzybek — APPROVED** [review]

**Review by aldettinger — CHANGES_REQUESTED** [review]
@osmman Many thanks for contribution. The CI issue is highly likely to be fixed in the root pom.xml where `**/*.bcfks` file would need to be excluded for the `license-maven-plugin`.

**Review by zhfeng — APPROVED** [review]

**Review by aldettinger — APPROVED** [review]

**Review by ppalaga — CHANGES_REQUESTED** [review]
Great contribution, thanks a lot @osmman!

Because we now have a new trust store and a new keystore the [README](https://github.com/apache/camel-quarkus/blob/main/integration-tests/netty/README.adoc) would deserve some update, wouldn't it?

Besides, when we are now able to run on a FIPs enabled system, it would be nice to drop a note in `extensions/netty/runtime/src/main/doc/usage.adoc` informing about the additional dependencies and special store type required for running on a FIPs enabled system.

**Comment by osmman** [comment]
> Great contribution, thanks a lot @osmman!
> 
> Because we now have a new trust store and a new keystore the [README](https://github.com/apache/camel-quarkus/blob/main/integration-tests/netty/README.adoc) would deserve some update, wouldn't it?
> 
> Besides, when we are now able to run on a FIPs enabled system, it would be nice to drop a note in `extensions/netty/runtime/src/main/doc/usage.adoc` informing about the additional dependencies and special store type required for running on a FIPs enabled system.

I updated the [README](https://github.com/apache/camel-quarkus/blob/main/integration-tests/netty/README.adoc) file.

I am thinking about a place where to put notes for FIPS because this is a global problem for all camel components (80+) that use SslContextParameters. Have you got an idea?

**Review by ppalaga — APPROVED** [review]

**Comment by ppalaga** [comment]
> global problem for all camel components (80+) that use SslContextParameters

I'd be for creating a new page under https://github.com/apache/camel-quarkus/tree/main/docs/modules/ROOT/pages/user-guide 

I guess you prefer doing it in a follow up PR so that we can merge this one?

**Comment by osmman** [comment]
> I guess you prefer doing it in a follow up PR so that we can merge this one?

Yes, I will do that in a follow up PR. https://github.com/apache/camel-quarkus/issues/4158

**Review by zbendhiba — APPROVED** [review]

**Comment by ppalaga** [comment]
Is this good to merge @osmman ?

**Pull request merged**
