### PR TITLE
fix extension creation on Windows

### LINKED ISSUE #2999: creation of extension on windows failed
OS : Windows

mvn cq:create -N -Dcq.artifactIdBase=cxf

error log:
[ERROR] Failed to execute goal org.l2x6.cq:cq-maven-plugin:0.38.0:create (default-cli) on project camel-quarkus: Execution default-cli of goal org.l2x6.cq:cq-maven-plugin:0.38.0:create failed: Illegal character [:] in path at index 4: ///D:\src\camel-quarkus/tooling/create-extension-templates -> [Help 1]

it come from main pom.xml:
```
<templatesUriBase>file:///${project.basedir}/tooling/create-extension-templates</templatesUriBase>
```
and it is used in org.apache.camel.quarkus.maven.CqUtils

templatesUriBase on my desktop was : `file:///D:\src\camel-quarkus/tooling/create-extension-templates`
FILE_PREFIX is removed so I end with "///D:\src\camel-quarkus/tooling/create-extension-templates" in createTemplateLoader

I think uri on windows must be `D:\src\camel-quarkus\tooling\create-extension-templates`

quick hack is maybe just in org.apache.camel.quarkus.maven.CqUtils.createTemplateLoader : 
```
diff --git a/tooling/maven-plugin/src/main/java/org/apache/camel/quarkus/maven/CqUtils.java b/tooling/maven-plugin/src/main/java/org/apache/camel/quarkus/maven/CqUtils.java
index d74490355..57a78ff60 100644
--- a/tooling/maven-plugin/src/main/java/org/apache/camel/quarkus/maven/CqUtils.java
+++ b/tooling/maven-plugin/src/main/java/org/apache/camel/quarkus/maven/CqUtils.java
@@ -63,7 +63,13 @@ public class CqUtils {
                             defaultLoader //
                     });
         } else if (templatesUriBase.startsWith(FILE_PREFIX)) {
-            final Path resolvedTemplatesDir = basePath.resolve(templatesUriBase.substring(FILE_PREFIX.length()));
+            String templatesUri = templatesUriBase.substring(FILE_PREFIX.length());
+            //windows uri
+            if (templatesUri.contains(":")) {
+                templatesUri = templatesUri.substring(3);
+                templatesUri = templatesUri.replaceAll("/","\\");
+            }
+            final Path resolvedTemplatesDir = basePath.resolve(templatesUri);
             try {
                 return new MultiTemplateLoader( //
                         new TemplateLoader[] { //
```

### PR DESCRIPTION
**Pull request by dufoli**
fix #2999

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by dufoli** [comment]
I am still failing on JfrConfigInterceptorTest with tempdir injection with NPE. I do not know if it is a junit test or an environment issue...

**Comment by ppalaga** [comment]
Thanks @dufoli , 6524d57 looks good. 
I'd like to see the other Windows fixes pass the CI separately. Could you please submit them as a separate PR?

**Comment by dufoli** [comment]
@ppalaga  done

**Comment by dufoli** [comment]
I have create a new PR for full windows support

**Comment by aldettinger** [comment]
Are we ok with closing this as the work is occurring in [another PR](https://github.com/apache/camel-quarkus/pull/3009) ?

**Comment by ppalaga** [comment]
Yep, looks good, thanks @dufoli!

**Pull request merged**
