### PR TITLE
Fix #3951 to add a test with quarkus-pooled-jms

### LINKED ISSUE #3951: Add a test in camel-quarkus-integration-test-jms-artemis-client with quarkus-pooled-jms
It needs to verify the pooling capability provided by [quarkus-pooled-jms](https://github.com/quarkiverse/quarkus-pooled-jms)

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by jamesnetherton** [comment]
Just so I understand things - we're not adding `quarkus-pooled-jms` to `camel-quarkus-bom` because there are some issues to resolve? So for now we just add to the test BOM for our internal testing?

**Comment by zhfeng** [comment]
No, it looks like I added it in a wrong BOM. I think we should manage it.

**Comment by zhfeng** [comment]
@jamesnetherton @ppalaga 
Hmm, I moved `quarkus-pooled-jms` to `camel-quarkus-bom` but it can not be included in `poms/bom/src/main/generated/flattened-reduced-pom.xml`. I guess it is becaus there is no extension directly depends on it. I tried to add it as an optional dependency in `extensions/jms/runtime/pom.xml` and it works. So is it right or anything I missed?

**Comment by zhfeng** [comment]
OK, I add `<resolutionEntryPointInclude>io.quarkiverse.messaginghub:*</resolutionEntryPointInclude>` to  sort it out.

**Review by jamesnetherton — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Review by zbendhiba — APPROVED** [review]

**Pull request merged**
