### PR TITLE
Fix documentation

### PR DESCRIPTION
**Pull request by aldettinger**

### CODE REVIEW

**Comment by aldettinger** [comment]
Proposal to remove the mention of quarkus-bom from the doc as it is not imported anymore.

https://repo1.maven.org/maven2/org/apache/camel/quarkus/camel-quarkus-bom/2.7.1/camel-quarkus-bom-2.7.1.pom (no quarkus-bom)
https://repo1.maven.org/maven2/org/apache/camel/quarkus/camel-quarkus-bom/2.7.0/camel-quarkus-bom-2.7.0.pom (quarkus-bom)

**Comment by ppalaga** [comment]
Good catch, @aldettinger , although now that camel-quarkus-bom does not import Quarkus BOM, it is not a simple replacement anymore. End users would have to also import quarkus-bom and take care that the versions are compatible. I'd vote for removing the whole `== Camel Quarkus BOM` section.

**Comment by aldettinger** [comment]
I've updated the PR accordingly.

**Review by jamesnetherton — APPROVED** [review]

**Review by zbendhiba — APPROVED** [review]

**Comment by aldettinger** [comment]
ok, backported to 2.7.x also.

**Pull request merged**
