### PR TITLE
perf-regresssion: fix number format exception when java and mvnw don'…

### PR DESCRIPTION
**Pull request by aldettinger**
…t have same default locale #4014

### CODE REVIEW

**Comment by aldettinger** [comment]
@zbendhiba Time permitting, it would be awesome if this PR could be tested in an environment where the bug is truly reproduceable. More info in #4014

**Review by zbendhiba — CHANGES_REQUESTED** [review]
@aldettinger   This works fine for Locale = fr_FR.UTF-8, but not for some other Locales. For instance when I try Locale = de_DE.UTF-8, the format of the Double is like that "#,##0.00", and we get a different error, as the String is not compatible with the Regex anymore. This is the kind of error we get with Locale =  de_DE.UTF-8 : ```Expected: a string containing " req/s [+0.00%] "
     but: was "       2.12.0-SNAPSHOT  |        1s  |  166,00 req/s [+0,00%]  |      OK  |"```. IMHO, we need to set the Locale to en_US, to get the right sentence, and avoid any Double/String conversion

**Comment by aldettinger** [comment]
@zbendhiba The reported error message seems to indicate that the expected for the `nominalShouldPrintReport` integration-test is locale dependent. I can't reproduce this though, steps to reproduce would help here.

Overriding the default locale in sub-processes with MAVEN_OPTS would put us in a more secure/repeatable situation to the price of overriding some environment settings made by users for good reasons. For instance, maybe there is a good reason that the default locale is different between java and maven on your machine ? Or do you think it would always be safe to override the default locale ?

**Comment by zbendhiba** [comment]
I was thinking of setting in the code with Java. If this meant to be executed also for native mode. Add this to the configuration: 
``` 
quarkus.native.user-country=US
quarkus.native.user-language=en 
```
Just to prevent it from failing locally, as Double is different regarding to our native languages. My laptop is setup with French language by default.

To reproduce on Linux, you can change the Locale this way : `export LANG=de_DE.UTF-8` in a terminal, before executing the test

**Comment by aldettinger** [comment]
The code formatting the double is from the hyperfoil-maven-plugin, not sure they would like to override the default locale with java code. Plus it would need a release. Anyway, it should be possible to do it on our side [with MAVEN_OPTS](https://github.com/apache/camel-quarkus/blob/main/tooling/perf-regression/src/main/java/org/apache/camel/quarkus/performance/regression/MvnwCmdHelper.java#L71).

Concerning native, there is no need for native support in the tool itself. The sample application under test could also be tested in native with the `-an` option. This is already working without tweaking locales.

The current PR should work as soon as java and maven have the same default locale. However itests are not working.
For instance, below would be expected to work:
```
mvn clean install -Dquickly
java -jar target/quarkus-app/quarkus-run.jar -d 1s 2.11.0
```

Thanks for sharing the way to reproduce. Experimenting with that should help to identify the best solution :+1:

**Comment by aldettinger** [comment]
Actually, both ways could work. I've opted to use a fixed en_US locale:
 + for interactions between the tool and underlying maven builds
 + when the tool format the report that will be printed to the console

This should work as soon as:
 + using `-Duser.language=...` has precedence over other ways of overriding the default locale
 + when passing mutliple `-user.language=` statements to the JVM, only the last takes effect
 + the en_US locale is available on all JREs

If overriding user environments/configs/variables generate other issues. Then we could still fallback to the initial solution with a regex.

**Review by zbendhiba — APPROVED** [review]

**Pull request merged**
