### PR TITLE
Register all types annotated with @UriParams for reflection

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by davsclaus** [comment]
`@UriParam`'s are configured via direct java method calls in Camel 3 (we source code generate configurer classes).

**Comment by lburgazzoli** [comment]
ah right so maybe better to see if we can remove those configuration classes at all and only add them when it is needed

**Comment by ppalaga** [comment]
@davsclaus 'es point is true about `@UriParam` without `s` but this PR is about `@UriParams` with `s`. Having said that, the we might want to generate the configurers in the Camel side also for `@UriParams` but as long as that's not the case, I think this PR makes sense.

**Comment by davsclaus** [comment]
UriParams (with an s) are just a reference for a configuration class which has UriParam (no s). So there are no reflection or special for this. Its used for tooling to know how to follow where there are options that it need to extract and put in the camel-catalog and so on.

**Comment by ppalaga** [comment]
Let me re-check my assumptions. The native tests for the adjusted telegram (hosted inside camel-quarkus tree) were failing unless I registered TelegramConfiguration for reflection. Then I saw most extensions were registering their `@UriParams` annotated configs for reflection. So I concluded they all have to be registered. Let me check if the itests are failing for other extensions if I do not register their `@UriParams`. Perhaps there is something wrong in my adjusted telegram.

**Comment by lburgazzoli** [comment]
There should be an auto generated class that maps parameters with a method call

**Comment by ppalaga** [comment]
> There should be an auto generated class that maps parameters with a method call

Yes, I can see two of them: for the component and for endpoint. But there is none for the configuration, whose getters/setters are apparently hit too. The stacktrace at the bottom is for Dozer in native mode (jvm mode works) with the `@uriParams` registration for reflection turned off. You mean that it should work without the registration, right?

```
2019-12-05 14:28:57,095 ERROR [org.apa.cam.qua.cor.FastCamelContext] (main) Error starting CamelContjava.lang.RuntimeException: org.apache.camel.FailedToCreateRouteException: Failed to create route roext (camel-1) due to exception thrown: Failed to create route route2 at: >>> To[dozer:simpleMapping?ute2 at: >>> To[dozer:simpleMapping?mappingFile=simple-mapping.xml&targetModel=org.apache.camel.quarmappingFile=simple-mapping.xml&targetModel=org.apache.camel.quarkus.component.dozer.it.model.Customekus.component.dozer.it.model.CustomerB] <<< in route: Route(route2)[From[direct:mapWithEndpoint] -> rB] <<< in route: Route(route2)[From[direct:mapWithEndpoint] -> [To[dozer:simp... because of Failed [To[dozer:simp... because of Failed to resolve endpoint: dozer://simpleMapping?mappingFile=simple-mato resolve endpoint: dozer://simpleMapping?mappingFile=simple-mapping.xml&targetModel=org.apache.camel.quarkus.component.dozer.it.model.CustomerB due to: The targetModel parameter is required for dozepping.xml&targetModel=org.apache.camel.quarkus.component.dozer.it.model.CustomerB due to: The targetr endpoints: org.apache.camel.FailedToCreateRouteException: Failed to create route route2 at: >>> ToModel parameter is required for dozer endpoints
        at org.apache.camel.quarkus.core.CamelMainRecorder.[dozer:simpleMapping?mappingFile=simple-mapping.xml&targetModel=org.apache.camel.quarkus.component.dstart(CamelMainRecorder.java:81)
        at io.quarkus.deployment.steps.Main$start78.deploy_0(Main$start78.ozer.it.model.CustomerB] <<< in route: Route(route2)[From[direct:mapWithEndpoint] -> [To[dozer:simp.zig:97)
        at io.quarkus.deployment.steps.Main$start78.deploy(Main$start78.zig:36)
        at io.quarkus.runn.. because of Failed to resolve endpoint: dozer://simpleMapping?mappingFile=simple-mapping.xml&targeer.ApplicationImpl.doStart(ApplicationImpl.zig:169)
        at io.quarkus.runtime.Application.start(ApplicatModel=org.apache.camel.quarkus.component.dozer.it.model.CustomerB due to: The targetModel parametertion.java:94)
        at io.quarkus.runtime.Application.run(Application.java:218)
        at io.quarkus.runner.Gen is required for dozer endpoints
        at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifieeratedMain.main(GeneratedMain.zig:41)
Caused by: org.apache.camel.FailedToCreateRouteException: Failr.java:386)
        at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:108)
        at org.apaed to create route route2 at: >>> To[dozer:simpleMapping?mappingFile=simple-mapping.xml&targetModel=che.camel.quarkus.core.FastModel.start(FastModel.java:61)
        at org.apache.camel.quarkus.core.BaseModeorg.apache.camel.quarkus.component.dozer.it.model.CustomerB] <<< in route: Route(route2)[From[directl.startRoute(BaseModel.java:327)
        at org.apache.camel.quarkus.core.BaseModel.startRouteDefinitions(B:mapWithEndpoint] -> [To[dozer:simp... because of Failed to resolve endpoint: dozer://simpleMapping?aseModel.java:320)
        at org.apache.camel.quarkus.core.BaseModel.startRouteDefinitions(BaseModel.java:mappingFile=simple-mapping.xml&targetModel=org.apache.camel.quarkus.component.dozer.it.model.Custome299)
        at org.apache.camel.quarkus.core.FastCamelContext.startRouteDefinitions(FastCamelContext.java:rB due to: The targetModel parameter is required for dozer endpoints
        at org.apache.camel.reifier.Ro139)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:2597)
        at org.apache.camel.impl.engine.AbstractCamelContext.lambda$doStart$2(AbstractCamelContext.javauteReifier.doCreateRoute(RouteReifier.java:386)
        at org.apache.camel.reifier.RouteReifier.createRout:2445)
        at org.apache.camel.impl.engine.AbstractCamelContext.doWithDefinedClassLoader(AbstractCamelCe(RouteReifier.java:108)
        at org.apache.camel.quarkus.core.FastModel.start(FastModel.java:61)
        at orontext.java:2462)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2443)
        at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:117)
        at og.apache.camel.quarkus.core.BaseModel.startRoute(BaseModel.java:327)
        at org.apache.camel.quarkus.corg.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2352)
        at org.apachre.BaseModel.startRouteDefinitions(BaseModel.java:320)
        at org.apache.camel.quarkus.core.BaseModel.se.camel.quarkus.core.CamelMain.doStart(CamelMain.java:47)
        at org.apache.camel.support.service.ServitartRouteDefinitions(BaseModel.java:299)
        at org.apache.camel.quarkus.core.FastCamelContext.startRouceSupport.start(ServiceSupport.java:117)
        at org.apache.camel.quarkus.core.CamelMainRecorder.start(CteDefinitions(FastCamelContext.java:139)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStaamelMainRecorder.java:79)
        at io.quarkus.deployment.steps.Main$start78.deploy_0(Main$start78.zig:97)rtCamel(AbstractCamelContext.java:2597)
        at org.apache.camel.impl.engine.AbstractCamelContext.lambda
        at io.quarkus.deployment.steps.Main$start78.deploy(Main$start78.zig:36)
        at io.quarkus.runner.Appl$doStart$2(AbstractCamelContext.java:2445)
        at org.apache.camel.impl.engine.AbstractCamelContext.doWicationImpl.doStart(ApplicationImpl.zig:169)
        at io.quarkus.runtime.Application.start(Application.jaithDefinedClassLoader(AbstractCamelContext.java:2462)
        at org.apache.camel.impl.engine.AbstractCamelva:94)
        at io.quarkus.runtime.Application.run(Application.java:218)
        at io.quarkus.runner.GeneratedMContext.doStart(AbstractCamelContext.java:2443)
        at org.apache.camel.support.service.ServiceSupport.ain.main(GeneratedMain.zig:41)
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed tostart(ServiceSupport.java:117)
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractC resolve endpoint: dozer://simpleMapping?mappingFile=simple-mapping.xml&targetModel=org.apache.camelamelContext.java:2352)
        at org.apache.camel.quarkus.core.CamelMain.doStart(CamelMain.java:47)
        at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:117)
        at org.apache.camel.quarkus.core.CamelMainRecorder.start(CamelMainRecorder.java:79)
        ... 6 more
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: dozer://simpleMapping?mappingFile=simple-mapping.xml&targetModel=org.apache.camel.quarkus.component.dozer.it.model.CustomerB due to: The targetModel parameter is required for dozer endpoints
        at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:803)
        at org.apache.camel.impl.engine.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:127)
        at org.apache.camel.reifier.SendReifier.resolveEndpoint(SendReifier.java:41)
        at org.apache.camel.reifier.SendReifier.createProcessor(SendReifier.java.quarkus.component.dozer.it.model.CustomerB due to: The targetModel parameter is required for dozer :34)
        at org.apache.camel.reifier.ProcessorReifier.makeProcessorImpl(ProcessorReifier.java:571)
        at endpoints
        at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.javorg.apache.camel.reifier.ProcessorReifier.makeProcessor(ProcessorReifier.java:537)
        at org.apache.caa:803)
        at org.apache.camel.impl.engine.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.javamel.reifier.ProcessorReifier.addRoutes(ProcessorReifier.java:250)
        at org.apache.camel.reifier.Route:127)
        at org.apache.camel.reifier.SendReifier.resolveEndpoint(SendReifier.java:41)
        at org.apache.cReifier.doCreateRoute(RouteReifier.java:384)
        ... 21 more
Caused by: java.lang.IllegalArgumentExceptamel.reifier.SendReifier.createProcessor(SendReifier.java:34)
        at org.apache.camel.reifier.Processorion: The targetModel parameter is required for dozer endpoints
        at org.apache.camel.component.dozer.Reifier.makeProcessorImpl(ProcessorReifier.java:571)
        at org.apache.camel.reifier.ProcessorReifier.mDozerComponent.createEndpoint(DozerComponent.java:48)
        at org.apache.camel.support.DefaultComponent.akeProcessor(ProcessorReifier.java:537)
        at org.apache.camel.reifier.ProcessorReifier.addRoutes(ProccreateEndpoint(DefaultComponent.java:240)
        at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:755)
        ... 28 more
essorReifier.java:250)
        at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:384)
        ... 21 more
Caused by: java.lang.IllegalArgumentException: The targetModel parameter is required for dozer endpoints
        at org.apache.camel.component.dozer.DozerComponent.createEndpoint(DozerComponent.java:48)
        at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:240)
        at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:755)
        ... 28 more
```

**Comment by lburgazzoli** [comment]
yes it should, if not we may need to refine our process as what Claus did was exactly done to avoid reflection but there may be some edge cases

**Comment by ppalaga** [comment]
OK, I can file a Camel JIRA for this, but I suggest to merge the current PR because it's substantial part is the removal of the registration code from the individual extensions.

**Comment by lburgazzoli** [comment]
I would first investigate case by case as we should not register for reflection classes that are not required

**Comment by ppalaga** [comment]
Created https://issues.apache.org/jira/browse/CAMEL-14263

**Pull request closed without merging**
