### PR TITLE
Leverage Quarkus plugin's generate-code mojo instead of protobuf-maven-plugin to generate protobuf stubs

### LINKED ISSUE #789: Protobuf dataformat native support
Followup: https://github.com/apache/camel-quarkus/issues/964

### PR DESCRIPTION
**Pull request by ppalaga**
Fix #789

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by jamesnetherton — APPROVED** [review]

**Comment by ppalaga** [comment]
@jamesnetherton could you please re-review?

* The Quarkus plugin's generate-code mojo commit has a fix for the Heisenbug
* New protobuf commit

**Comment by jamesnetherton** [comment]
> @jamesnetherton could you please re-review?
> 
> * The Quarkus plugin's generate-code mojo commit has a fix for the Heisenbug
> * New protobuf commit

Looks good to me :+1: 

Should we perhaps drop a note into our gRPC docs to point users at `quarkus-maven-plugin` to do the proto class generation? The camel component docs reference `org.xolstice.maven.plugins:protobuf-maven-plugin`, which is maybe not desirable here.

**Comment by ppalaga** [comment]
> Should we perhaps drop a note into our gRPC docs to point users at `quarkus-maven-plugin`

Of course, I even had it in one of my revisions and I wonder why it disappeared. Thanks for noticing! Let me find it.

**Comment by ppalaga** [comment]
The messaging failure does not seem to be related.

**Pull request merged**
