### PR TITLE
Snmp: reworked tests to avoid flaky failures

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/apache/camel-quarkus/issues/4850

Attempt to remove possible `ConcurrentModificationException` on `Vector`

### CODE REVIEW

**Comment by jamesnetherton** [comment]
I ran the build a second time and passed like the first time.

**Comment by ppalaga** [comment]
@JiriOndrusek looks good, thanks! Could we please eliminate the compile warnings something like I sent in https://github.com/JiriOndrusek/camel-quarkus/pull/1 ? 

I am investigating the failure in the SOAP grouped test.

**Comment by ppalaga** [comment]
The soap failure is 

```
2023-05-03 11:29:10,385 INFO  [🐳 .io/.1]] (pool-2-thread-1) Pulling docker image: quay.io/l2x6/calculator-ws:1.1. Please be patient; this may take some time but only needs to be done once.
2023-05-03 11:29:10,580 INFO  [🐳 .io/.1]] (docker-java-stream--805919771) Starting to pull image
2023-05-03 11:29:10,606 INFO  [🐳 .io/.1]] (docker-java-stream--805919771) Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
2023-05-03 11:29:11,098 INFO  [🐳 .io/.1]] (docker-java-stream--805919771) Pulling image layers:  4 pending,  1 downloaded,  0 extracted, (64 MB/? MB)
2023-05-03 11:29:11,220 INFO  [🐳 .io/.1]] (docker-java-stream--805919771) Pulling image layers:  3 pending,  2 downloaded,  0 extracted, (79 MB/? MB)
2023-05-03 11:29:11,408 INFO  [🐳 .io/.1]] (docker-java-stream--805919771) Pulling image layers:  2 pending,  3 downloaded,  0 extracted, (92 MB/? MB)
2023-05-03 11:29:13,028 INFO  [🐳 .io/.1]] (docker-java-stream--805919771) Pulling image layers:  1 pending,  4 downloaded,  0 extracted, (323 MB/? MB)
2023-05-03 11:29:13,756 INFO  [🐳 .io/.1]] (docker-java-stream--805919771) Pulling image layers:  1 pending,  4 downloaded,  1 extracted, (370 MB/? MB)
2023-05-03 11:29:14,529 INFO  [🐳 .io/.1]] (docker-java-stream--805919771) Pulling image layers:  0 pending,  5 downloaded,  1 extracted, (431 MB/447 MB)
2023-05-03 11:29:15,737 INFO  [🐳 .io/.1]] (docker-java-stream--805919771) Pulling image layers:  0 pending,  5 downloaded,  2 extracted, (432 MB/447 MB)
2023-05-03 11:29:19,535 INFO  [🐳 .io/.1]] (docker-java-stream--805919771) Pulling image layers:  0 pending,  5 downloaded,  3 extracted, (446 MB/447 MB)
2023-05-03 11:29:19,588 INFO  [🐳 .io/.1]] (docker-java-stream--805919771) Pulling image layers:  0 pending,  5 downloaded,  4 extracted, (446 MB/447 MB)
2023-05-03 11:29:23,146 INFO  [🐳 .io/.1]] (docker-java-stream--805919771) Pulling image layers:  0 pending,  5 downloaded,  5 extracted, (447 MB/447 MB)
2023-05-03 11:29:23,154 INFO  [🐳 .io/.1]] (docker-java-stream--805919771) Pull complete. 5 layers, pulled in 12s (downloaded 447 MB at 37 MB/s)
2023-05-03 11:29:23,200 INFO  [🐳 .io/.1]] (pool-2-thread-1) Creating container for image: quay.io/l2x6/calculator-ws:1.1
2023-05-03 11:29:23,294 INFO  [🐳 .io/.1]] (pool-2-thread-1) Container quay.io/l2x6/calculator-ws:1.1 is starting: c8fa87f0c432fda916e340b49b4503d6b50e606de1f00f3f0c5c773d5bc43b7f
2023-05-03 11:29:23,726 INFO  [org.tes.con.wai.str.HttpWaitStrategy] (pool-2-thread-1) /heuristic_kapitsa: Waiting for 60 seconds for URL: http://localhost:32768/calculator-ws/CalculatorService?wsdl (where port 32768 maps to container port 8080)
2023-05-03 11:29:24,470 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDOUT: 
2023-05-03 11:29:24,475 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDOUT:  * Error * 
2023-05-03 11:29:24,476 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDOUT: WFLYDM0106: File permissions problems found while attempting to update /opt/jboss/wildfly/domain/configuration/application-users.properties file.
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDOUT: 
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDERR: Exception in thread "main" org.jboss.as.domain.management.security.adduser.AddUserFailedException: WFLYDM0106: File permissions problems found while attempting to update /opt/jboss/wildfly/domain/configuration/application-users.properties file.
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDERR: 	at org.jboss.as.domain-management@18.1.1.Final//org.jboss.as.domain.management.security.adduser.ErrorState.execute(ErrorState.java:72)
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDERR: 	at org.jboss.as.domain-management@18.1.1.Final//org.jboss.as.domain.management.security.adduser.AddUser.run(AddUser.java:133)
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDERR: 	at org.jboss.as.domain-management@18.1.1.Final//org.jboss.as.domain.management.security.adduser.AddUser.main(AddUser.java:233)
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDERR: 	at org.jboss.modules.Module.run(Module.java:353)
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDERR: 	at org.jboss.modules.Module.run(Module.java:321)
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDERR: 	at org.jboss.modules.Main.main(Main.java:604)
2023-05-03 11:29:24,800 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDOUT: =========================================================================
2023-05-03 11:29:24,805 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDOUT: 
```

It is caused by the recent change https://github.com/l2x6/calculator-ws/pull/9 in the test container by @llowinge I'll have to revert it.

**Comment by llowinge** [comment]
@ppalaga Let me try to do fix.

**Comment by ppalaga** [comment]
The SOAP failure is being solved by reverting the breaking change in the test container tag 1.1. @llowinge works on a fig in 1.2 branch  - see https://github.com/l2x6/calculator-ws/issues/10

**Comment by JiriOndrusek** [comment]
> 

I'll eliminate the warnings as you suggested. Unfortunately the change does not help with the problems in 2.13.x.
I've seen another issue (only warning but seems important - `java.io.IOException: The actual length of the SEQUENCE object org.snmp4j.PDUv1 is 24, but 41 was expected`.
Problem is probably caused by the fact, that 2.13.x uses camel 3.18.6, which uses snmp4j (            <groupId>org.apache.servicemix.bundles</groupId>
            <artifactId>org.apache.servicemix.bundles.snmp4j</artifactId> of version 2.6.3_1)
            `main` uses org.snmp4j.snmp4j.2.8.15.
            I've never seen such issue on main.

**Comment by ppalaga** [comment]
The reverted 1.1 image is now available on quay.io and the soap test is passing again for me locally.

**Comment by ppalaga** [comment]
> `java.io.IOException: The actual length of the SEQUENCE object org.snmp4j.PDUv1 is 24, but 41 was expected`.
> 
> Problem is probably caused by the fact, that 2.13.x uses camel 3.18.6, which uses snmp4j (
> 
> ```
>            <groupId>org.apache.servicemix.bundles</groupId>
>             <artifactId>org.apache.servicemix.bundles.snmp4j</artifactId> of version 2.6.3_1)
> ```
> 
> ```
>      `main` uses org.snmp4j.snmp4j.2.8.15.
> ```

Perhaps we should try to upgrade to 2.8.15 in 2.13.x via managing it in our BOM?

**Comment by JiriOndrusek** [comment]
Upgrading to 2.8.15 in our bo,  is probably the only viable option. I tried it, but I'm getting `Failed to create Producer for endpoint: snmp://udp:127.0.0.1/43411. Reason: java.lang.NoSuchMethodError: 'void org.snmp4j.security.SecurityModels.addSecurityModel` during execution of the test. I'll continue tomorrow morning with the issue. (I don't think that there should be any such problem)

**Comment by JiriOndrusek** [comment]
This PR is prepared to be merged. The failing CI is not related to this PR (cxf-soap). The previous comment is targeting backport to `2.13.x` branch.

**Comment by JiriOndrusek** [comment]
@ppalaga @jamesnetherton 
It is more complicated  to backport this change to 2.13.x correctly then expected
Let me explain:

If I backport ([PR](https://github.com/apache/camel-quarkus/pull/4870)) the changes to 2.13.x (which inherits `org.apache.servicemix.bundles.snmp4j` -> tests are flaky. I'm able to see problems approximately in 1 of 4 runs using docker with limited memory. This is not happening on `main` branch, whih uses `org.snmp4j.snmp4j`.

I tried to replace `org.apache.servicemix.bundles.snmp4j` with `org.snmp4j.snmp4j` in BOM. Unfortunatelly there is a change of signature between `  public void addSecurityModel(SecurityModel model) {` and `public SecurityModels addSecurityModel(SecurityModel model) {` (method is called from this camel [line](https://github.com/apache/camel/blob/camel-3.18.x/components/camel-snmp/src/main/java/org/apache/camel/component/snmp/SnmpProducer.java#L75))

The only solution I see is to rewrite the [method](https://github.com/apache/camel/blob/camel-3.18.x/components/camel-snmp/src/main/java/org/apache/camel/component/snmp/SnmpProducer.java#L68-L100) `doStart` in extension's Recorder with the exact same code, but using `org.snmp4j.snmp4j` and verify, that the flakiness is solved.
WDYT?

**Pull request merged**
