### PR TITLE
Support JMS ObjectMessage

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
Having dug into the serialization support code a bit more. I think my docs are a bit misleading. In this case, there's actually no need for users to explicitly enable it via the config property because the extension(s) produce `CamelSerializationBuildItem`. I'll amend the wording...

**Comment by jamesnetherton** [comment]
Latest commit fixes the wording of the documentation to something that more accurately describes the serialization support.

**Comment by jamesnetherton** [comment]
Latest commit adds the `org.w3c.dom.Node` statement to SJMS & SJMS2 docs (I mistakenly thought those components did not support it).

**Comment by ppalaga** [comment]
Perfect, thanks!

**Pull request merged**
