### PR TITLE
Merge the performance regression detection prototype #3905

### PR DESCRIPTION
**Pull request by aldettinger**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by zhfeng — COMMENTED** [review]
@aldettinger is it possible to reuse such `mvnw` in the root directory?

**Comment by aldettinger** [comment]
> @aldettinger is it possible to reuse such `mvnw` in the root directory?

@zhfeng Thanks for feedback. It looks that the root mvnw has a far more recent version. So we should probably align on this one if feasible, and probably we can remove the .mvn folder after that.

I would take it as a dedicated task in another ticket. What do you think ?

**Comment by zhfeng** [comment]
yeah, it looks good to me.

**Comment by aldettinger** [comment]
> yeah, it looks good to me.

Ok, I've filed #3960 in this respect

**Comment by aldettinger** [comment]
Another pair of eyes on this subject ? Feel welcome to ask questions if something is not clear enough.

**Comment by jamesnetherton** [comment]
It looks mostly ok to me.

A nitpick on the Maven Wrapper. If we are going to (at least temporarily) have the sample project use its own wrapper, we should probably make sure the version is aligned with the one used by CQ.

Also, do you think we should add a dedicated docs page for this? I.e perhaps eventually  it'd be part of the release process to do a perf check, so we could link to the relevant bits from the release guide.

**Comment by aldettinger** [comment]
@jamesnetherton The wrapper version is next on my list #3960. And yes, we could also add some improvements like integrating the tool in the release process #3967.

**Pull request merged**
