### PR TITLE
Bump quarkus-artemis to 3.0.0.Alpha7 and quarkus-pooled-jms to 2.0.0.CR2

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by jamesnetherton — APPROVED** [review]

**Comment by jamesnetherton** [comment]
Looks like one of the example projects will maybe need fixing up.

**Review by aldettinger — APPROVED** [review]
Indeed, beyond LGTM.

**Comment by zhfeng** [comment]
Yeah, there is a break change with `quarkus.pooled-jms.xa.enabled`. It needs to change to `quarkus.pooled-jms.transacion=xa`

I will open a PR to fix it in `camel-quarkus-example` after merging this one.

**Comment by zhfeng** [comment]
Fix camel-quarkus-examples https://github.com/apache/camel-quarkus-examples/pull/135

**Pull request merged**
