### PR TITLE
Add spring common extension

### LINKED ISSUE #538: Add support/spring artifact for common substrate support
Extract Spring substitutions etc, from the SQL extension into its own 'common' support artifact, since they will likely be needed for other Camel components that we add in the future.

### PR DESCRIPTION
**Pull request by jamesnetherton**
fixes #538

### CODE REVIEW

**Comment by jamesnetherton** [comment]
ok to test

**Comment by jamesnetherton** [comment]
ok to test

**Comment by jamesnetherton** [comment]
ok to test

**Comment by oscerd** [comment]
LGTM

**Pull request merged**
