### PR TITLE
Spark JVM support

### PR DESCRIPTION
**Pull request by ppalaga**
Related https://github.com/apache/camel-quarkus/issues/1701

This is the idea how we could handle this kind of dependency hell components. The artifacts are managed in the runtime module so that they do not to pollute the BOM.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by jamesnetherton — APPROVED** [review]

**Comment by ppalaga** [comment]
Let me write a test

**Comment by ppalaga** [comment]
a1b5695 :
* Added a proper test
* dependencyManagement in a separate camel-quarkus-spark-bom

Please re-review

**Review by jamesnetherton — APPROVED** [review]
Looks good.

I wonder if we should place the spark specific version properties within the spark bom and keep them out of the root pom. WDYT?

**Comment by ppalaga** [comment]
> I wonder if we should place the spark specific version properties within the spark bom and keep them out of the root pom. WDYT?

I'd like to have them in the top pom so that everyone can see that those artifacts are used somewhere. I find this important for the case that they pop up through some other extension. In such a case we should make a conscious decision whether they should be managed in the main BOM or somewhere else. That could get forgotten easily if there is no trace of them in the top pom. WDYT?

**Comment by ppalaga** [comment]
I should document the peculiarities.

**Comment by jamesnetherton** [comment]
> That could get forgotten easily if there is no trace of them in the top pom. WDYT?

Ok - fine with me to keep them in the root pom.

**Pull request merged**
