### PR TITLE
Fix #6 Rename packages from io.quarkus.camel to org.apache.camel.quarkus

### LINKED ISSUE #6: Initial source code - Package names
The root java package name should be renamed to

- org.apache.camel.quarkus

### PR DESCRIPTION
**Pull request by ppalaga**
The current PR contains only the easy part. In particular, it is not renaming packages in /src/test and in integration test projects. Renaming those leads to strange errors that I propose to investigate separately. Merging the easy part quickly prevents potential conflicts because this is a big change affecting the majority of files.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@ppalaga can you please open an issue with the error ?

**Comment by ppalaga** [comment]
> @ppalaga can you please open an issue with the error ?

Done: https://github.com/apache/camel-quarkus/issues/24

**Comment by lburgazzoli** [comment]
Adding WIP for a while waiting to see if can solve #24

**Comment by davsclaus** [comment]
LGTM, lets merge it, thanks @ppalaga

**Comment by oscerd** [comment]
+1

**Pull request merged**
