### PR TITLE
Upgrade to Camel 3.9.0

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Comment by ppalaga** [comment]
Does the "Disable doc xref checks as there is no camel-3.9.x branch yet" commit still have to be there?

**Comment by jamesnetherton** [comment]
> Does the "Disable doc xref checks as there is no camel-3.9.x branch yet" commit still have to be there?

Yes, that condition is still true.

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Just a comment: aws-xray is still there in 3.9.0

**Comment by jamesnetherton** [comment]
> Just a comment: aws-xray is still there in 3.9.0

Yeah that's my fault. I need to redo the PR anyway so I can try to restore it.

**Pull request closed without merging**
