### PR TITLE
Fix #1037 to support the quarkus command mode

### LINKED ISSUE #1037: Support Quarkus command mode
https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/command-mode-reference.adoc

camel-main supports giving some arguments from the command line. i.e. hoe many messages to wait before to shut down so it would be nice if we can optionally support Quarkus' command mode

### PR DESCRIPTION
**Pull request by zhfeng**
- introduce the CamelBootstrap
- refactor the core extension to do bootstrap
- next will add a "main" bootstrap extension to override the ```assembler``` which should be started in the QuarkusApplication main method by using the camel-main

### CODE REVIEW

**Comment by zhfeng** [comment]
@lburgazzoli  I made these changes related to https://github.com/apache/camel-quarkus/issues/1037, can you take a look in advance ?

**Comment by lburgazzoli** [comment]
@zhfeng I will have a look soon but what's your plan here ? I mean are you gogin to implemnent only the support for the quarkus command mode or the whole `bootsrap` refactor I've proposed ?

btw, I've opened a new issue https://github.com/apache/camel-quarkus/issues/1128

**Comment by zhfeng** [comment]
yeah, I'd like to do the refactor of bootstrap at first and then implement the "main" bootstrap to support the quarkus command mode.

**Comment by lburgazzoli** [comment]
It is a little bit hard to review the PR in the current state as in example, you have removed the flag to turn on/off without providing an alternative

**Comment by zhfeng** [comment]
Oh, yeah, maybe we can provide an "empty" extension to do nothing about bootstrap ? such as
```
@BuildStep
public CamelBoostrapBuildItem empty() {
       return new CamelBootstrapBuildItem(new RuntimeValue<>(new CamelBootstrap() {
                @Override
                public void start() {              
                }

                @Override
                public void stop() {
                }
            }));
}
```
any other idea ?

**Comment by ppalaga** [comment]
I think we should properly discuss the desired goals and design in https://github.com/apache/camel-quarkus/issues/1128 before proceeding here.

**Comment by zhfeng** [comment]
I withdraw this PR and need to work on the https://github.com/apache/camel-quarkus/issues/1128 at first.

**Pull request closed without merging**
