### PR TITLE
test - Define routes in YAML DSL using beans declared in Java

### PR DESCRIPTION
**Pull request by AnetaCadova**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
Thanks @AnetaCadova. Please can you change the target branch to `main` and I will cherry-pick the commit over to 2.13.x after it's merged.

**Comment by AnetaCadova** [comment]
@jamesnetherton I created this branch from 2.13.x, so I'd prefer to keep this one as it is and create a new PR to the main if it's ok for you. Sorry, next time I'll checkout from the main branch.

**Comment by AnetaCadova** [comment]
@jamesnetherton I created the backport to the main branch here: https://github.com/apache/camel-quarkus/pull/4577

**Review by aldettinger — APPROVED** [review]
LGTM. The error message in examples `error: invalid target release: 17` looks unrelated to me.

**Review by zhfeng — APPROVED** [review]

**Comment by zbendhiba** [comment]
Thanks @AnetaCadova  for your contribution!

**Pull request merged**
