### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by erayerdem**

### CODE REVIEW

**Review by jamesnetherton — CHANGES_REQUESTED** [review]
You need to rebase against the `main` branch instead of `2.6.x`.

**Comment by aldettinger** [comment]
@erayerdem Many thanks for contributions. The freemarker configuration [comes from quarkus-freemarker](https://github.com/apache/camel-quarkus/blob/main/extensions/freemarker/runtime/src/main/doc/configuration.adoc#quarkiverse-freemarker-and-its-configuration). As such, one should use the `quarkus.freemarker.includes` property to include the templates as shown in [integration tests](https://github.com/apache/camel-quarkus/blob/main/integration-tests/freemarker/src/main/resources/application.properties).

So, the section dealing with including native resources in camel-quarkus-freemarker documentation may not be needed anymore. quarkus-freemarker [is embedding all templates in the native executable](https://github.com/quarkiverse/quarkus-freemarker/blob/master/deployment/src/main/java/io/quarkiverse/freemarker/deployment/FreemarkerProcessor.java#L106).

That said, are you ok with closing this PR in favor of #3545 ?

**Comment by erayerdem** [comment]
Yes you can thanks 😀

**Comment by aldettinger** [comment]
Closing in favor of https://github.com/apache/camel-quarkus/pull/3545.

**Pull request closed without merging**
