### PR TITLE
Management JVM support

### LINKED ISSUE #1564: make camel-management a camel-quarkus extension.
In a plain and simple Maven/Camel 3 project, I can - with a dependency of camel-management - easily use hawtio and jolokai to monitor or debug Camel routes. I've tried the same with a simple Quarkus project, but there is no extension for camel-management, yet.

If there are no other ways to access/monitor Camel routs via jolokai and hawtio (that I do not know of, yet), then I'd be happy to see camel-management as an extension, too.

### PR DESCRIPTION
**Pull request by jamesnetherton**
Fixes #1564

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by ppalaga — APPROVED** [review]
Looks good, thanks!

**Comment by ppalaga** [comment]
Shouldn't we make it more explicit (e.g. in `limitations.adoc`) that this extension will stay JVM only due to limitations inherent to GraalVM?

**Comment by jamesnetherton** [comment]
> Shouldn't we make it more explicit (e.g. in `limitations.adoc`) that this extension will stay JVM only due to limitations inherent to GraalVM?

Yes, I was thinking along similar lines so I can add some notes about that.

**Comment by jamesnetherton** [comment]
Latest commit adds `limitations.adoc`.

**Pull request merged**
