### PR TITLE
Provide SBOM for Camel-Quarkus project

### LINKED ISSUE #4459: Provide SBOM for Camel-Quarkus project
Like we have on Camel we could add a SBOM generation profile in camel-quarkus too:

https://github.com/apache/camel/blob/main/pom.xml#L848-L891

### PR DESCRIPTION
**Pull request by oscerd**
Signed-off-by: Andrea Cosentino <ancosen@gmail.com>

Fixes #4459 

So this is a first iteration for having a SBOM for Camel-Quarkus.

Generation time on a free repository: 41 minutes for me.
SBOM dimensions: Around 8 MB

My proposal:

- In Camel we have a github action running every Sunday at 14:30. The action will rebase on particular branch "regen_bot_sbom", run the sbom generation, commit and create a PR with the SBOM updated.
- I can setup something like this if it's fine for you

For the moment, the camel-sbom on Camel and camel-quarkus-sbom are not part of release process, so there want be an artifact for them. They are descriptors more or less.

Let me know what you think and if you have proposals/doubts/discussions. Thank you

### CODE REVIEW

**Comment by jamesnetherton** [comment]
I'm fine with it in principal. Lets see what @ppalaga thinks.

Can we add the `camel-quarkus-sbom` directory to the list of `path-ignores`. There's no need to run a CI cycle for changes in those files, right?

https://github.com/apache/camel-quarkus/blob/main/.github/workflows/ci-build.yaml#L27

**Comment by aldettinger** [comment]
No strong advice. I would see sbom as becoming more and more important, so :+1: 
On a side note, I wonder how git would handle such large files 8Mb, hundred of thousand lines, each week. Seems it's working on Camel side.

As a last note, I wonder whether there would be something special linked to Quarkus. Like are deployment items to be included in sbom ? I would say yes... still now strong advice.

**Comment by oscerd** [comment]
> I'm fine with it in principal. Lets see what @ppalaga thinks.
> 
> Can we add the `camel-quarkus-sbom` directory to the list of `path-ignores`. There's no need to run a CI cycle for changes in those files, right?

No need for run a CI cycle for them, no. The idea is more or  less this: https://github.com/apache/camel-spring-boot/blob/main/.github/workflows/generate-sbom-main.yml

Having a GH action doing this once a week and open a PR with the regenerated SBOMs.

> 
> https://github.com/apache/camel-quarkus/blob/main/.github/workflows/ci-build.yaml#L27

I'll update the PR

**Comment by oscerd** [comment]
> No strong advice. I would see sbom as becoming more and more important, so +1 On a side note, I wonder how git would handle such large files 8Mb, hundred of thousand lines, each week. Seems it's working on Camel side.
> 
> As a last note, I wonder whether there would be something special linked to Quarkus. Like are deployment items to be included in sbom ? I would say yes... still now strong advice.

Everything in the modules should be part of the generated aggregated SBOM, so they should be there.

**Review by ppalaga — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
