### PR TITLE
DebeziumMongodbTest skipped tests #3213

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/apache/camel-quarkus/issues/3213

Problem was caused by https://github.com/quarkusio/quarkus/pull/16748/files, which made some of the test disabled forever. I refactored the way how tests are disabled, using `ConfigProvider.getConfig()`.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by aldettinger** [comment]
@JiriOndrusek Not sure I get it. Shouldn't we fail when the mySql driver is not there or the Ms SQL EULA has not accepted ?

I see it like they are part of the valid test setup, but maybe I'm missing something there ?

**Comment by JiriOndrusek** [comment]
@aldettinger Original behavior was, that if driver is missing or EULA is not accepted, those tests will be skipped. It makes sense, because on CI we won't have driver or acceptance of EULA. This PR doesn't change the behavior, only fixes issues. (because without this fix, mysql, mssql and mongo will be skipped always).

**Review by aldettinger — APPROVED** [review]
Thanks, it's clearer now. The failing test on CI seems unrelated. Well done @JiriOndrusek :)

**Comment by ppalaga** [comment]
Ups, it looks like this PR got forgotten for some reason. Could you please rebase @JiriOndrusek ?

**Comment by JiriOndrusek** [comment]
@ppalaga rebased

**Comment by ppalaga** [comment]
@JiriOndrusek could you please have a look at the failure and assess whether they may be caused by this change?

**Comment by JiriOndrusek** [comment]
This PR modifies only 3 test files inside `inegration-tests/debezium` Failure is caused by `JmsArtemisTest`.
```
 JmsArtemisTest>AbstractMessagingTest.testResequence:140 1 expectation failed.
```
I don't see a possible connection to the changed files.

**Pull request merged**
