### PR TITLE
Upgrade to 3.20

### PR DESCRIPTION
**Pull request by JiriOndrusek**
Testing PR with upgrade to camel 3.20 using staging repo.
Do not merge!

Replaces https://github.com/apache/camel-quarkus/pull/4347

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by zbendhiba** [comment]
@JiriOndrusek Can you please do a full `mvn clean install -DskipTests` to regenerate the flattened boms ?

**Comment by JiriOndrusek** [comment]
@zbendhiba  Already amended

**Comment by JiriOndrusek** [comment]
Synchronization of version was missing.

**Comment by ppalaga** [comment]
@JiriOndrusek could you please cherry pick https://github.com/apache/camel-quarkus/commit/3051e9e923ebcf967f8a621aa4a5407d7b1ab54a into this Camel 3.20 branch? see https://github.com/apache/camel-quarkus/issues/4246#issuecomment-1359001025

**Comment by zbendhiba** [comment]
Thanks @ppalaga @JiriOndrusek

**Comment by JiriOndrusek** [comment]
@ppalaga @jamesnetherton 
@zbendhiba pointed out that we need to have kubernetes native support for Quarkus 2.x and Camel 3.20
Therefore it would be better  to solve https://github.com/apache/camel-quarkus/issues/4357 before merging this PR.

**Comment by JiriOndrusek** [comment]
PR is complete, can be squashed and merged.

**Comment by zbendhiba** [comment]
Hello @JiriOndrusek, yes rebase please, and we'll do a final review. It's time to merge Camel 3.20

**Comment by jamesnetherton** [comment]
Shall we get this merged now to avoid having to keep doing rebases?

Upgrading later to 3.20.1 should be trivial.

**Review by zbendhiba — APPROVED** [review]

**Comment by zbendhiba** [comment]
@jamesnetherton +1

**Comment by zbendhiba** [comment]
we need to squash while merging

**Pull request merged**
