### PR TITLE
 fix hazelcast integration-test failed in native mode(On Mac) #2719

### PR DESCRIPTION
**Pull request by ffang**

### CODE REVIEW

**Comment by ppalaga** [comment]
Thanks @ffang , let's see if this is going to pass on Linux

**Review by zbendhiba — APPROVED** [review]

**Review by ppalaga — APPROVED** [review]

**Comment by ppalaga** [comment]
I am OK with merging this as a temporary workaround. A long term solution should be IMO that the profile is added indeally in hazelcast-quarkus-client, or in camel-quarkus-hazelcast. Could you please file a followup issue in camel Quarkus and ideally also in hazelcast-quarkus-client and paste the URLs into a comment around the new profile?

**Comment by ffang** [comment]
> I am OK with merging this as a temporary workaround. A long term solution should be IMO that the profile is added indeally in hazelcast-quarkus-client, or in camel-quarkus-hazelcast. Could you please file a followup issue in camel Quarkus and ideally also in hazelcast-quarkus-client and paste the URLs into a comment around the new profile?

@ppalaga , sure.
Raised
https://github.com/apache/camel-quarkus/issues/2800
and 
https://github.com/hazelcast/quarkus-hazelcast-client/issues/189
separately

**Comment by ffang** [comment]
squashed here
https://github.com/apache/camel-quarkus/pull/2789/commits/16d4e4fe686c9bc61befa0926bf48c37ab17646a

**Comment by ffang** [comment]
we have green CI build so I will merge it

**Pull request merged**
