### PR TITLE
Fix usage of incorrect @Produces annotation

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by aldettinger** [comment]
Looks good to me. One question however, @Unremovable are useless because this is managed by camel-quarkus-core ?

**Comment by jamesnetherton** [comment]
> Looks good to me. One question however, @Unremovable are useless because this is managed by camel-quarkus-core ?

AFAIK - if the bean has an explicit name, it's unremovable. There is some logic in core that I think is supposed to make component beans unremovable, but I'm not sure if it's working. Hence how I stumbled on this issue while experimenting.

**Review by aldettinger — APPROVED** [review]
ok, thanks for sharing.

**Comment by ppalaga** [comment]
Oh, I see it was `@javax.ws.rs.Produces`. I guess `@javax.enterprise.inject.Produces` would be correct but superfluous in this situation?

**Pull request merged**
