### PR TITLE
Camel master update

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@ppalaga there are some build failures

**Comment by ppalaga** [comment]
> @ppalaga there are some build failures

Yeah, there is never enough fun with remote snapshots. The Java 12 job was perhaps unlucky enough to get a newer snapshot that added a method to AbstractCamelContext. Because otherwise Java 8 should have failed too. Once we use the same cache for java 8 11 and 12 this should not happen anymore.

**Comment by ppalaga** [comment]
ConfigurerResolver adapts to the newest changes in Camel

**Comment by ppalaga** [comment]
Failed due to transfer problems again. Let's rebase on top of master once https://github.com/apache/camel-quarkus/pull/705 is merged and see if the transfer problems go away.

**Comment by jamesnetherton** [comment]
@ppalaga #705 is merged. Can we rebase this one and try again?

**Comment by ppalaga** [comment]
One more fix in e974195

**Comment by ppalaga** [comment]
There is never enough fun with snapshots. The CI apparently uses a different snapshot than my machine. There is no way to figure out which one is used by the CI and there is no way to force the two machines to use the same snapshot. What do you guys do in situations like this?

**Comment by jamesnetherton** [comment]
The error is reproducible by slurping down the latest SNAPSHOTs. E.g build with `-U`.

But you're right, it is a bit tricky to manage when the target keeps on moving.

**Comment by lburgazzoli** [comment]
> But you're right, it is a bit tricky to manage when the target keeps on moving.

it is the funny part

**Comment by ppalaga** [comment]
Updated what I wanted, let's wait for the next random error.

**Pull request merged**
