### PR TITLE
Splunk: tests are failing after the upgrade of Splunk in Camel #4085

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/apache/camel-quarkus/issues/4085

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by aldettinger** [comment]
It looks the upgrade in camel is linked to TLS version. Are we covering TLS in those splunk tests ?

**Comment by JiriOndrusek** [comment]
This fix is meant to fix the failure int the current tests, which was caused by the upgrade.
I looked into the test and ssl is turned off  (see [this line](https://github.com/apache/camel-quarkus/blob/main/integration-tests/splunk/src/test/java/org/apache/camel/quarkus/component/splunk/it/SplunkTestResource.java#L54).

I'll create another ticket to extend the coverage of the splunk extension by covering TLD.

**Review by aldettinger — APPROVED** [review]
Ok, many thanks for double checking @JiriOndrusek :+1: . So, I see the coverage is the same than before and that's good.

Concerning the need to create another ticket for TLS, maybe it makes sense as TLS is handled  a bit special in native mode if I recall correctly.

**Comment by jamesnetherton** [comment]
@JiriOndrusek can we redo this one with just the Splunk test changes on `main`?

**Comment by JiriOndrusek** [comment]
Can be merged.

**Pull request merged**
