### PR TITLE
Revert "Temporarily disable dataformat integration tests due to #4662"

### LINKED ISSUE #4662: camel-quarkus-snakeyaml not compatible with Quarkus 3.0.0.Alpha6
SnakeYAML has been upgraded to 2.x:

```
2023-03-15T16:52:20.6319162Z Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
2023-03-15T16:52:20.6319978Z 	at org.apache.camel.component.snakeyaml.SnakeYAMLDataFormat.defaultRepresenter(SnakeYAMLDataFormat.java:419)
2023-03-15T16:52:20.6320884Z 	at org.apache.camel.component.snakeyaml.SnakeYAMLDataFormat.getYaml(SnakeYAMLDataFormat.java:150)
2023-03-15T16:52:20.6321994Z 	at org.apache.camel.component.snakeyaml.SnakeYAMLDataFormat.marshal(SnakeYAMLDataFormat.java:114)
2023-03-15T16:52:20.6322867Z 	at org.apache.camel.support.processor.MarshalProcessor.process(MarshalProcessor.java:64)
2023-03-15T16:52:20.6323574Z 	... 48 more
```

We need:

https://issues.apache.org/jira/browse/CAMEL-19130

I will disable the affected tests for now.

### PR DESCRIPTION
**Pull request by zbendhiba**
This reverts commit 18159898d10df121db50bf35296b5043c76dbf8e.

Fixes #4662

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by aldettinger — APPROVED** [review]

**Comment by zbendhiba** [comment]
@JiriOndrusek Could you please advise if we can merge this?

**Comment by JiriOndrusek** [comment]
@zbendhiba I'd suggest to rebase on the current 'camel-main'. I can not guarantee, that `camel-main` is flawless at this moment. (The numner of failing tests should be low and as you can see, there is a lot of commits in camel-main for the last few days.)

**Comment by zbendhiba** [comment]
okay let me rebase this. Many thanks

**Comment by JiriOndrusek** [comment]
Once rebased, we can compare results from this morning (https://github.com/apache/camel-quarkus/actions/runs/4551291603/jobs/8025189242) with this PR, and if there is no new failing test, we can merge.

**Comment by JiriOndrusek** [comment]
I checked all failures and this PR did not cause any new one (as you can see, the only affected test extension `dataformat` is successful). I think that PR could be merged.

**Review by JiriOndrusek — APPROVED** [review]

**Comment by zbendhiba** [comment]
Many thanks @JiriOndrusek

**Pull request merged**
