### PR TITLE
Documentation for 'Fop native failures due to pdfbox 3 upgrade' #1

### LINKED ISSUE #6743: Documentation for issue 5244 : Fop native failures due to pdfbox 3 upgrade
### Description

After upgrading to pdfbox 3, it seems the native build is not working anymore, as for the issues:  

[camel-quarkus : Fop native failures due to pdfbox 3 upgrade #5244](https://github.com/apache/camel-quarkus/issues/5244)

*Maybe it should be reported in documentation?*

I suggest that because at first I read the [camel-quarkus-fop documentation](https://camel.apache.org/camel-quarkus/next/reference/extensions/fop.html) and it seemed native profile was available.

Only after i tried and it did not work a searched for the open issue where it is stated otherwise : 
<https://github.com/apache/camel-quarkus/issues/5244>

As it is open since more than one year, maybe the fact should be noted in the limitations.

The pull request is on the [came-quarkus-fop] documentation as I found the issue when trying to use it.
Here is a [reproducer](https://github.com/fugerit79/camel-quarkus-examples/blob/1-quarkus-camel-fop-example/rest-json/NATIVE.md)

Do you agree?

Thanks in advance.

### PR DESCRIPTION
**Pull request by fugerit79**
fugerit79/camel-quarkus/issues/1
#5244
#5234

This PR's goal is to 
Fix #6743 

And document on [camel-quarkus-fop limitations page](https://camel.apache.org/camel-quarkus/next/reference/extensions/fop.html) the fact that native profile is currenlty disabled.

[X] An issue should be filed for the change unless this is a trivial change (fixing a typo or similar). One issue should ideally be fixed by not more than one commit and the other way round, each commit should fix just one issue, without pulling in other changes.
[X] Each commit in the pull request should have a meaningful and properly spelled subject line and body. Copying the title of the associated issue is typically enough. Please include the issue number in the commit message prefixed by #.
[X] The pull request description should explain what the pull request does, how, and why. If the info is available in the associated issue or some other external document, a link is enough.
[X] Phrases like Fix #<issueNumber> or Fixes #<issueNumber> will auto-close the named issue upon merging the pull request. Using them is typically a good idea.
[ ] Please run mvn process-resources -Pformat (and amend the changes if necessary) before sending the pull request.
[X] Contributor guide is your good friend: https://camel.apache.org/camel-quarkus/latest/contributor-guide.html

### CODE REVIEW

**Comment by zhfeng** [comment]
Thanks @fugerit79 - can you run the following command locally to regen the docs module as well.
```
./mvnw -f extensions/fop/runtime/pom.xml clean install
```

**Comment by fugerit79** [comment]
Thanks @zhfeng , the docs module has been generated.

Is there anything else I can do?

**Comment by jamesnetherton** [comment]
This may actually not be needed in the next release. FOP in Camel 4.9.0 will use pdfbox 3.x.

**Comment by fugerit79** [comment]
@jamesnetherton as you think, but I lost some time before understanding why the native profile was not working.
Is there any due date for the release? And are we sure the native profile will work again for camel-quarkus-fop?

If there are no proof that the native build will work again for sure, I would rather update the documentation and then update it again.

So I guess would better to document the issue right now.

**Comment by jamesnetherton** [comment]
> And are we sure the native profile will work again for camel-quarkus-fop

I need to investigate it. But I don't see why it can't be made to work when we have the correct pdfbox version.

Anyway, I'll this for now until it's fixed.

**Review by jamesnetherton — APPROVED** [review]

**Pull request merged**
