### PR TITLE
Laveraging quarkus-security

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/apache/camel-quarkus/issues/2005

Quarkus can only  register boucyCastleProvider in current state. So I used it instead of our code and removed duplicate code (which exists in quarkus).

### CODE REVIEW

**Review by ppalaga — APPROVED** [review]
Looks good, thanks @JiriOndrusek!

@JiriOndrusek is there any potential to move some of the stuff from here to quarkus-security?

**Review by oscerd — APPROVED** [review]

**Comment by JiriOndrusek** [comment]
@ppalaga I'm thinking about moving some registrations for reflection into quarkus-security, because some similar stuff is already there (see https://github.com/quarkusio/quarkus/blob/main/extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java#L149)
But I'm not sure whether it will be accepted. If some of that code makes it into qaurkus, it should be removed from here...

**Comment by ppalaga** [comment]
> @ppalaga I'm thinking about moving some registrations for reflection into quarkus-security, because some similar stuff is already there (see https://github.com/quarkusio/quarkus/blob/main/extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java#L149)
> But I'm not sure whether it will be accepted. If some of that code makes it into qaurkus, it should be removed from here...

+1, could you please file an issue on our side so that we don't forget about that?

**Comment by JiriOndrusek** [comment]
Issue is created as https://github.com/apache/camel-quarkus/issues/2922

**Pull request merged**
