### PR TITLE
WIP: Add velocity extension #837

### PR DESCRIPTION
**Pull request by dc2tom**
Adding so @ppalaga can review if any of this is useful for him

### CODE REVIEW

**Comment by ppalaga** [comment]
Perfect, thanks for sharing! I can take it over, if you do not have time to finish it?

**Comment by dc2tom** [comment]
> Perfect, thanks for sharing! I can take it over, if you do not have time to finish it?

Feel free :) Glad I could at least help out a little

**Comment by JiriOndrusek** [comment]
I've created a new PR with velocity native extension - https://github.com/apache/camel-quarkus/pull/1804
@dc2tom you can look into my PR and close this one, if you agree with it.

**Comment by dc2tom** [comment]
Thanks - as commented on your own PR I'd just suggest you port a few more tests over to cover more use cases . happy to close this one.

**Pull request closed without merging**
