### PR TITLE
Upgrade Camel to 3.13.0

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Review by zbendhiba — APPROVED** [review]

**Comment by jamesnetherton** [comment]
@djencks There's a mountain of xref check failures:

https://github.com/apache/camel-quarkus/runs/4197965398?check_suite_focus=true

**Comment by jamesnetherton** [comment]
The failure in the examples build is expected. I'll fix it up over at `camel-quarkus-examples` once this PR is merged.

**Comment by djencks** [comment]
The xref failures are because the referenced 3.13.x branches of camel and camel-spring-boot haven't been updated to indicate they are 3.13.x yet. (I think). Keeping these partial-build playbooks up to date is beyond my organizational abilities, we need something else.

Are the camel-quarkus changes needed for an upgrade something that a camel-quarkus expert needs to do?  If not then we should add the extra steps to the release guide (see https://github.com/apache/camel/pull/6436).

If not then we should make the website release more asynchronous by leaving the old version of camel/camel-spring-boot/camel-karaf on the website until subprojects including camel-quarkus can update themselves.  That would also reduce problems such as this xref one, so maybe we should do that anyway.

**Comment by jamesnetherton** [comment]
> Are the camel-quarkus changes needed for an upgrade something that a camel-quarkus expert needs to do?

For a major / minor version upgrade, yes.

We can't bump the Camel version property and expect everything to work. We have to adapt the project to whatever API changes etc have been made in each new Camel release. We actually do this continuously on our `camel-main` branch.

**Comment by djencks** [comment]
For the camel-quarkus main branch that seems fine to do since it isn't released so no one should be using it for anything but development.  However, this seems like  a problem for the released branch, currently 2.4.x, which I've proposed modifying in https://github.com/apache/camel-quarkus/pull/3298.  Either the documentation is going to point to a different version than the software actually supports or you'll have to release a new camel-quarkus 2.4.x related to the new main camel version.  Do you do that?

Both of the following seem like reasonable strategies to me:
- Don't ever update the related camel version (e.g. 3.12.x) of a release camel-quarkus version, and keep the referenced camel branch docs around until the camel-quarkus version is superseded and disappears.
- Keep the related camel version docs around long enough for an update release of the released camel-quarkus, e.g. moving 2.4.x from 3.12 to 3.13.

In any case, it's clear to me that dropping the old main camel docs needs to happen in a separate step from adding the new version, giving everyone time to catch up.  I'll change the instructions PR and my playbook PR :-)

**Comment by djencks** [comment]
I've changed the instructions and my playbook PR to use the asynchronous process I outlined.  So, this PR should wait until step one is complete: it no longer breaks the website because the 3.12.x docs will remain until camel-quarkus has time to adapt.  Furthermore, the xrefs in this PR should resolve once my PRs are merged.

**Comment by jamesnetherton** [comment]
> once my PRs are merged

Please can you provide links to those PRs?

We plan to cut a new release later this week. I'd like to get this PR merged ASAP and not leave it dangling for too long.

**Review by aldettinger — APPROVED** [review]

**Comment by djencks** [comment]
The PRs holding up 3.13. and thus this one are

https://github.com/apache/camel-website/pull/669 and those listed there

https://github.com/apache/camel-website/pull/671

It's possible to reorder them but I worry about losing parts if I do so.

**Comment by djencks** [comment]
3.13.x is now in the website, so you should be able to successfully build the website with these changes.

**Comment by jamesnetherton** [comment]
@djencks docs build still fails. This time with multiple errors lilke:

```json
{
  "level": "warn",
  "time": 1637049672725,
  "name": "asciidoctor",
  "file": {
    "path": "docs/components/modules/ROOT/pages/timer-component.adoc"
  },
  "source": {
    "url": "https://github.com/apache/camel.git",
    "refname": "camel-3.13.x",
    "startPath": "docs/components"
  },
  "msg": {
    "msg": "Target spring-boot:example$json/timer.json not found",
    "useId": 5,
    "jsonpath": "jsonpathcount$"
  }
}
```

https://github.com/apache/camel-quarkus/runs/4221838688?check_suite_focus=true

**Comment by jamesnetherton** [comment]
> I guess I can make a PR against this branch? 

Yes, just clone this branch and any commits you add will be added to this PR.

> I think the 2.4.x branch also needs some fixes, is #3298 OK for that?

TBH it's not clear to me why we need to update old release branches. 2.4.x was released with Camel 3.12, there's not going to be another release from that branch, so I'm not sure whether (conceptually) it makes any sense bumping the Camel version.

As a compromise we could maybe introduce a new Maven property for the docs version. That'd allow the Camel version used by the project and the version of the Camel docs to be updated independently.

**Comment by djencks** [comment]
I still don't understand the nature of the working relationship between cq code and main camel code: if there is one, I'd expect changing the camel version referred to by cq 2.4.x would not be appropriate.

Camel-quarkus 2.4.x docs refer to the camel 3.12.x documentation. 3.12.x is not LTS, so it's about to disappear from the website without a change in policy.  Do you want to drop cq 2.4.x from the website also?

A couple months ago this didn't show up as a problem because the released cq docs branch was totally broken, not showing any extensions at all.  Apparently only I noticed...

I can think of a couple of changed policies that might work...

1. Release cq branches use the latest LTS camel branch. The main camel LTS branch is likely to stick around longer than the cq branch.  This might give an opportunity to have LTS cq branches as well, I don't know if that's desirable.
2. We keep all the non-LTS branches referred to by subprojects around as long as they are referred to.  This would mean that, instead of dropping 3.12.x later this week, we keep it at least until the next cq release, which will depend on 3.13.x.

**Comment by jamesnetherton** [comment]
> Camel-quarkus 2.4.x docs refer to the camel 3.12.x documentation. 3.12.x is not LTS, so it's about to disappear from the website without a change in policy. Do you want to drop cq 2.4.x from the website also?

We can drop 2.4.x when CQ 2.5.0 is released.

> We keep all the non-LTS branches referred to by subprojects around as long as they are referred to. This would mean that, instead of dropping 3.12.x later this week, we keep it at least until the next cq release, which will depend on 3.13.x.

That seems the most logical option (to me).

**Pull request merged**
