### PR TITLE
Add FTP extension

### LINKED ISSUE #463: Create a Camel FTP extension

### PR DESCRIPTION
**Pull request by jamesnetherton**
fixes #463

### CODE REVIEW

**Comment by lburgazzoli** [comment]
ok to test

**Comment by jamesnetherton** [comment]
Just realised I need to fix up the `<firstVersion>` property.

**Comment by jamesnetherton** [comment]
Can anyone else replicate this test failure in native mode? It's working fine for me.

**Comment by lburgazzoli** [comment]
I think you may need to declare that you need ssl, like https://github.com/apache/camel-quarkus/blob/master/extensions/aws-s3/deployment/src/main/java/org/apache/camel/quarkus/component/aws/s3/deployment/AwsS3Processor.java#L59

**Comment by jamesnetherton** [comment]
ok to test

**Comment by lburgazzoli** [comment]
mmh, does not fails for me neither but still failing on jenkins... maybe something caused by the oracle jdk vs openjdk ?

**Comment by jamesnetherton** [comment]
Yes, it's weird. I tested with the same JDK version Jenkins uses and it still passes.

**Comment by lburgazzoli** [comment]
There’s an open issue here: https://github.com/quarkusio/quarkus/issues/2125

**Comment by jamesnetherton** [comment]
Wondering if the Jenkins build environment is configured correctly?

If I unset `GRAALVM_HOME` locally I hit the same issue.

Maybe the other extensions that require native SSL support don't trigger the relevant code paths in their integration tests (AWS, Twitter & Salesforce tests don't run at all). Hence why we perhaps haven't hit this before.

**Comment by lburgazzoli** [comment]
I think the main problem is that the code is built with docker but executed outside it, do you mind adding some notes to the linked issue or starting a conversation on zulip ?

**Comment by jamesnetherton** [comment]
ok to test

**Comment by davsclaus** [comment]
All is green, lets merge ? We can maybe mark this extension as preview

**Comment by jamesnetherton** [comment]
Lets merge as-is. 

IMO it works fine in native mode when the environment is configured correctly. I raised https://github.com/apache/camel-quarkus/issues/468 as a follow up issue.

**Pull request merged**
