### PR TITLE
[2.7.x] Upgrade to Camel 3.14.4

### PR DESCRIPTION
**Pull request by ppalaga**
The last commit needs to be removed/reverted before merging

### CODE REVIEW

**Comment by aldettinger** [comment]
The failure in group-09 seems unrelated.
Note sure about the failure in examples: `java.lang.ClassNotFoundException: com.jcraft.jsch.jce.HMACSHA256ETM`

**Comment by zhfeng** [comment]
@ppalaga @aldettinger I think we need to upgrade `quarkiverse-jsch.version` to `2.0.0` which includes the fix https://github.com/quarkiverse/quarkus-jsch/commit/ee7b71beeadfb7a93ad1265f1b13d6012c3100ff

**Review by aldettinger — APPROVED** [review]
Ah, ok should be good now.

**Comment by zhfeng** [comment]
@ppalaga we should still wait for camel `3.14.4` releasing ?

**Comment by ppalaga** [comment]
> we should still wait for camel 3.14.4 releasing ?

We can release (create our staging repo) against the Camel 3.14.4 staging repo, open our vote and release our staging repo only after camel staging repo is released. We did something like that in the past .

**Pull request merged**
