### PR TITLE
Avoid overwriting the Qute json which breaks Camel K catalogs

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Comment by orpiske** [comment]
This should solve https://github.com/apache/camel-k-runtime/issues/677

**Comment by orpiske** [comment]
Without this, the catalog seems to generate its own bogus `qute.json`. Then, during camel-k-runtime build, it gets picked instead of the one available in camel-quarkus-qute-component jar.

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
@orpiske please can you rebase on the latest work from `main` as I committed a fix for the CI failure.

**Comment by orpiske** [comment]
> @orpiske please can you rebase on the latest work from `main` as I committed a fix for the CI failure.

Hello James, sure, I can do that. Just let me confirm I understand it correctly: you want me to rebase `camel-main` with the latest changes from `main`. Is that correct?

**Comment by jamesnetherton** [comment]
Ah, sorry. I missed that you were targeting `camel-main` with this change. Is there any reason to not have this work on `main`? I can rebase it over to `camel-main` once merged.

**Comment by orpiske** [comment]
> Ah, sorry. I missed that you were targeting `camel-main` with this change. Is there any reason to not have this work on `main`? I can rebase it over to `camel-main` once merged.

No worries. We can definitely have it there, now. When I started working on upgrading Camel K Runtime (around 5 days ago), main was still tracking Camel 3.9 and Quarkus 1.x. Let me close this PR and send it to main, instead.

**Pull request closed without merging**
