### PR TITLE
Upgrade to Camel 3.10.0 and Quarkus 2.0.0.Alpha3

### PR DESCRIPTION
**Pull request by ppalaga**
Most of the work done by @zbendhiba & @jamesnetherton (Thanks!)

I squashed commits where I thought it made sense. Any suggestions about that?

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
> I squashed commits where I thought it made sense. Any suggestions about that?

Personally I'd just squash everything into 1 commit, but I have no strong preference on it.

Is `quarkus.test.flat-class-path` still needed? I noticed Stuart did more classloader tweaks, so was wondering if it was no longer required.

**Comment by ppalaga** [comment]
> Is quarkus.test.flat-class-path still needed? I noticed Stuart did more classloader tweaks, so was wondering if it was no longer required.

Yes, it is fixed. Actually, I can remove both the workaround and its revert from the log and close the issue manually.

**Comment by jamesnetherton** [comment]
@ppalaga please can you fix up the validation errors?

**Comment by ppalaga** [comment]
> @ppalaga please can you fix up the validation errors?

Geez, my bad, I have sent a fix to Quarkus last week, but forgot to workaround it on our side :/

**Pull request merged**
