### PR TITLE
:memo: Set documentation version to  Camel Quarkus 2.5.x

### PR DESCRIPTION
**Pull request by zbendhiba**

### CODE REVIEW

**Comment by zbendhiba** [comment]
I wonder if this one works as this https://github.com/apache/camel-website/pull/691 not merged yet

**Review by jamesnetherton — APPROVED** [review]

**Comment by zbendhiba** [comment]
I fixed the `qute.json` file
But I'm skeptical that this could work. Every time I build the project, the antora.yaml file is updated. The version goes from **2.5.x** to **next**. So I'm expecting the `mvn install` to fail.

**Comment by jamesnetherton** [comment]
> The version goes from **2.5.x** to **next**.

Ah yeah the update script sees `SNAPSHOT` in the project version and will use `next`.

I think we should just merge this PR. It's pretty unlikely anyone is going to do a full build the 2.5.x anyway. We can fix up the antora update script and try to make it smarter later.

**Review by aldettinger — APPROVED** [review]

**Comment by djencks** [comment]
For 2.4.x I updated the groovy scripts to not update antora.yml: https://github.com/apache/camel-quarkus/commit/efda8ea4d5d29e0a9808187384f4c9627286284e

I'd recommend doing that here too.

**Comment by zbendhiba** [comment]
I don't know how we could address this in the release process. Is there a way to change automagically those files ?

**Comment by zbendhiba** [comment]
I guess I can merge this. Thanks for reviews

**Comment by djencks** [comment]
I couldn't think of an automated way of detecting a non-next branch.

Would it be possible for the release process to add a pom property saying "released" and the groovy script not update the Antora stuff on a released branch?

**Comment by ppalaga** [comment]
Could please somebody create an issue describing what should happen on release?

**Comment by zbendhiba** [comment]
@ppalaga Yes, I'd create one to explain all I did. on my TODO list

**Comment by ppalaga** [comment]
For the record, the issue is here: https://github.com/apache/camel-quarkus/issues/3350

**Pull request merged**
