### PR TITLE
Aws2  quarkus client ddb refactor

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/apache/camel-quarkus/issues/3236

Requires https://github.com/apache/camel-quarkus/pull/3458 to be merged (it contains the forst commit from this PR)

This commit refactores aws2-quarkus-client-ddb. With this change, module will copy sources from aws2-ddb module and won't duplicate them.
S3 module is fixed by the PR which contains the first commit.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by aldettinger** [comment]
I'm not sure whether this PR contains both ddb and S3 ? Shouldn't we merge #3458 first ? Or maybe rebase ?

**Comment by aldettinger** [comment]
I'm not sure whether this PR contains both ddb and S3 ? Shouldn't we merge #3458 first ? Or maybe rebase ?

**Comment by JiriOndrusek** [comment]
@aldettinger  Yes. https://github.com/apache/camel-quarkus/pull/3458 should be merged first. Hopefully there should not be needed any rebase of this PR, because the first commit is the same in both PRs.

I wrote that into the summary:
```
Requires #3458 to be merged (it contains the forst commit from this PR)
```

**Comment by aldettinger** [comment]
@JiriOndrusek I've merged the other PR and now this one has conflict. Could you please check ?

**Comment by JiriOndrusek** [comment]
I'll do it

**Comment by JiriOndrusek** [comment]
@aldettinger  it should be fixed. Eventhough I cherrypicked the second commitr from the original PR and there was no conflict. I'm not sure why it didn't work automatically

**Comment by aldettinger** [comment]
I don't know too. Let's have a successful CI build and merge this PR then. Thanks for fixing :+1:

**Pull request merged**
