### PR TITLE
Enable SSL for Azure extension #1269

### PR DESCRIPTION
**Pull request by galderz**
PR for https://github.com/apache/camel-quarkus/issues/1269. Replaces https://github.com/apache/camel-quarkus/pull/1272.

### CODE REVIEW

**Comment by galderz** [comment]
Shall I send a PR to quarkus in parallel to add Camel Azure to the list [here](https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/native-and-ssl.adoc)?

**Comment by jamesnetherton** [comment]
> Shall I send a PR to quarkus in parallel to add Camel Azure to the list [here](https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/native-and-ssl.adoc)?

@ppalaga WDYT? There's actually a few other camel extensions that enable SSL support. Not sure if we should document that over on the Quarkus side or whether it'd be better to do it exclusively in our own documentation (probably the better option IMO).

**Comment by ppalaga** [comment]
> > Shall I send a PR to quarkus in parallel to add Camel Azure to the list [here](https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/native-and-ssl.adoc)?
> 
> @ppalaga WDYT? There's actually a few other camel extensions that enable SSL support. Not sure if we should document that over on the Quarkus side or whether it'd be better to do it exclusively in our own documentation (probably the better option IMO).

Yeah, I think syncing to Quarkus docs is not sustainable. The question is how detailed we should document it on our side. I have created https://github.com/apache/camel-quarkus/issues/1300 Let's discuss there so that we do not block this PR.

**Comment by galderz** [comment]
Thanks all!

**Pull request merged**
