### PR TITLE
Use azure-sdk-bom instead of individual azure artifact versions

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
Not sure about the Camel side.

**Review by jamesnetherton — APPROVED** [review]

**Review by aldettinger — APPROVED** [review]
The failing test is highly likely unrelated.

**Comment by ppalaga** [comment]
> The failing test is highly likely unrelated.

Hm... I can reproduce the optaplanner test failure with these changes and I cannot reproduce it with master.

**Comment by ppalaga** [comment]
It passed with these changes when trying the second time.

**Comment by ppalaga** [comment]
OK, I see this older CI run where the same issue happened https://github.com/apache/camel-quarkus/runs/1963000106?check_suite_focus=true#step:9:1875 and it has been reported in the past https://github.com/apache/camel-quarkus/issues/2205

**Pull request merged**
