### PR TITLE
camel-quarkus-minio: quarkus.minio.url is not mandatory

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/apache/camel-quarkus/issues/2721

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
This will break any dependant project using quarkus extension as runtime. If I set the minio url at camel level in a kamelet I don't have to set the minio url as quarkus property.

**Comment by JiriOndrusek** [comment]
@oscerd I'm not sure if I understand. My fix is only setting property ''quarkus.minio.allow-empty" to true, which has no effect on cases, where minio client is initialized from quarkus properties:

- if all other quarkus minio parameters are null, no minio client will be created (without it, it would throw a validation exception)

From this perspective,  everything that worked before, would work after this fix. 
Only difference is in the case, where all quarkus parameters are null (url, server_secret and server_access) - case of kamelet - it wouldn't throw a validation exception, but return `null` as a client. Autowiring capability of the component then would use minio client from the context.

**Comment by JiriOndrusek** [comment]
Better explanation of `quarkus.minio.allow-empty` is - do not throw a validation exception but return `null` as a minio client (so it won't throw an exception during autowiring, if all parameters are `null`)

**Comment by oscerd** [comment]
The title was a bit misleading.. it looks like quarkus.minio.url is always mandatory, which should be wrong.

**Comment by JiriOndrusek** [comment]
Sorry, I didn't see this, I'll change title.

**Review by ppalaga — APPROVED** [review]

**Pull request merged**
