### PR TITLE
Upgrade to Quarkus 2.0.0.CR2

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
I think the gRPC integration will be broken. Here's the git diff that should fix it:

[grpc.txt](https://github.com/apache/camel-quarkus/files/6555060/grpc.txt)

**Comment by ppalaga** [comment]
> I think the gRPC integration will be broken. Here's the git diff that should fix it:
> 
> [grpc.txt](https://github.com/apache/camel-quarkus/files/6555060/grpc.txt)

Thanks, applied

**Comment by ppalaga** [comment]
I have filed a followup https://github.com/apache/camel-quarkus/issues/2689

**Comment by ppalaga** [comment]
I have analyzed the heap usage during the build and I have not found any single hog in the dumps (except for the CqCatalog held in the ThreadLocal ). It looks the heap naturally increases with the number of modules. So I chose to increase the heap from 3g to 4g for the initial-mvn-install job, keeping others on 3g.

**Pull request merged**
