### PR TITLE
Adapt to latest API changes

### PR DESCRIPTION
**Pull request by lburgazzoli**
Requires https://github.com/apache/camel/pull/5023

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by lburgazzoli** [comment]
@jamesnetherton @ppalaga I see this PR failing because of:

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (antora-xref-check) on project camel-quarkus-docs: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
2021-02-05T08:57:14.2334796Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (antora-xref-check) on project camel-quarkus-docs: Command execution failed.
```

Any clue ?

**Comment by jamesnetherton** [comment]
I think that failure is expected on the `camel-master` branch. Did you rebase from master? I added a commit so that the docs module is not run on `camel-master`.

**Comment by lburgazzoli** [comment]
let me rebase

**Review by davsclaus — APPROVED** [review]

**Comment by lburgazzoli** [comment]
@jamesnetherton @ppalaga as the failing jobs are related to docs, what about merging this PR and fix what's left as follow up ?

**Pull request merged**
