### PR TITLE
Add tests for #543

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
ok to test

**Comment by lburgazzoli** [comment]
We can but then we need to include the routes in the native image which is not yet done automatically, in general we should not assume that all the test have to run on the quarkus-platform

**Comment by ppalaga** [comment]
> We can but then we need to include the routes in the native image which is not yet done automatically

I'd vote for including the XML file in the native image via application.properties' for now:

```
quarkus.native.additional-build-args = -H:IncludeResources=my-routes.xml
```

Not sure this will work OOTB on the platform, but it is a bit more flexible than `-H:ResourceConfigurationFiles` recommended in the Quarkus docs. 

> in general we should not assume that all the test have to run on the quarkus-platform

I think we should assume that all our tests should run there unless we define a clear filtering strategy.

**Comment by lburgazzoli** [comment]
Peter, we already agreed that we need to create some consolidated test for the quarkus platform. T

**Comment by lburgazzoli** [comment]
xml is now included in the native image

**Comment by lburgazzoli** [comment]
ok to test

**Pull request merged**
