### PR TITLE
[2.13.x] Upgrade to quarkus-cxf 1.5.11 and other backports

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by ppalaga** [comment]
The failures related to a missing Sisu class are easy to fix. I am investigating the rest.

**Comment by ppalaga** [comment]
perfregression seems to be missing some backports. Adding those

**Comment by ppalaga** [comment]
Added back some more exclusions. Let's see.

**Comment by ppalaga** [comment]
>  we somehow need to alternate between GITHUB_REF_NAME and GITHUB_BASE_REF.

I did this:

```
          if [[ ${GITHUB_REF_NAME} =~ [0-9]+.[0-9]+.x || ${GITHUB_BASE_REF} =~ [0-9]+.[0-9]+.x ]]; then
```

We should port it to main if it succeeds.

**Comment by ppalaga** [comment]
> > we somehow need to alternate between GITHUB_REF_NAME and GITHUB_BASE_REF.
> 
> I did this:
> ```
>           if [[ ${GITHUB_REF_NAME} =~ [0-9]+.[0-9]+.x || ${GITHUB_BASE_REF} =~ [0-9]+.[0-9]+.x ]]; then
> ```

... and it did not work. Waiting for the native jobs to finish before fixing it with 

```
          if [[ ${GITHUB_REF_NAME} =~ [0-9]+.[0-9]+.x ]]; then
              EXAMPLES_BRANCH=${GITHUB_REF_NAME}
          elif [[ ${GITHUB_BASE_REF} =~ [0-9]+.[0-9]+.x ]]; then
              EXAMPLES_BRANCH=${GITHUB_BASE_REF}
          fi
```

**Review by davsclaus — APPROVED** [review]

**Pull request closed without merging**
