### PR TITLE
Upgrade to Quarkus CXF 2.6.1

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by jamesnetherton — APPROVED** [review]
Maybe also bump to `l2x6/calculator-ws:1.3` to align with QCXF?

**Review by aldettinger — APPROVED** [review]

**Comment by ppalaga** [comment]
> Maybe also bump to `l2x6/calculator-ws:1.3` to align with QCXF?

Good idea! Let me fix it.

**Comment by ppalaga** [comment]
6e19cb7: Upgraded to `l2x6/calculator-ws:1.3`

**Comment by jamesnetherton** [comment]
@ppalaga sorry, maybe my idea was a bad one because I think it has caused a test failure.

**Comment by jamesnetherton** [comment]
So I can get the 3.6.0 release started. I'll merge this & downgrade `calculator-ws` back to 1.2 (which I verified works ok locally).

I will try to follow up again later.

**Comment by ppalaga** [comment]
Ups, sorry about that and thanks for taking care!

**Pull request merged**
