### PR TITLE
Upgrade to Camel 4 and Quarkus 3

### PR DESCRIPTION
**Pull request by ppalaga**
Not perfect yet. The main objective for now is to figure out which tests are failing. ~~Needs a rebase.~~ Any feedback is welcome.

### CODE REVIEW

**Comment by aldettinger** [comment]
It looks like the ci should build with jdk 17 now :rocket:

**Comment by ppalaga** [comment]
> It looks like the ci should build with jdk 17 now rocket

Good point. I fully forgot about that. Let me fix it.

**Review by oscerd — APPROVED** [review]

**Comment by zbendhiba** [comment]
Many thanks @ppalaga !

**Comment by ppalaga** [comment]
Closing in favor of https://github.com/apache/camel-quarkus/pull/4504 whose camel-4 branch resides in apache/camel-quarkus so that it is easier to send PRs.

**Pull request closed without merging**
