### PR TITLE
Add support for MicroProfile Fault Tolerance

### LINKED ISSUE #1234: Add support for MicroProfile Fault Tolerance
https://camel.apache.org/components/latest/others/microprofile-fault-tolerance.html

### PR DESCRIPTION
**Pull request by jamesnetherton**
Fixes #1234

### CODE REVIEW

**Comment by jamesnetherton** [comment]
Database native test failures seems unrelated to this change. I've seen `java.net.BindException: Address already in use` pop up a few times recently. Wonder if its related to the problem mentioned in https://github.com/apache/camel/pull/3842 given that we copied the original implementation of `AvailablePortFinder`?

**Comment by lburgazzoli** [comment]
If we don't use the ranged method, it should not be the same thing, wonder if we should increase the range of ports the OS is allowed to allocate

**Comment by jamesnetherton** [comment]
Or I wonder if it is because we do not randomise `quarkus.http.test-ssl-port`? In the logs I see the default value being passed` -Dquarkus.http.ssl-port=8444`.

**Comment by lburgazzoli** [comment]
> Or I wonder if it is because we do not randomise `quarkus.http.test-ssl-port`? In the logs I see the default value being passed` -Dquarkus.http.ssl-port=8444`.

oh, yeah that could be

**Comment by jamesnetherton** [comment]
Merging as Kudu test failure is not unrelated.

**Pull request merged**
