### PR TITLE
Upgrade Quarkus to 2.13.0.CR1

### PR DESCRIPTION
**Pull request by jamesnetherton**
I could possibly drop commit be839b3 and cover the workaround with documentation. I added it to restore the capability to do autowiring of `DataSource` when only 1 named `DataSource` exists. It relates to [this Quarkus change](https://github.com/quarkusio/quarkus/commit/60f62f7283a62fe28d9282be78cec97ff2866120). Not sure what others think?

### CODE REVIEW

**Comment by zhfeng** [comment]
@jamesnetherton what is the workaround if there is only one named `DataSource`, users have to use it explictly and can not be Autowired?

**Comment by jamesnetherton** [comment]
> What is the workaround if there is only one named DataSource, users have to use it explictly and can not be Autowired?

Yes, exactly.

However, the JDBC example project test is failing. So it looks like I would need to rethink the fix for #4063 anyway.

I'm going to work around the JTA itest failure for now so we can merge the 2.13 upgrade.

**Comment by zhfeng** [comment]
yeah, I recall the issue https://github.com/apache/camel-quarkus/issues/4063. For the failing of jdbc example, is it possible to add some similar codes in jdbc extension https://github.com/apache/camel-quarkus/pull/4094/commits/be839b34d1260987bcf8fd0b43be70d5ef4b9bbf#diff-15efe9e17b3cf8bebde051bb494ba73ed69148b908162e1191492f6ad141cda2

**Review by zhfeng — APPROVED** [review]

**Comment by jamesnetherton** [comment]
I will fix up the failing JDBC example project test post merging this.

**Pull request merged**
