### PR TITLE
Improve google-bigquery test coverage #3949

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/apache/camel-quarkus/issues/3949, https://github.com/apache/camel-quarkus/issues/2057

Test `sqlCrudOperations` is disabled until Camel 18.3 is adopted (follow-up issue - https://github.com/apache/camel-quarkus/issues/4029)

Cover of various authentication approaches is covered by google-pubsub's ticket https://github.com/apache/camel-quarkus/issues/3970 and google-bigquery's ticket https://github.com/apache/camel-quarkus/issues/4033. 

Tiny part of the partitioning usecase is not covered by tests in this PR - the use of `GoogleBigQueryConstants.PARTITION_DECORATOR`. Follow-up ticket https://github.com/apache/camel-quarkus/issues/4025 is created to cover this option (if possible)

### CODE REVIEW

**Comment by jamesnetherton** [comment]
Windows build failed because there's no docker environment there. But....

If we're using WireMock to stub the BigQuery APIs, why are we starting containers?

**Comment by JiriOndrusek** [comment]
There are 2 options of starting wiremock server. Programatically or via docker. I don't see any advantages for any of those options. So I went with wiremock started by docker (just because docker is heavily used in other tests).

**Comment by JiriOndrusek** [comment]
PR is changed to leverage `camel-quarkus-integration-wiremock-support` and do not use containers.

**Comment by JiriOndrusek** [comment]
Rebased to avoid build test failure.

**Comment by JiriOndrusek** [comment]
Parameters in the format ${name} are not tested  (see https://camel.apache.org/components/3.18.x/google-bigquery-sql-component.html#_uri_format). Switching to the draft to add this test coverage.

**Comment by JiriOndrusek** [comment]
The small missing coverage was added  (and another camel Issue discovered https://issues.apache.org/jira/browse/CAMEL-18437, which affects follow-up issue: https://github.com/apache/camel-quarkus/issues/4029)
PR is ready to be merged.

**Comment by JiriOndrusek** [comment]
PR is ready for approval and merge. Failed build (ftp) is not linked to this PR

**Review by zbendhiba — APPROVED** [review]

**Review by jamesnetherton — APPROVED** [review]

**Pull request merged**
