### PR TITLE
Description updates for JSON serialization and deserialization extensions

### PR DESCRIPTION
**Pull request by rsvoboda**
Description updates for JSON serialization and deserialization extensions

Trivial change, removed the content of PR template.

Duplicated descriptions are visible on https://code.quarkus.io

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Thanks, but this needs to be done in the main camel repository. The descriptions are coming from the camel catalog metadata.

**Comment by ppalaga** [comment]
Thanks, Rosťo, for the report. @oscerd is right, the data comes from Camel, although a different local fix is possible too. I'll take care.

**Comment by rsvoboda** [comment]
@ppalaga thanks, please share the link for your changes so I know where to look next time.

**Comment by ppalaga** [comment]
Superceded by https://github.com/apache/camel-quarkus/pull/1832

**Pull request closed without merging**
