### PR TITLE
Merge camel-quarkus-main into camel-quarkus-core #2358

### LINKED ISSUE #2358: Merge camel-quarkus-main into camel-quarkus-core
The split does not have any practical meaning anymore. Some main functionalities should become disableable through configuration.

### PR DESCRIPTION
**Pull request by ppalaga**
Fix #2358
This is the idea. @lburgazzoli could you please review? Does this fulfill your definition of disableability?

Docs is TBD.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
LGTM

**Review by lburgazzoli — APPROVED** [review]

**Comment by ppalaga** [comment]
d3eeeac : fixed formatting

**Comment by ppalaga** [comment]
a6a69f2 : more formatting fixes

**Comment by ppalaga** [comment]
59a885c : even more formatting fixups

**Comment by ppalaga** [comment]
f09fb14 rebased on top of the current master

**Comment by ppalaga** [comment]
Filed https://github.com/apache/camel-quarkus/issues/2384 for the `master` component failure. `master` and all subsequent tests from the group passed for me locally. Thus merging.

**Pull request merged**
