### PR TITLE
Revisit #1017 Be even less intrusive when registering our Transformer…

### PR DESCRIPTION
**Pull request by ppalaga**
@lburgazzoli made me think about #1017 again after merging the first attempt #1018. He asked which service files get embedded into the native image. The previous attempt vastly ignored the question and forced our factory via system property. 

As a matter of fact, when multiple service files are available for the same path, using ServiceProviderBuildItem or NativeImageResourceBuildItem will always embed only one of them. There is not only no control which one is picked, but also the winner is different across GraalVM 19.3.1-java8, 19.3.1-java11, 20.0.0-java8 and 20.0.0-java11. So I am coming with the current proposal that pushes our preferred service file using low level GraaVM means. Using this mechanism, there is no need to mess with the system property and thus there is also no need to make it configurable (the user can use the system property on the command line to override our service file).

### CODE REVIEW

**Comment by lburgazzoli** [comment]
Is this also taking care of forcing our impl in jvm mode ?

**Comment by ppalaga** [comment]
> Is this also taking care of forcing our impl in jvm mode ?

It makes its best to do so. Our service file is written to the app, where it should™ be seen as the first and thus be the only effective one: https://github.com/apache/camel-quarkus/pull/1027/files#diff-27a4882bb0ecf7b9d1f46376b12351e9R79-R82

**Comment by lburgazzoli** [comment]
Ah ok was confused because that core in the `XalanNativeImageProcessor` whereas it should probably bee moved to the `XalanProcessor` as it is not native specific

**Comment by ppalaga** [comment]
All tests from the failing group are passing for me locally.

**Pull request merged**
