### PR TITLE
Update Salesforce testCDCAndStreamingEvents test to wait for consumin…

### LINKED ISSUE #3103: Salesforce integration tests: possible failures
Depending on the order in which the tests are run, the _testCDCAndStreamingEvents_ can get the wrong Document, and the test can fail.

### PR DESCRIPTION
**Pull request by zbendhiba**
…g the right Document

Fixes #3103

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by aldettinger — APPROVED** [review]

**Comment by zbendhiba** [comment]
I don't know why the functional-extensions-tests-and-docs are failing. Do you think it's related to this PR, or do we have an issue ?

**Comment by aldettinger** [comment]
I don't know too. But I think it's not related. It happened on other PRs as well.

**Review by ppalaga — COMMENTED** [review]
The documentation xref checks seem to have nothing to do with Camel Quarkus. I see only broken links in Camel and pointing to Camel. Can we safely ignore this, @zregvart?

For this PR I must say I do not understand how these changes fix the linked issue? You switched from a server side 10s await `consumerTemplate.receiveBody()` to test side 10s polling which sounds like no substantial change. How is that addressing the wrong document due to test ordering?

**Comment by ppalaga** [comment]
> The documentation xref checks seem to have nothing to do with Camel Quarkus. I see only broken links in Camel and pointing to Camel. Can we safely ignore this, @zregvart?

Unping @zregvart, sorry for disturbing, it looks like there is a solution already: https://github.com/apache/camel-quarkus/pull/3110

**Comment by zbendhiba** [comment]
> The documentation xref checks seem to have nothing to do with Camel Quarkus. I see only broken links in Camel and pointing to Camel. Can we safely ignore this, @zregvart?
> 
> For this PR I must say I do not understand how these changes fix the linked issue? You switched from a server side 10s await `consumerTemplate.receiveBody()` to test side 10s polling which sounds like no substantial change. How is that addressing the wrong document due to test ordering?

The problem is not with the time, but what Account is consumed first. it's about testing the id of the account. If the consumers got the other account from another method first, the tests don't pass. So I wanted to poll multiple times until I get the right Account.
Is that make sense ?

**Comment by zbendhiba** [comment]
@ppalaga well I've done multiple tests locally. It did poll until it finds the right Account, but sometimes 1000s is not enough to poll the first one.
So I'm going to add more time to the consumer

**Review by ppalaga — APPROVED** [review]
Thanks for the explanation, @zbendhiba makes sense

**Comment by zbendhiba** [comment]
The netty failing tests seems not related to this

**Comment by ppalaga** [comment]
> The netty failing tests seems not related to this

I do not remember to have seen anything like that before. I have restarted the tests to see whether it persists.

**Comment by zbendhiba** [comment]
thanks @ppalaga

**Pull request merged**
