### PR TITLE
Upgrade to Debezium 1.3.0.Final

### PR DESCRIPTION
**Pull request by ppalaga**
... as proposed by Quarkus https://github.com/quarkusio/quarkus/pull/12561

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by ppalaga** [comment]
I checked the tests that failed in the previous CI run and they passed for me locally. I have rebased and restarted the CI.

**Comment by ppalaga** [comment]
This can be merged, WDYT @jamesnetherton ?

**Comment by jamesnetherton** [comment]
> This can be merged, WDYT @jamesnetherton ?

Yes, probably. Mind that the MySQL tests are skipped by default, so we may want to verify those locally before merging if you've not already done that.

**Comment by ppalaga** [comment]
The tests with SQL Server and MySQL enabled pass for me locally.

**Pull request merged**
