### PR TITLE
Split json dataformats to different modules

### LINKED ISSUE #3088: Split JSON dataformats test
The test is currently covering various JSON dataformats. We should split it per JSON extension to be able to test in isolation.

### PR DESCRIPTION
**Pull request by ldrozdo**
Fix #3088

### CODE REVIEW

**Comment by ldrozdo** [comment]
Hi @ppalaga, @aldettinger , can you please review? I closed the previous PR because there were too many conflicts and it broke lot of the code. 
One thing about this PR: I know that the classes in model could be extracted to `integration-tests-support`, but I tried it and I had some problems with native mode. I can play with it later.

**Comment by aldettinger** [comment]
Looking the first check `validate PR Style / check-format (pull_request) `, reports `Some files do not have the expected license header`. It might be a matter of formatting, there are instructions that can be followed when creating a pr (commented in pr text content).

**Review by oscerd — APPROVED** [review]

**Comment by aldettinger** [comment]
`group-07` tests are failing due to `Could not find the selected project in the reactor: integration-tests/dataformats-json`.
Was the project correctly renamed in `tooling/scripts/test-categories` ?

Keep up on this track. It's good to see progress :+1:

**Review by aldettinger — APPROVED** [review]
Looks good to me :+1: Let's see how the ci run goes and then we can squash/merge.

@ldrozdo Good job. Would there be value in splitting jackson and jacksonxml itests in a next pr ?

**Comment by ldrozdo** [comment]
@aldettinger thank you!  Yes, for sure we can split it, I will add it to my backlog :)

**Comment by aldettinger** [comment]
@ldrozdo Could you please recall what ticket it is about ?

By the way, we generally and up the commit message with #ticket number to find it easily.

**Comment by aldettinger** [comment]
> @ldrozdo Could you please recall what ticket it is about ?
> 
> By the way, we generally and up the commit message with #ticket number to find it easily.

Ok, it was mentioned in the first note. I've re-opened the ticket to include the jackson/jacksonxml split.

**Comment by zbendhiba** [comment]
Thanks @ldrozdo for your contribution

**Pull request merged**
