### PR TITLE
Fix #494 Group catalog re-generation and formatting mojos under a sin…

### LINKED ISSUE #494: Group catalog re-generation and formatting mojos under a single profile
Proposed by @lburgazzoli https://github.com/apache/camel-quarkus/pull/492#discussion_r352280609

### PR DESCRIPTION
**Pull request by ppalaga**
…gle profile

### CODE REVIEW

**Comment by oscerd** [comment]
ok to test

**Comment by ppalaga** [comment]
d20e251 fixes a typo

**Comment by lburgazzoli** [comment]
ok to test

**Comment by ppalaga** [comment]
Do we need to re-run the tests because of the Kafka timeout?

**Pull request merged**
