### PR TITLE
add affinity dependency in a mac profile for camel-hazelcast extensio…

### PR DESCRIPTION
**Pull request by ffang**
…n #2800

### CODE REVIEW

**Comment by ppalaga** [comment]
Let's whether they accept the profile in Hazelcast https://github.com/hazelcast/quarkus-hazelcast-client/issues/189 If they do we wouldn't need the profile here, would we?

**Comment by ffang** [comment]
> Let's whether they accept the profile in Hazelcast [hazelcast/quarkus-hazelcast-client#189](https://github.com/hazelcast/quarkus-hazelcast-client/issues/189) If they do we wouldn't need the profile here, would we?

Hi @ppalaga ,

Yes, we don't need this if can fix it up from quarkus-hazelcast-client side, aslo sent a PR there
https://github.com/hazelcast/quarkus-hazelcast-client/pull/190

Let's wait a bit to see if they can accept this PR.

Cheers
Freeman

**Comment by jamesnetherton** [comment]
The project aligns to 2.0.0 so I guess this PR can be closed now?

**Comment by ffang** [comment]
Thanks @jamesnetherton for the heads up, yes we can close this PR now.

**Pull request closed without merging**
