### PR TITLE
Minio native support #2040

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/apache/camel-quarkus/issues/2040

[ ] An issue should be filed for the change unless this is a trivial change (fixing a typo or similar). One issue should ideally be fixed by not more than one commit and the other way round, each commit should fix just one issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful and properly spelled subject line and body. Copying the title of the associated issue is typically enough. Please include the issue number in the commit message prefixed by #.
[ ] The pull request description should explain what the pull request does, how, and why. If the info is available in the associated issue or some other external document, a link is enough.
[ ] Phrases like Fix #<issueNumber> or Fixes #<issueNumber> will auto-close the named issue upon merging the pull request. Using them is typically a good idea.
[ ] Please run mvn process-resources -Pformat (and amend the changes if necessary) before sending the pull request.
[ ] Contributor guide is your good friend: https://camel.apache.org/camel-quarkus/latest/contributor-guide.html

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by jamesnetherton — COMMENTED** [review]
I've not done a full review yet, but I have some comments / questions.

* Seems `mysql-connector-java-8.0.20.jar` was committed by mistake.

* Any reason why we are not leveraging `quarkiverse-minio`? In theory it has already solved the Minio native support, so we'd not have to duplicate it here.

**Comment by JiriOndrusek** [comment]
@jamesnetherton thanks for the reviewing

- `mysql-connector-java-8.0` was commited by mistake, it should be now reverted

- about `quarkiverse-minio` - this is my mistake. I was preparing this extension before the Christmas, when camel was using older version of minio (7.1.4), quarkiverse is using 8.x. Today the version from camel is 8.0.3, which is the same as in quarkiverse. Today I've fixed my previous work and using quarkiverse doesn't occur to me.
- I try to look into a possibility to use existing extension and not to duplicate some code.

**Comment by JiriOndrusek** [comment]
@jamesnetherton I'm facing a problem with quarkiverse-minio. Extension is meant to create minio client (seems to be the main purpose of extension). It requires mandatory configuration for the client - [source](https://github.com/quarkiverse/quarkiverse-minio/blob/master/runtime/src/main/java/io/quarkiverse/minio/client/MinioProducer.java).

It should be possible to use quakiverse extension from cq if this client was not present (camel component is able to create its own client for each endpoint if necessary [source](https://github.com/apache/camel/blob/master/components/camel-minio/src/main/java/org/apache/camel/component/minio/MinioEndpoint.java#L87)

I can possibly imagine solution with quarkiverse, when the client created by quarkiverse could be used by camel component. But this approach would require to fill connection parameters even if user then decides to use some kind of dynamic values in endpoint parameters.

WDYT?

**Comment by jamesnetherton** [comment]
> even if user then decides to use some kind of dynamic values in endpoint parameters

I actually encountered a similar thing when I implemented Google BigQuery native support, which leverages a quarkiverse extension. There's a `projectId` config param that has to be specified:

https://github.com/apache/camel-quarkus/blob/master/integration-tests/google-bigquery/src/main/resources/application.properties#L19

For the initial implementation we could state in the docs that it's mandatory to configure the Minio client using the Quarkus way and Camel will autowire it into the Mino component. Then later we revisit this and try to improve things.

Alternatively, we could forget about leveraging the quarkiverse extension altogether and just do our own thing (not my preference).

@ppalaga @aldettinger @zbendhiba WDYT?

**Comment by aldettinger** [comment]
I would stick to quarkiverse as far as possible. Chances are that we'll find at trick to handle those kind of situations later on.

**Comment by ppalaga** [comment]
Yes, I'd also prefer reusing the quarkiverse extension as far as possible, possibly proposing changes there to get a better support for our use cases. Doing our own thing should be reserved for situations where there are serious technical/design obstacles between us and them.

**Comment by JiriOndrusek** [comment]
Thanks for the suggestions. I'll use quarkiverse extension. 

I'm closing this PR because current solution is not the preferred one.

**Pull request closed without merging**
