### PR TITLE
Fix typo in Azure ServiceBus docs

### PR DESCRIPTION
**Pull request by ldrozdo**

### CODE REVIEW

**Comment by ldrozdo** [comment]
@zbendhiba FYI

**Review by aldettinger — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
Unfortunately, this wont work. These descriptions are driven from the Camel component metadata:

https://github.com/apache/camel/blob/main/components/camel-azure/camel-azure-servicebus/src/main/java/org/apache/camel/component/azure/servicebus/ServiceBusEndpoint.java#L29

**Review by oscerd — CHANGES_REQUESTED** [review]
Please raise an issue or fix this on Apache Camel repository. Thanks @jamesnetherton @ldrozdo

**Comment by ldrozdo** [comment]
Thanks @jamesnetherton @oscerd , sorry I didn't know. I've raised an issue https://issues.apache.org/jira/browse/CAMEL-19908 because I'm not sure if I will know all the right places where to change it.

**Pull request closed without merging**
