### PR TITLE
perf-regression: add integration tests #3982

### PR DESCRIPTION
**Pull request by aldettinger**

### CODE REVIEW

**Comment by aldettinger** [comment]
Please do not merge. It is needed to check whether it build on CI and how to run `mvn clean verify` on perf-regression.

**Comment by aldettinger** [comment]
@jamesnetherton @ppalaga With `mvn clean verify`, we could early detect potential breakage in the `perf-regression` tool before using it during the release.

How could we run those integration tests for each PR during CI checks ? I guess trying to list `perf-regression` in a test group is a bad idea ?

**Comment by jamesnetherton** [comment]
> How could we run those integration tests for each PR during CI checks

Probably best to add it as another task here:

https://github.com/apache/camel-quarkus/blob/main/.github/workflows/ci-build.yaml#L196

The overhead is probably minimal.

**Comment by aldettinger** [comment]
Looks good to me, it's ready for review.

**Review by jamesnetherton — APPROVED** [review]

**Review by zhfeng — APPROVED** [review]

**Pull request merged**
