### PR TITLE
Fix #4128 add a dependabot to upgrade quarkiverse versions

### LINKED ISSUE #4128: Dependabot to upgrade quarkiverse versions
Have a way to automatic to upgrade quarkiverse versions, if possible ?

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by aldettinger** [comment]
Good time to experiment with new tools right after a release. Thus few questions.

Will dependabot upgrade versions only linked to CVEs ?
Or upgrade to any new release quarkiverse.* version available ?

Also, in case a new quarkiverse.* version is available but we would skip it in camel-quarkus, because of a bug for instance. Then, how could we skip that version ?

**Comment by zhfeng** [comment]
It could open a PR for any new release of  quarkiverse artifacts we are using. More details on https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

Of casue we can skip a version if it is not feasible for merging.

**Comment by aldettinger** [comment]
So, when we want to skip a version. Then we just modify the yaml file ?
That would be a nice way to document what quarkiverse updates are dangling.

**Comment by zhfeng** [comment]
yeah. I think we can use `ignore` in yaml file to skip some artifacts or some version we don't want to update.

**Review by aldettinger — APPROVED** [review]
Ok, thanks for sharing @zhfeng. I would vote to experiment with this.

I wonder what other think ?

**Comment by jamesnetherton** [comment]
> I would vote to experiment with this.
> 
> I wonder what other think ?

Yeah let's see how it works for us.

For `quarkus-amazon-services` we maybe need to be a bit careful. I don't think we always want to merge version upgrades, given that project is a Quarkus Platform member and we should not use a version higher than what is specified there.

**Comment by aldettinger** [comment]
Indeed, well spotted, not all updates are to be consumed.

Also, I'm thinking the dependabot approach would encourage to increase each quarkiverse.* version independently. I see this as a benefit at this stage.

**Review by ppalaga — APPROVED** [review]

**Comment by zbendhiba** [comment]
Many thanks! This is awesome and helpful.
Just quick question, will it open a PR every time a new quarkiverse dependency is released ?

**Comment by zhfeng** [comment]
@zbendhiba yeah, it checks daily and will open a PR for new release of quarkiverse.

**Pull request merged**
