### PR TITLE
Default to JDK 11 source & target compiler options

### PR DESCRIPTION
**Pull request by jamesnetherton**
I don't see any reason to maintain Java 8 source compatibility now that Quarkus 2.x has dropped support for it.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by aldettinger** [comment]
Yeah, and there might even be more Java 8 cleanups. Just one thing to keep in mind, last time we have done Java 8 cleanups there was an issue as there was still a Java 8 build on quarkus-platform. Not sure the build is still there however.

**Review by aldettinger — APPROVED** [review]

**Comment by jamesnetherton** [comment]
> Not sure the build is still there however.

Yeah, I checked and platform is only building on 11 now.

**Comment by zbendhiba** [comment]
@jamesnetherton @aldettinger there are some graal substitutions to clean up
for example this one https://github.com/apache/camel-quarkus/blob/7d56d88595496f78c3f8c985f4feb0d103b77aaf/extensions-support/xalan/runtime/src/main/java/org/apache/camel/quarkus/support/xalan/graal/SunTemplatesImplSubstitution.java#L29

**Review by zbendhiba — APPROVED** [review]

**Comment by jamesnetherton** [comment]
> @jamesnetherton @aldettinger there are some graal substitutions to clean up

Thanks - latest commit cleans those up.

**Pull request merged**
