### PR TITLE
Crypto (JCE) native support

### LINKED ISSUE #1593: Crypto (JCE) native support

### PR DESCRIPTION
**Pull request by jamesnetherton**
Fixes #1593

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by aldettinger** [comment]
Good PR @jamesnetherton . Just a note that I have spotted this [guy](https://github.com/apache/camel/blob/master/components/camel-crypto/src/main/java/org/apache/camel/component/crypto/processor/DigitalSignatureProcessor.java#L91), I wonder if it's covered.

**Review by aldettinger — APPROVED** [review]

**Comment by jamesnetherton** [comment]
> Just a note that I have spotted this [guy](https://github.com/apache/camel/blob/master/components/camel-crypto/src/main/java/org/apache/camel/component/crypto/processor/DigitalSignatureProcessor.java#L91), I wonder if it's covered.

Good spot! Kind of a weird way to clear headers :smiley:. Unsurprisingly, `getFields` returns an empty array in native mode.

I can follow up with a workaround and then fix properly on the Camel side.

**Comment by jamesnetherton** [comment]
I raised https://github.com/apache/camel-quarkus/issues/1881.

**Review by ppalaga — COMMENTED** [review]
It would be nice to have a README with the info how the pgp and jks files were created for the case that we need to alter them in the future

**Comment by jamesnetherton** [comment]
> It would be nice to have a README with the info how the pgp and jks files were created for the case that we need to alter them in the future

I stole them from the Camel tests :-). But I can see if I can put something together.

**Pull request merged**
