### PR TITLE
Upgrade Camel to 3.17.0

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by zhfeng — APPROVED** [review]

**Review by zbendhiba — APPROVED** [review]

**Comment by zbendhiba** [comment]
@jamesnetherton Do we need to mention all those deleted extensions we are deleting with 3.17 upgrade in some release guide.

**Comment by jamesnetherton** [comment]
> @jamesnetherton Do we need to mention all those deleted extensions we are deleting with 3.17 upgrade in some release guide.

My thought was to mention it on the release blog post + link to the Camel 3.17 release notes. Do you think that's enough?

**Review by aldettinger — APPROVED** [review]
Looks good to me. In previous releases, it happens that we mentioned extensions deprecation and removal in the migration guide.

**Comment by jamesnetherton** [comment]
> we mentioned extensions deprecation and removal in the migration guide

Ok. I will follow up with some notes in a migration guide doc.

**Comment by zbendhiba** [comment]
I think it's a safe habit to add to the migration guide. We are sure it's there and easy to track while writing the release blog post.

**Pull request merged**
