### PR TITLE
Fixed FastCamelContext with recent changs in camel master

### PR DESCRIPTION
**Pull request by JiriOndrusek**
Fixed compilation issues introduced into camel-master (https://github.com/apache/camel/commit/97cd7552a922f510dc7fc4565e3558d2f419d283)

@jamesnetherton @ppalaga I don't orient fully in these core parts, but tests are successful.

[ ] An issue should be filed for the change unless this is a trivial change (fixing a typo or similar). One issue should ideally be fixed by not more than one commit and the other way round, each commit should fix just one issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful and properly spelled subject line and body. Copying the title of the associated issue is typically enough. Please include the issue number in the commit message prefixed by #.
[ ] The pull request description should explain what the pull request does, how, and why. If the info is available in the associated issue or some other external document, a link is enough.
[ ] Phrases like Fix #<issueNumber> or Fixes #<issueNumber> will auto-close the named issue upon merging the pull request. Using them is typically a good idea.
[ ] Please run mvn process-resources -Pformat (and amend the changes if necessary) before sending the pull request.
[ ] Contributor guide is your good friend: https://camel.apache.org/camel-quarkus/latest/contributor-guide.html

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by JiriOndrusek** [comment]
This is not complete, I see that `Main :: Runtime` contains some other compilation issues.

**Comment by jamesnetherton** [comment]
I think @lburgazzoli was going to look at getting the camel-master branch working again.

**Comment by lburgazzoli** [comment]
argh, was doing the same thing :)

**Comment by JiriOndrusek** [comment]
@lburgazzoli  I'll let it to you, as an author of changes in camel, it would be much easier for you.
I've noticed it, because I'm starting to work on some new extension, which requires camel 3.8.0-SNAPSHOT....

**Pull request closed without merging**
