### PR TITLE
Re-enable google-bigquery and add a work around

### PR DESCRIPTION
**Pull request by zhfeng**
Exclude `org.apache.arrow:arrow-memory-netty` because it is not compatible with the lastest netty `4.1.94.Final`.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
We should add the same doc notes for the workaround like we did for pubsub & storage.

Also, not sure how safe the Arrow exclusion is. It is referenced in a few places:

https://github.com/search?q=repo%3Agoogleapis%2Fjava-bigquery+arrow+language%3AJava&type=code&l=Java

I guess the fact that the native compilation + tests passed means that maybe we don't hit those code paths in Camel...

**Comment by zhfeng** [comment]
Yeah, it is exactly what I was concerned. It seems that `google-bigquery` default uses `DataFormat.ARROW` when read/write a large data table result.

We don't hit those codes because  we lack of a test for the large table. So how can write a sentence for this limitation?

**Comment by jamesnetherton** [comment]
Thinking a bit more, I'm not sure I like excluding Arrow because it potentially impacts negatively on JVM mode, and the issue is purely a native mode one.

**Comment by jamesnetherton** [comment]
@zhfeng is it just the shaded Netty of Arrow that is causing the problem? If Arrow does not modify any of the Netty bits, maybe we could try something similar to what we did for Kudu and shaded Netty? See here: https://github.com/apache/camel-quarkus/pull/2008 & https://github.com/apache/camel-quarkus/issues/1907.

**Comment by zhfeng** [comment]
@jamesnetherton I think `apache-arrow` does not shade Netty. The problem is Quarkus 3.2.0.Final update Netty to `4.1.94.Final` and there is an un-compatible change in `PooledByteBufAllocator`. So I think it could also impact the JVM mode if we test with a large table.

The fix in `apache-arrow` is https://github.com/apache/arrow/commit/ea4f03ac166e3961b59f29f60dcd160fbed29894#diff-d967dd684919ce097b81e439fafc96217f1263985f5864faa4b78eb96e7a4f16L164

So is it possible to have this file in our `camel-quarkus-google-bigquery`?

**Comment by jamesnetherton** [comment]
Ah, yeah. Sorry for the confusion!

> So is it possible to have this file in our camel-quarkus-google-bigquery?

We could temporarily have it in our extension. Quarkus has `RemovedResourceBuildItem`, not sure if that could also be used to remove the bad impl from Arrow?

If it becomes too much work. Maybe we just stick with the original plan of removing Arrow until we get the fix.

**Comment by zhfeng** [comment]
Sine `org.apache.arrow:arrow-memory-netty` is a runtime dependency, `RemovedResourceBuildItem` seems not working. I just try to copy 4 files from `apache-arrow`
- LargeBuffer.java
- MutableWrappedByteBuf.java
- PooledByteBufAllocatorL.java
- UnsafeDirectLittleEndian.java

and apply the fix for `PooledByteBufAllocatorL.java`. All of the `google-bigquery` tests look good both in JVM and native mode.

Also I think we need a test for a large table and enable the result with arrow data format. Can it be supported by wiremock?

**Comment by ppalaga** [comment]
> storing huge files for the stubbed data

We could perhaps generate those at build time?

**Comment by zhfeng** [comment]
I raise 
- https://github.com/apache/camel-quarkus/issues/5048

**Review by jamesnetherton — APPROVED** [review]

**Pull request merged**
