### PR TITLE
[fix] Enforce correct maven version

### PR DESCRIPTION
**Pull request by llowinge**

### CODE REVIEW

**Review by ppalaga — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Review by aldettinger — APPROVED** [review]

**Comment by llowinge** [comment]
@ppalaga Do you know if the error from GH action is connected to my PR ?

```
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (yarn-install) on project camel-quarkus-docs: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (yarn-install) on project camel-quarkus-docs: Command execution failed.
```

**Comment by ppalaga** [comment]
No, it is not related, it happened in this other PR https://github.com/apache/camel-quarkus/pull/2440 We need to fix it first.

**Comment by ppalaga** [comment]
Let's see if this helps: https://github.com/apache/camel-quarkus/pull/2446

**Comment by ppalaga** [comment]
#2446 is merged. Could you plz rebase?

**Pull request merged**
