### PR TITLE
Upgrade to Camel 4.0.0 and Quarkus 3.0.0.Alpha3

### PR DESCRIPTION
**Pull request by ppalaga**
Replaces https://github.com/apache/camel-quarkus/pull/4479

Fix https://github.com/apache/camel-quarkus/issues/4491
Fix https://github.com/apache/camel-quarkus/issues/4415
Fix https://github.com/apache/camel-quarkus/issues/4493
Fix https://github.com/apache/camel-quarkus/issues/4496
Fix https://github.com/apache/camel-quarkus/issues/4508

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by ppalaga** [comment]
Iteration ending with 2db94a6:

* Upgrade to quarkiverse-mybatis 2.0.0.CR1, thus fixing https://github.com/apache/camel-quarkus/issues/4491

**Comment by jamesnetherton** [comment]
@ppalaga Shall we just disable the problematic tests and get this merged to `main`?

**Comment by ppalaga** [comment]
91c6a19:

* Fixed some tests
* Created issues for the failing tests 
* Disabled the failing tests

**Comment by ppalaga** [comment]
230718e:

* Fixed #4496
* Reported more issues and disabled more tests

**Comment by ppalaga** [comment]
211ebd3: 

* Fixed the native failure in aws2-grouped test by adding aws-crt dependency to our s3 extension
* Upgraded to QFreemarker 1.0.0.Alpha1 thus fixing https://github.com/apache/camel-quarkus/issues/4508
* Disabled PerfRegressionIT https://github.com/apache/camel-quarkus/issues/4528

**Pull request merged**
