### PR TITLE
WiP: Upgrade to Camel 3.1.0

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@jamesnetherton @ppalaga can we close this one since we have now a camel-master branch that builds against camel 3.1  ?

**Comment by ppalaga** [comment]
Have all commits from here been ported to master?

**Comment by jamesnetherton** [comment]
We should close this now that we have a dedicated `camel-master` branch for the 3.1 upgrade.

I chose to redo the branch from scratch as this one was massively out of date, given all of the changes that have happened on the camel side. 

I wanted to keep changes to a minimum, so have not pulled in the telegram stuff or the fix for #518 (yet).

**Comment by ppalaga** [comment]
Replaced by https://github.com/apache/camel-quarkus/pull/698

**Pull request closed without merging**
