### PR TITLE
Update mvnd.builder.rules

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
The previous iteration failed on a dependency download again. Lets try with `-Dmaven.wagon.http.retryHandler.requestSentEnabled=true` in 748db16

**Comment by lburgazzoli** [comment]
You probably need to add somewhere what mvnd is and what's the meaning of the rules

**Comment by ppalaga** [comment]
Added comments in a8526df

**Comment by lburgazzoli** [comment]
LGTM

@ppalaga Wonder if mvnd should have a way to extend through service loader mechanism so one could contribute a logic to compute the rules without polluting the poms

**Comment by ppalaga** [comment]
Sounds interesting. Would you mind proposing it via https://github.com/gnodet/mvnd/issues/new %

**Comment by lburgazzoli** [comment]
maven download seems very unstable

**Pull request merged**
