### PR TITLE
Fix lambda tests on localstack #2595

### PR DESCRIPTION
**Pull request by aldettinger**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by aldettinger** [comment]
AWS lambda tests were not working previously on localstack. Switching to python solves the issue as python seems to be present built-in in localstack container.

**Review by jamesnetherton — APPROVED** [review]

**Review by ppalaga — APPROVED** [review]
How, how simple and elegant!

**Review by zbendhiba — APPROVED** [review]
Nice !

**Comment by aldettinger** [comment]
On CI, the lambda test is working in isolation but not grouped. I cannot reproduce this behavior locally, so I may need to push few investigation commits on this PR.

**Pull request merged**
