### PR TITLE
Remove use of Xalan #4065

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/apache/camel-quarkus/issues/4065

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by zhfeng — APPROVED** [review]

**Review by aldettinger — APPROVED** [review]

**Comment by JiriOndrusek** [comment]
The CI failure is caused by this change. There seems to be a problem with generation of some classes.

```
Caused by: javax.xml.transform.TransformerConfigurationException: Cannot find class 'org.apache.camel.quarkus.component.xslt.generated.HtmlTransform'.
2022-09-02T10:44:40.1852572Z 	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:903)
2022-09-02T10:44:40.1853455Z 	at org.apache.camel.quarkus.support.xalan.XalanTransformerFactory.newTemplates(XalanTransformerFactory.java:70)
2022-09-02T10:44:40.1854276Z 	at org.apache.camel.component.xslt.XsltBuilder.setTransformerSource(XsltBuilder.java:345)
2022-09-02T10:44:40.1855004Z 	at org.apache.camel.component.xslt.XsltEndpoint.loadResource(XsltEndpoint.java:326)
2022-09-02T10:44:40.1855675Z 	at org.apache.camel.component.xslt.XsltEndpoint.doInit(XsltEndpoint.java:342)
2022-09-02T10:44:40.1856270Z 	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
```

I'm going to search for a better fix.

**Comment by zhfeng** [comment]
@JiriOndrusek the JDK issue fixed?

**Comment by JiriOndrusek** [comment]
@zhfeng TBH I wasn't able to confirm fix in jdk, but I retested with current `main` branch and it works (both jvm and native) -> I made a small change because of jvm

**Comment by JiriOndrusek** [comment]
Error is still there I accidentally verified only `xmlsecurity` - hence the native fix, and not `xml` security

**Comment by jamesnetherton** [comment]
Closing as we can't realistically do this for the reasons outlined in https://github.com/apache/camel-quarkus/issues/4065.

**Pull request closed without merging**
