### PR TITLE
Fix #3496 Ban javax.servlet:javax.servlet-api in favor of jakarta.ser…

### LINKED ISSUE #3496: Ban javax.servlet:servlet-api in favor of jakarta.servlet:jakarta.servlet-api
We should add rules like they have in Quarkus and do replacements where necessary
```
                                            <exclude>javax.servlet:servlet-api</exclude>
                                            <exclude>javax.servlet:javax.servlet-api</exclude>
```

### PR DESCRIPTION
**Pull request by zhfeng**
…vlet:jakarta.servlet-api

### CODE REVIEW

**Review by aldettinger — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Review by zbendhiba — APPROVED** [review]

**Review by ppalaga — APPROVED** [review]
Thanks @zhfeng ! Could you please prepare a backport PR for [2.7.x](https://github.com/apache/camel-quarkus/tree/2.7.x) branch?

**Comment by ppalaga** [comment]
Any chance to backport to 2.7.x @zhfeng?

**Comment by jamesnetherton** [comment]
> Any chance to backport to 2.7.x @zhfeng?

He's currently on PTO I believe.

**Comment by ppalaga** [comment]
OK, let me backport together with https://github.com/apache/camel-quarkus/pull/3518

**Comment by ppalaga** [comment]
The backport PR: https://github.com/apache/camel-quarkus/pull/3519

**Comment by zhfeng** [comment]
Thanks @ppalaga

**Pull request merged**
