### PR TITLE
Fix #41 Re-introduce test scope in integration test projects

### LINKED ISSUE #41: Re-introduce test scope in integration test projects
Once https://github.com/quarkusio/quarkus/issues/3136 get resolved, we can make our integration test projects idiomatic again. This would mean (at least) to re-introduce the `<scope>test</scope>` occurrences that got removed in https://github.com/apache/camel-quarkus/pull/35 .

### PR DESCRIPTION
**Pull request by ppalaga**
@aloubyansky could you please review and eventually test if this works for you?

### CODE REVIEW

**Comment by ppalaga** [comment]
@aloubyansky we'd need to get this merged to avoid potential conflicts, but you are welcome to test or give feedback anyway. If you could please file a new issue if something does not work for you.

**Comment by aloubyansky** [comment]
The first issue is
````
[WARNING] The POM for org.apache.camel.quarkus:camel-quarkus-integration-test-core-tests:jar:0.1.1-SNAPSHOT is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for org.apache.camel.quarkus:camel-quarkus-integration-test-core-tests:0.1.1-SNAPSHOT
[ERROR] 'dependencies.dependency.version' for org.apache.camel.quarkus:camel-quarkus-integration-test-core:jar is missing. @ 
````

**Comment by ppalaga** [comment]
How can I reproduce that error message?

**Comment by aloubyansky** [comment]
mvn dependency:tree

**Comment by aloubyansky** [comment]
I did it for the artifact that depended on the *-tests.

**Comment by ppalaga** [comment]
You need to run `mvn clean install -DskipTests` on this PR's tree, which you did, I assume. It installs all tests jars except for the servlet one (because servlet has a different parent than the others). Did you happen to use the servlet itest in your experiment?

**Comment by ppalaga** [comment]
I blind, your error message says you used `core`.

**Comment by ppalaga** [comment]
e7622d7 fixes the problem reported by @aloubyansky (thanks!)

**Comment by ppalaga** [comment]
Replaced by https://github.com/apache/camel-quarkus/pull/150

**Comment by aloubyansky** [comment]
A class in Quarkus needs a one line adjustment for this approach to work.

**Comment by aloubyansky** [comment]
https://github.com/quarkusio/quarkus/issues/3615

**Pull request closed without merging**
