### PR TITLE
Fix read-lock tests

### PR DESCRIPTION
**Pull request by philschaller**
#2888

### CODE REVIEW

**Comment by aldettinger** [comment]
@philschaller Many thanks for contributing to camel-quarkus :+1:  Apparently, the `fileReadLock_minLength` test appears to fail on the continuous integration after this PR. When clicking the `Details` button on the `Camel Quarkus CI / Native Tests - group-06 (pull_request)` continuous integration check above, we notice the following log:
```
Error:  Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 24.713 s <<< FAILURE! - in org.apache.camel.quarkus.component.file.it.FileTest
Error:  fileReadLock_minLength  Time elapsed: 10.059 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <204> but was <200>.
```

**Comment by philschaller** [comment]
@aldettinger The test will not pass until this Camel issue [1] is fixed. It should have caught that problem without the changes. But my first version of the test from last year was flawed.

[1] https://issues.apache.org/jira/browse/CAMEL-16795

**Comment by zbendhiba** [comment]
@philschaller When your PR is merged in Camel, you can do this PR against camel-main branch, to be on 3.12.SNAPSHOT

**Comment by philschaller** [comment]
@zbendhiba Fix for [1] has been merged into camel-main.

[1] https://issues.apache.org/jira/browse/CAMEL-16795

**Comment by ppalaga** [comment]
I have changed the base branch from main to camel-main

**Comment by jamesnetherton** [comment]
@philschaller Do you mind rebasing your branch with the latest work from `main`. We have upgraded to Camel 3.11.1.

**Comment by aldettinger** [comment]
Many thanks @philschaller :+1:

**Pull request merged**
