### PR TITLE
 Github Actions Security Best practices: Pin Actions to Full lenght C…

### PR DESCRIPTION
**Pull request by oscerd**
…ommit SHA - Assign milestone workflow

### CODE REVIEW

**Comment by ppalaga** [comment]
@oscerd could you please explain, why is this a good practice?

**Comment by oscerd** [comment]
@ppalaga https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

It's suggested to do this for third party, it's not crucial, but even for dependabot it doesn't change that much, it will point the new commit sha on new releases.

**Comment by ppalaga** [comment]
Makes sense, thanks a lot!

**Comment by oscerd** [comment]
I forgot to add the link to the hardening guide. Sorry.

**Pull request merged**
