### PR TITLE
Added nagios native support #1726

### PR DESCRIPTION
**Pull request by aldettinger**
[ ] An issue should be filed for the change unless this is a trivial change (fixing a typo or similar). One issue should ideally be fixed by not more than one commit and the other way round, each commit should fix just one issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful and properly spelled subject line and body. Copying the title of the associated issue is typically enough. Please include the issue number in the commit message prefixed by #.
[ ] The pull request description should explain what the pull request does, how, and why. If the info is available in the associated issue or some other external document, a link is enough.
[ ] Phrases like Fix #<issueNumber> or Fixes #<issueNumber> will auto-close the named issue upon merging the pull request. Using them is typically a good idea.
[ ] Please run mvn process-resources -Pformat (and amend the changes if necessary) before sending the pull request.
[ ] Contributor guide is your good friend: https://camel.apache.org/camel-quarkus/latest/contributor-guide.html

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by ppalaga** [comment]
Overall, this looks good, thanks @aldettinger !

I'd like to ask about some details:

* Since recently, we try to make tests runnable in two modes: real backend service vs. mocked backend. There is also some log message based auditing convention so that interested parties can make sure that the tests were actually run against real services. IIRC, Twillio is one of the recent examples. The current proposal seems to support only the mock mode. I wonder whether the real mode could be supported too? cc @llowinge 
* @jamesnetherton recently started to use WireMock for mocking backend services. I wonder whether it would also make sense to use it also here? I have no idea whether WireMock supports raw TCP.

**Comment by jamesnetherton** [comment]
> * I have no idea whether WireMock supports raw TCP.

Its for HTTP only IIRC.

**Comment by aldettinger** [comment]
Thanks for paying attention to this one guys.
My current understanding is that twilio itests uses wiremock which supports only HTTP based mock server.

In the case at hand, I've explored different options to run a test against a real NSCA server to no avail. So, I've ended up simulating the protocol with camel-netty. On top of that, do we see any improvement/alignment for this PR ?

**Comment by ppalaga** [comment]
> Thanks for paying attention to this one guys.
> My current understanding is that twilio itests uses wiremock which supports only HTTP based mock server.

OK, let's forget about WireMock for raw tC

> In the case at hand, I've explored different options to run a test against a real NSCA server to no avail.

The test does not need to manage the real service. It may well be the responsibility of the testing person to set it up, start it and pass some env vars or similar local config to the test to avoid running against the mock. I guess something like that would be possible with NSCA server?

**Comment by aldettinger** [comment]
It should be possible, but I was not able to set it up in reasonable time. I wonder if we should file a follow up issue ? maybe even in camel ?

**Comment by ppalaga** [comment]
+1, let's file a followup and let @llowinge express his opinion.

**Comment by aldettinger** [comment]
I'm filing #1992 as follow up

**Pull request merged**
