### PR TITLE
Bump Optaplanner to 8.18.0.Final

### PR DESCRIPTION
**Pull request by zbendhiba**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by jamesnetherton — APPROVED** [review]

**Review by zhfeng — APPROVED** [review]

**Comment by zbendhiba** [comment]
I don't understand that failure for syslog tests on Windows.

**Review by aldettinger — APPROVED** [review]

**Comment by zbendhiba** [comment]
I just rebased from main

**Comment by zbendhiba** [comment]
I corrected the format of one of the pom.xml files, hopes it passes the validation :) 
As I don't find any missing file to commit

**Comment by zbendhiba** [comment]
this time it's the gRPC tests on Windows :(

**Comment by zbendhiba** [comment]
thanks @aldettinger for fixing the pom.xml format

**Comment by jamesnetherton** [comment]
The gRPC failure is a known flake https://github.com/apache/camel-quarkus/issues/3037. We're good to merge this IMO.

**Pull request merged**
